<!DOCTYPE html>
<html lang="es">

<head>
    <title>Actualizaciones - 11Cert</title>
    <?php getheader("Actualizaciones - 11Cert", false) ?>
    <link rel="stylesheet" href="./css/update.css">
</head>

<body class="d-flex flex-column h-100">
    <?php getmenu() ?>
    <div class="mt-5 mx-auto w-75" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="changelog-updates">
            <img src="./img/update.svg" class="icono-16 rounded me-2" alt="update">
            <strong class="text-primary me-auto">Actualizaciones</strong>
            <small class="fecha-update"></small>
        </div>
        <div class="justify-content-center row">
            <button type="button" class="update_button back-update btn-primary mshide col-md-auto"><img src="./img/back.svg" class="icono-8" alt="back"></button>
            <div class="level paddingboth-10 col-md-auto"></div>
            <button type="button" class="update_button next-update btn-primary col-md-auto"><img src="./img/next.svg" class="icono-8" alt="next"></button>
        </div>
        <div class="toast-body mt-4">
            <div class="fecha mshide">24/04/2023</div>
            <p>- Se han corregido algunos errores de la vista de ECR.</p>
            <p>- Añadido al selector de estado de seguimiento de PAC "No Aplica".</p>
            <p>- Arreglados varios fallos en el reporte de métricas y madurez de KPMS.</p>
            <p>- Ahora los reportes de KPMS pueden ser editados por el usuario.</p>
            <p>- Los Administradores pueden bloquear o desbloquear los reportes de KPMS y descargarlos.</p>
            <p>- Ahora puedes descargar el Excel de riesgos de varios sistemas a la vez sin tener que cambiar entre ellos.</p>
            <p>- Eliminados algunas alertas intrusivas y mensaje de actualizaciones para no entorpecer el uso de la herramienta.</p>
            <p>- Nueva funcionalidad en historial de servicio para cumplimentar controles No Evaluados a través del gráfico.</p>
            <p>- Se ha incrementado la seguridad de la herramienta.</p>
            <p>- Se ha reestructurado el Dashboard para mostrar un cuadro de mando más organizado.</p>
            <p>- Modificada la tipografía e iconos por los de las guía de marca de Telefónica.</p>
            <p>- Actualizadas librerías de terceros.</p>
            <p>- Otras correcciones y mejoras visuales.</p>
        </div>
        <div class="toast-body mshide mt-4">
            <div class="fecha mshide">23/02/2023</div>
            <p>- Añadida ISO 27002 (2022) completa y con compatibilidad con anterior versión.</p>
            <p>- Modificado el titulo de la pagina de terminos de uso.</p>
            <p>- Actualizadas librerias.</p>
            <p>- Mejorado el control de sesión del usuario.</p>
            <p>- Añadido No Aplica en Prepia de los BIA.</p>
            <p>- Corrección de errores de dashboard y descarga de tablas.</p>
            <p>- Modificadas plantillas de envio de correos de la herramienta.</p>
            <p>- Añadida la versión de la herramienta al final de pagina.</p>
        </div>
        <div class="toast-body mshide mt-4">
            <div class="fecha mshide">16/01/2023</div>
            <p>- Se ha aumentado la seguridad de 11Cert</p>
            <p>- Se ha incluido Términos de uso y las Políticas de Privacidad de 11Cert.</p>
            <p>- Añadida la fecha de ultima modificación de los BIA</p>
            <p>- Añadido datos de ERS en Dashboard</p>
            <p>- Corregidos algunos títulos de paginas</p>
            <p>- Actualizadas librerías de terceros</p>
        </div>
        <div class="toast-body mshide mt-4">
            <div class="fecha mshide">02/12/2022</div>
            <p>- Se han corregido mas de 100 faltas ortográficas/gramaticales (gracias Rubén, esta te la dedico).</p>
            <p>- Se ha implementado un corrector ortográfico al IDE del proyecto para ayudar en la revisión automática de esos errores.</p>
            <p>- Corregido enlace de documentación de KPMS.</p>
            <p>- Ahora tenéis un botón en el historial de activo llamado "Generar ECR" que genera el documento automáticamente.</p>
            <p>- Simplificadas algunas lineas de código y refactorizado métodos.</p>
        </div>
        <div class="toast-body mshide mt-4">
            <div class="fecha mshide">22/11/2022</div>
            <p>- Se ha implementado la posibilidad de reportar <a href="./reportarkpms">KPMS</a>. Se puede acceder a traves del menú</p>
            <p>- Añadido el envío de una copia del reporte de KPMS que se manda por correo electrónico automáticamente al usuario.</a></p>
            <p>- Ahora al crear un activo nuevo de tipo ubicación solo se podrá seleccionar de una lista cerrada.</p>
            <p>- En la tabla de seguimiento de PAC en el cuadro de mando se ha añadido columna del servicio o los servicios a los que pertenece.</p>
            <p>- Eliminado la opción de poner responsable y technical lead en la edición de responsables de los servicios.</p>
            <p>- Corregido un bug que al borrar un activo que tuviese varias dependencias daba errores y no se borraba.</p>
            <p>- Se han corregido y simplificado algunas líneas de código y reestructurado algunos aspectos visuales de la herramienta.</p>
        </div>
        <div class="toast-body mshide mt-4">
            <div class="fecha mshide">28/09/2022</div>
            <p>- Se ha añadido la opción de añadir el Responsable CISO a los servicios.</p>
            <p>- Los activos se pueden marcar ahora como expuestos a internet en el botón de edición.</p>
            <p>- Se ha incluido la ISO27002 del 2022 casi por completo faltan algunos controles.</p>
            <p>- Se ha corregido un bug en los mensajes de error al importar una arquitectura.</p>
        </div>
        <div class="toast-body mshide mt-4">
            <div class="fecha mshide">11/08/2022</div>
            <p>- Se ha añadido la posibilidad de poner responsables a los servicios.</p>
            <p>- Ahora se han agrupado los iconos en la vista de servicios.</p>
            <p>- Se han corregido algunos mensajes de error de la herramienta.</p>
            <p>- Se ha añadido un perfil de solo lectura.</p>
            <p>- El perfil de solo lectura no podrá ejecutar ninguna acción de modificación.</p>
        </div>
        <div class="toast-body mshide mt-4">
            <div class="fecha mshide">23/06/2022</div>
            <p>- Ya se ha corregido el login con O365, puedes loguearte con tu cuenta @telefonica.com.</p>
            <p>- Se ha corregido algunos estilos que se visualizaban de forma incorrecta.</p>
            <p>- Se ha mejorado la seguridad de la herramienta.</p>
            <p>- Corregido un error del estado de icono de BIA e HISTORIAL que a veces aparecía en un color erróneo.</p>
            <p>- Los iconos de servicios se han agrupado para mejorar el aspecto visual.</p>
        </div>
        <div class="toast-body mshide mt-4">
            <div class="fecha mshide">31/03/2022</div>
            <p>- Se han agregado cabeceras CSP seguras.</p>
            <p>- Se han corregido vulnerabilidades detectadas en pentest manual.</p>
            <p>- Solucionadas vulnerabilidades detectadas con análisis de código estático.</p>
            <p>- Corregidos code smells.</p>
            <p>- Se ha corregido algunos estilos y funciones de JS.</p>
            <p>- Actualizada librería de terceros highcharts.</p>
            <p>- Actualizada librería de terceros bootgrid.</p>
            <p>- Han sido corregido bugs derivados de refactorizar funciones.</p>
            <p>- Correcciones en CSS para mejor visualización.</p>
            <p>- Ahora todas las alertas desaparecen en segundos.</p>
            <p>- Listado de servicios ordenados alfabéticamente.</p>
        </div>
        <div class="toast-body mshide mt-4">
            <div class="fecha mshide">11/03/2022</div>
            <p>- Se ha corregido un bug producido al importar un Excel de activos que en algunos casos daba un error al obtener una respuesta no deseada.</p>
            <p>- Solucionado un bug que al introducir una nueva evaluación daba fallo al crear los seguimientos de PAC.</p>
            <p>- En la vista de edición de evaluación se ha añadido cod.usf y cod.pac para ayudar a identificar a que afectan las preguntas.</p>
            <p>- Ahora la sesión caduca a los 5 minutos de inactividad y pide volver a hacer login.</p>
            <p>- El cambio de estado a "Finalizado" de un seguimiento de PAC afecta directamente al resultado de la evaluación.</p>
        </div>
        <div class="toast-body mshide mt-4">
            <div class="fecha mshide">03/03/2022</div>
            <p>- Arreglado un error que hacía que a algunos usuarios les apareciese un servicio sin BIA cuando si tenía BIA cargado.</p>
            <p>- Añadido tag de entornos en vista servicios, ahora se muestran etiquetas en los servicios.</p>
            <p>- Se ha eliminado del selector de la vista servicios Área y Unidad por falta de uso.</p>
            <p>- Se han añadido iconos de los servicios al visualizar por dirección en la vista de servicios.</p>
            <p>- Solucionado un error al importar un cuestionario con fórmulas, ahora muestra un mensaje de error y no se queda colgado.</p>
            <p>- Actualizada la BD con las descripciones y tareas de los proyectos que faltaban.</p>
        </div>
        <div class="toast-body mshide mt-4">
            <div class="fecha mshide">25/02/2022</div>
            <p>- Revisada la ISO22301 y añadido relaciones/preguntas que faltaban.</p>
            <p>- Se ha añadido doble check para el borrado de activos.</p>
            <p>- Solucionado un bug que hacía que a veces en el listado de servicios no mostrase correctamente aquellos servicios sin BIA o SIN ECR.</p>
            <p>- Se han solucionado varias líneas de código y refactorizado funciones.</p>
            <p>- Se ha añadido al cuadro de mando gráficos y tablas para el recuento de seguimientos de PAC.</p>
            <p>- Corregidas algunas faltas ortográficas en diferentes textos del BIA.</p>
            <p>- Solucionado un error al intentar mostrar el BIA de un servicio que no tenía BIA .</p>
        </div>
        <div class="toast-body mshide mt-4">
            <div class="fecha mshide">11/02/2022</div>
            <p>- Implementada la gestión de usuarios para poder crear, eliminar o editar roles desde la herramienta.</p>
            <p>- Se han corregido algunas incidencias detectadas con Sonarqube.</p>
            <p>- Se ha abstraído funciones y métodos para mejorar la lectura del código.</p>
            <p>- Se ha corregido la función encargada de listar los servicios y ahora es más rápido y eficiente.</p>
            <p>- Implementada la creación de seguimientos de PAC automáticos en base a la última evaluación.</p>
        </div>
        <div class="toast-body mshide mt-4">
            <div class="fecha mshide">26/01/2022</div>
            <p>- Se ha habilitado la opción de clonar servicios.</p>
            <p>- Se ha corregido un fallo en el cálculo del BIA que hacía que a veces no mostrase los valores.</p>
            <p>- Corregido el aspecto visual para el reporte de KPMs.</p>
            <p>- Se han mejorado algunas funciones de código.</p>
        </div>
        <div class="toast-body mshide mt-4">
            <div class="fecha mshide">21/01/2022</div>
            <p>- Ahora se pueden archivar sistemas, al archivarlos aparecerán bloqueados en la vista de cuestionario e histórico.</p>
            <p>- Se ha corregido la librería bootgrid que no era compatible con la nueva versión de bootstrap.</p>
            <p>- Se ha cambiado el aspecto de los iconos de las tablas y arreglado varios bug con la interacción de las tablas.</p>
            <p>- Se ha separado el contenido del dashboard para agilizar la carga de datos.</p>
            <p>- Nuevas pestañas en el dashboard para ayudar a obtener más información (Seguimientos de PAC,KPIs,etc).</p>
            <p>- Corregido varios errores en las ventanas modales.</p>
            <p>- Han sido eliminados algunos métodos en el código que no tenían uso.</p>
            <p>- Solucionado varios errores de cálculo en el BIA.</p>
            <p>- En los esquemas visuales de arquitectura de los servicios se ha implementado una opción de zoom-in y zoom-out.</p>
        </div>
        <div class="toast-body mshide mt-4">
            <div class="fecha mshide">09/12/2021</div>
            <p>- Ahora este aviso de actualizaciones desaparece con el tiempo, aunque no lo cierres.</p>
            <p>- Se han actualizado algunas librerías JS y CSS de terceros.</p>
            <p>- Corregido un bug en los mapas de calor que hacía que al cambiar el tamaño de la ventana los gráficos se estirasen.</p>
            <p>- Se han eliminado los valores y promedio que aparecía bajo el mapa de calor de Riesgo actual.</p>
            <p>- Se han corregido estilos y aspecto visual de algunos formularios.</p>
        </div>
        <div class="toast-body mshide mt-4">
            <div class="fecha mshide">01/12/2021</div>
            <p>- Ahora en la vista de BIA se puede visualizar el resultado al cargar y al guardar un nuevo BIA (no se calcula en tiempo real por ahora).</p>
            <p>- Se ha incluido al algoritmo de calculo del BIA la retención de logs y aparece en las vista de BIA.</p>
            <p>- Los riesgos ahora están agrupados en los mapas de calor por amenaza única en la vista historial del servicio/sistema.</p>
            <p>- Se ha corregido el cálculo de disponibilidad en el BIA que desbordaba y si daba un valor por encima de "muy alto" daba como resultado un "muy bajo".</p>
            <p>- Se ha solucionado un error que hacia que en algunos selectores saliesen activos que no debía.</p>
            <p>- Se ha corregido un error de cálculo en algunas gráficas del dashboard que daba como error un valor negativo.</p>
        </div>
        <div class="toast-body mshide mt-4">
            <div class="fecha mshide">05/11/2021</div>
            <p>- Se han añadido los gráficos de análisis de riesgo para evaluaciones que son 3PS.</p>
            <p>- Se han añadido los PAC de análisis de riesgo para evaluaciones que son 3PS.</p>
            <p>- Corregido el cálculo de riesgo actual cuando la evaluación es 3PS.</p>
            <p>- Se ha solucionado un bug que hacía que el mapa de calor se fuese estirando si se cargaba varias veces.</p>
            <p>- Se ha ajustado el calculo del valor promedio del mapa de calor de riesgo actual.</p>
            <p>- Se ha actualizado la BD con correcciones de preguntas,relaciones y otras modificaciones.</p>
        </div>
        <div class="toast-body mshide mt-4">
            <div class="fecha mshide">11/10/2021</div>
            <p>- Ya lo habrás notado, correcto ahora puedes loguearte en la herramienta con tu cuenta office365 corporativa (deshabilitado por el momento).</p>
            <p>- Ahora en la vista de riesgos del servicio podrás ver la media del riesgo actual a simple vista y sus porcentajes de los valores.</p>
            <p>- Nueva vista para reportar KPMS (deshabilitado).</p>
            <p>- Se ha corregido el cálculo integridad en el BIA que desbordaba y si daba un valor por encima de "muy alto" daba como resultado un "muy bajo".</p>
            <p>- Se ha solucionado un error que al editar el ECR de un sistema que no tenía evaluación te llevaba a una página incompleta.</p>
            <p>- Corregido un fallo al crear un plan de seguimiento en un sistema que no tuviese evaluación previa.</p>
            <p>- Se ha añadido y solucionado errores en la hoja de estilos principal.</p>
        </div>
        <div class="toast-body mshide mt-4">
            <div class="fecha mshide">14/09/2021</div>
            <p>- Ahora puedes exportar evaluaciones ya realizadas desde la vista "Historial del activo".</p>
            <p>- Se ha corregido un error que hacía que no pudieses editar evaluaciones.</p>
            <p>- Corregido un error que al marcar un activo como externo en algunos casos no se guardaba correctamente.</p>
            <p>- En la vista de servicios para diferenciar los externos se visualizará la barra de un tono azul.</p>
        </div>
        <div class="toast-body mshide mt-4">
            <div class="fecha mshide">10/08/2021</div>
            <p>- Ahora los servicios se pueden marcar como externos.</p>
            <p>- Se ha arreglado un error que hacía que al cambiar el selector de seguimiento de PAC no se actualizasen las fechas de la evaluación correspondientes.</p>
            <p>- Se ha mejorado el diseño de las notificaciones de actualizaciones.</p>
            <p>- Se ha corregido un error por el cual daba problemas al cargar una evaluación diferente a 3PS.</p>
            <p>- Se ha solucionado un fallo que hacia que no se pudiesen crear activos con sus relaciones en la herramienta correctamente.</p>
            <p>- Otras correcciones menores de código.</p>
        </div>
        <div class="toast-body mshide mt-4">
            <div class="fecha mshide">30/07/2021</div>
            <p>- Se ha corregido un fallo en Chrome por el cual el checkbox de archivado no se visualizaba correctamente.</p>
            <p>- Se ha corregido un fallo al importar algunos Excel de 3ps que daban error en la carga.</p>
            <p>- Se ha corregido un fallo al crear un nuevo activo dentro de una arquitectura de negocio que algunas veces creaba un bucle infinito.</p>
            <p>- Se han corregido algunos fallos de visualización, mensajes de error y código.</p>
        </div>
        <div class="toast-body mshide mt-4">
            <div class="fecha mshide">29/07/2021</div>
            <p>- Ahora tengo varias páginas para tener información sobre actualizaciones anteriores.</p>
            <p>- Se ha añadido 3ps para poder evaluarlo pudiendo importar un excel para el análisis.</p>
            <p>- Los servicios ahora se pueden archivar y dentro del selector en la vista de servicios podrás ver aquellos que tienes archivados.</p>
            <p>- Se han corregido pequeños errores para evitar fallos comunes en la BBDD.</p>
            <p>- Se han modificado algunos textos de la vista de histórico de evaluaciones.</p>
            <p>- Se han corregido varios errores de código.</p>
        </div>
        <div class="toast-body mshide mt-4">
            <div class="fecha mshide">17/07/2021</div>
            <p>- Soy nuevo por aquí y me encargaré de mantenerte actualizado con todos los cambios que se hagan :)</p>
            <p>- Nueva funcionalidad de seguimiento de PAC. Ahora podrás realizar seguimientos haciendo clic en el icono
                <img src="./img/history.svg" class="icono-16" alt="histórico"> del servicio.
                y luego en el icono azul <img src="./img/analitica.svg" class="icono-16" alt="update">
            </p>

            <p>- Se han corregido varios errores.</p>
        </div>
    </div>
    <?php getfooter() ?><div class="toast" data-bs-autohide="true" role="alert" aria-live="assertive" aria-atomic="true">
</body>

</html>
