<!DOCTYPE html>
<html lang="es">

<head>
    <title>Cuadro de mando</title>
    <?php getheader("Cuadro de mando", false) ?>
    <script src="https://www.gstatic.com/charts/loader.js" type="text/javascript"></script>
    <script src="./js/modules/dashboardModule.js" type="module" integrity="<?php echo "sha384-" . base64_encode(hash_file('sha384', "./js/modules/dashboardModule.js", true)) ?>" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="./css/styleLoading.css">
</head>

<body class="d-flex flex-column h-100">
    <?php getmenu() ?>
    <div class="container">
        <div class="row">
            <div class='col-12'>
                <ul class="nav nav-tabs">
                    <li class="nav-item">
                        <a class="eae nav-link active" data-bs-toggle="tab" href="#eae">EAE</a>
                    </li>
                    <li class="nav-item">
                        <a class="ecr nav-link" data-bs-toggle="tab" href="#ecr">ECR</a>
                    </li>
                    <li class="nav-item">
                        <a class="pac nav-link" data-bs-toggle="tab" href="#pac">PAC</a>
                    </li>
                    <li class="nav-item mshide">
                        <a class="kpms nav-link" data-bs-toggle="tab" href="#kpms">KPMs</a>
                    </li>
                    <li class="nav-item">
                        <a class="ps3 nav-link pointer" data-bs-toggle="tab" href="#ps3">3PS</a>
                    </li>
                    <li class="nav-item">
                        <a class="privacidad nav-link pointer" data-bs-toggle="tab" href="#privacidad">Privacidad</a>
                    </li>
                    <li class="nav-item">
                        <a class="continuidad nav-link pointer" data-bs-toggle="tab" href="#continuidad">Continuidad</a>
                    </li>
                    <li class="nav-item">
                        <a class="gbu nav-link pointer" data-bs-toggle="tab" href="#gbu">GBU</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link pointer" data-bs-toggle="tab" href="#eas">EAS</a>
                    </li>
                </ul>
            </div>
            <div class="tab-content">
                <div id="eae" class='tab-pane fade show active eae content'>
                    <small class="text-muted mt-4">Criticidad de productos</small>
                    <div class='graficaCriticidadProductos'></div>
                    <div class='tablaCriticidadProductos'>
                        <table id='criticidadProductos' class="table table-condensed table-hover table-striped table-11cert">
                            <caption>Criticidad máxima de los BIA por producto</caption>
                            <thead>
                                <tr>
                                    <th data-column-id="id" id="id-producto" data-identifier="true" data-visible="false">ID</th>
                                    <th data-column-id="producto" id="producto">PRODUCTO</th>
                                    <th data-column-id="servicios" id="servicios" data-visible="false">SERVICIOS</th>
                                    <th data-column-id="criticidad" id="criticidad">CRITICIDAD</th>
                                    <th data-column-id="fecha_bia" id="fecha_bia">FECHA BIA</th>
                                    <th data-column-id="confidencialidad" id="confidencialidad">CONFIDENCIALIDAD</th>
                                    <th data-column-id="integridad" id="integridad">INTEGRIDAD</th>
                                    <th data-column-id="disponibilidad" id="disponibilidad">DISPONIBILIDAD</th>
                                </tr>
                            </thead>
                            <tbody id='criticidadProductos-grid-data'>
                            </tbody>
                        </table>
                    </div>
                    <small class="text-muted">Servicios con BIA</small>
                    <div class='graficabia'>
                    </div>
                    <div class='tablaBialist'>
                        <table class="table table-condensed table-hover table-striped table-11cert" id='biaactivos'>
                            <caption>Listado de los activos</caption>
                            <thead>
                                <tr>
                                    <th data-column-id="id" data-identifier="true" data-searchable="true" id="bia-id">ID</th>
                                    <th data-column-id="nombre" id="nombre">NOMBRE</th>
                                    <th data-column-id="descripcion" id="descripcion">DESCRIPCIÓN</th>
                                    <th data-column-id="bia" id="bia">BIA</th>
                                    <th data-column-id="fechabia" data-type="date" id="fechabia">FECHA</th>
                                    <th data-column-id="archivado" id="archivado">ARCHIVADO</th>
                                    <th data-column-id="critico" id="critico">CRITICIDAD</th>
                                    <th data-column-id="expuesto" id="expuesto">EXPOSICION</th>
                                </tr>
                            </thead>
                            <tbody id='biaactivos-grid-data'>
                            </tbody>
                        </table>
                    </div>
                    <small class="text-muted">Tipos de activos</small>
                    <div class='graficaActivos'></div>
                    <div class='tablaActivoslist'>
                        <table id='tiposactivos' class="table table-condensed table-hover table-striped table-11cert">
                            <caption>Listado de tipo de activos</caption>
                            <thead>
                                <tr>
                                    <th data-column-id="id" data-identifier="true" data-searchable="true" id="id">ID</th>
                                    <th data-column-id="nombre" id="nombre">NOMBRE</th>
                                    <th data-column-id="descripcion" id="descripcion">DESCRIPCIÓN</th>
                                    <th data-column-id="tipo" id="tipo">TIPO</th>
                                    <th data-column-id="email" id="email">CREADO POR</th>
                                    <th data-column-id="archivado" id="archivado">ARCHIVADO</th>
                                </tr>
                            </thead>
                            <tbody id='tiposactivos-grid-data'>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div id="ecr" class='tab-pane fade show ecr content'>
                    <div class='tablaEcrAssets mb-5'>
                        <table id='ecractivos' class="table table-condensed table-hover table-striped table-11cert">
                            <caption>Listado de la fecha de evaluación de todos los activos no archivados.</caption>
                            <thead>
                                <tr>
                                    <th data-column-id="ID" data-searchable="true" data-visible="false" id="ID">ID</th>
                                    <th data-column-id="Nombre_Sistema" id="Nombre_Sistema">SISTEMA</th>
                                    <th data-column-id="Nombre_Servicio" id="Nombre_Sistema">SERVICIO</th>
                                    <th data-column-id="Fecha_Evaluacion" data-type="date" id="Fecha_Evaluacion">FECHA EVALUACIÓN</th>
                                </tr>
                            </thead>
                            <tbody id='ecrassets-grid-data'>
                            </tbody>
                        </table>
                    </div>
                    <div class='tablaEcrProductos mt-5'>
                        <small class="muted">Grafico de productos con y sin ECR</small>
                        <div class='graficaECRProductos'></div>
                        <table id='pruebasProductos' class="table table-condensed table-hover table-striped table-11cert">
                            <caption>Listado de productos con sus últimas fechas de evaluación.</caption>
                            <thead>
                                <tr>
                                    <th data-column-id="producto_id" id="producto_id" data-searchable="true" data-visible="false">ID PRODUCTO</th>
                                    <th data-column-id="nombre_producto" id="nombre_producto" data-visible='true'>NOMBRE PRODUCTO</th>
                                    <th data-column-id="servicio_id" id="servicio_id" data-visible='false'>ID SERVICIO</th>
                                    <th data-column-id="nombre_servicio" id="nombre_servicio" data-visible='false'>NOMBRE SERVICIO</th>
                                    <th data-column-id="activo_id" id="activo_id" data-visible='false'>ID ACTIVO</th>
                                    <th data-column-id="nombre_activo" id="nombre_activo" data-visible='true'>NOMBRE ACTIVO</th>
                                    <th data-column-id="fecha" id="fecha" data-type="date" data-visible='true'>FECHA EVALUACIÓN</th>
                                </tr>
                            </thead>
                            <tbody id='ecrproductos-grid-data'></tbody>
                        </table>
                    </div>
                </div>
                <div id="ers" class='tab-pane fade show ers content'>
                    <small class="text-muted">Sistemas con ERS</small>
                    <div class='graficaERS'>
                    </div>
                    <div class='tablaErslist'>
                        <table class="table table-condensed table-hover table-striped table-11cert" id='ersactivos'>
                            <caption>Listado de los activos</caption>
                            <thead>
                                <tr>
                                    <th data-column-id="id" id="id">ID</th>
                                    <th data-column-id="area" id="area">AREA</th>
                                    <th data-column-id="direccion" id="direccion">DIRECCION</th>
                                    <th data-column-id="servicio" id="servicio">SERVICIO</th>
                                    <th data-column-id="sistema" id="sistema">SISTEMA</th>
                                    <th data-column-id="fecha" id="fecha">FECHA</th>
                                    <th data-column-id="riesgo" id="riesgo">RIESGO</th>
                                </tr>
                            </thead>
                            <tbody id='ersactivos-grid-data'>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div id="pac" class='tab-pane fade show pac content'>
                    <small class="text-muted">Estado de PACs</small>
                    <div class='graficaPAC'>
                    </div>
                    <small class="text-muted">Nombre PACs creados</small>
                    <div class='graficaPACnombre'>
                    </div>
                    <div class='tablaPaclist'>
                        <table id="tablapac" class="table table-condensed table-hover table-striped table-11cert">
                            <caption>Listado PACs</caption>
                            <thead>
                                <th id='id' data-column-id="id" data-type="numeric" data-searchable="true" data-identifier="true" data-visible='false'>ID_PAC</th>
                                <th id='activo_id' data-column-id="activo_id" data-type="numeric" data-visible='false'>ACTIVO_ID</th>
                                <th id='proyecto_id' data-column-id="proyecto_id" data-type="numeric" data-visible='false'>PROYECTO_ID</th>
                                <th id='evaluacion_id' data-column-id="evaluacion_id" data-visible='false'>EVALUACION_ID</th>
                                <th id='servicio' data-column-id="servicio">SERVICIO</th>
                                <th id='sistema' data-column-id="sistema">SISTEMA</th>
                                <th id='nombrepac' data-column-id="nombrepac">PROYECTO</th>
                                <th id='responsable' data-column-id="responsable" data-visible='false'>RESPONSABLE</th>
                                <th id='estado' data-column-id="estado" data-visible='true'>ESTADO</th>
                                <th id='inicio' data-column-id="inicio" data-type="date" data-visible='true'>INICIO</th>
                                <th id='fin' data-column-id="fin" data-type="date" data-visible='true'>FIN</th>
                                <th id='creado' data-column-id="creado" data-type="date" data-visible='false'>CREADO</th>
                                <th id='comentarios' data-column-id="comentarios" data-visible='false'>COMENTARIOS</th>
                                <th id='adjuntos' data-column-id="adjuntos" data-visible='false'>ADJUNTOS</th>
                            </thead>
                            <tbody id='tablapac-grid-data'>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div id="kpms" class='tab-pane fade show kpms content'>
                    <div class="text-right">
                        <button type="button" class="btn btn-xs btn-primary mt-3 mb-2 obtainMetricas float-right">Obtener métricas</button>
                    </div>
                    <small class="text-muted">Áreas</small>
                    <div class='tablaAreas'>
                        <table class="table table-condensed table-hover table-striped table-11cert" id='Areas'>
                            <caption>Tabla de áreas en 11Cert</caption>
                            <thead>
                                <tr>
                                    <th data-column-id="seleccionar" id="seleccionar"><input type="checkbox" id="seleccionar-checkbox"></th>
                                    <th data-column-id="id" id="id">ID</th>
                                    <th data-column-id="nombre" id="nombre">NOMBRE</th>
                                </tr>
                            </thead>
                            <tbody id='areas-grid-data'>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div id="ps3" class='tab-pane fade show ps3 content'>
                    <div class="row PS3Row justify-content-end">
                        <div class="col-md-6 d-flex align-items-center">
                            <h3 class="minititle">Sistemas Evaluados 3PS</h3>
                        </div>
                        <div class="col-md-6 loading3PS d-flex justify-content-end mb-2 align-items-center">
                            <div class="spinner-animation" id="loading3PS">
                                <svg class="spinner-a" height="60" viewBox="0 0 66 66" width="60">
                                    <circle class="spinner-circle" cx="33" cy="33" fill="none" r="30" stroke-width="3" stroke="#0d6efd"></circle>
                                </svg>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <table class="table table-condensed table-hover table-striped table-11cert" id='PS3Tabla'>
                                <caption>Tabla Sistemas Evaluados 3PS</caption>
                                <thead>
                                    <tr>
                                        <th data-column-id="Producto" data-header-css-class="ProductoCol" id="Producto">PRODUCTO</th>
                                        <th data-column-id="Sistema" data-header-css-class="SistemaCol" id="Sistema">SISTEMA</th>
                                        <th data-column-id="FechaEvaluacion" data-header-css-class="fechaEvaluacionCol" id="fechaEvaluacion">FECHA EVALUACIÓN</th>
                                    </tr>
                                </thead>
                                <tbody id='PS3Total'>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <hr>
                    <div class="row PS3Row justify-content-end">
                        <div class="col-md-6 d-flex align-items-center">
                            <h3 class="minititle">Productos Externalizados con 3PS en alguno de sus Sistemas</h3>
                        </div>
                        <div class="col-md-6 loading3PSBia d-flex justify-content-end align-items-center">
                            <div class="spinner-animation position-relative" id="loadingSisIngresos">
                                <svg class="spinner-a" height="60" viewBox="0 0 66 66" width="60">
                                    <circle class="spinner-circle" cx="33" cy="33" fill="none" r="30" stroke-width="3" stroke="#0d6efd"></circle>
                                </svg>
                                <div class="position-absolute top-50 start-50 translate-middle">
                                    <span class="porcentajeIngresos porcentaje" id="porcentaje">0%</span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="graficaIngresos">
                            </div>
                        </div>
                        <div class="col-md-12">
                            <table class="table table-condensed table-hover table-striped table-11cert" id='SisIngresosTabla'>
                                <caption>Productos Externalizados</caption>
                                <thead>
                                    <tr>
                                        <th data-column-id="Direccion" data-header-css-class="DireccionCol" data-visible='false' id="Direccion">DIRECCIÓN</th>
                                        <th data-column-id="Area" data-header-css-class="AreaCol" data-visible='false' id="Area">ÁREA</th>
                                        <th data-column-id="Producto" data-header-css-class="ProductoCol" id="Producto">PRODUCTO</th>
                                        <th data-column-id="Servicio" data-header-css-class="servicioCol" data-visible='false' id="Servicio">SERVICIO</th>
                                        <th data-column-id="Eval3PS" data-header-css-class="Eval3PSCol" id="Eval3PS">EVALUACIÓN 3PS</th>
                                        <th data-column-id="EvalNorm" data-header-css-class="EvalNormCol" id="EvalNorm">EVALUACIÓN NORMATIVA</th>
                                    </tr>
                                </thead>
                                <tbody id='PS3Total'>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div id="privacidad" class='tab-pane fade show privacidad content'>
                    <div class="row PS3RowBia justify-content-end mt-3">
                        <div class="col-md-6 d-flex align-items-end">
                            <h3 class="minititle">Configuración productos con tratamiento de datos personales</h3>
                        </div>
                        <div class="col-md-6 loading3PSBia d-flex justify-content-end align-items-center">
                            <div class="spinner-animation position-relative" id="loadingConf">
                                <svg class="spinner-a" height="60" viewBox="0 0 66 66" width="60">
                                    <circle class="spinner-circle" cx="33" cy="33" fill="none" r="30" stroke-width="3" stroke="#0d6efd"></circle>
                                </svg>
                                <div class="position-absolute top-50 start-50 translate-middle">
                                    <span class="porcentajePrivacidad porcentaje" id="porcentaje">0%</span>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-12">
                            <div class="graficaPrivacidadProductos">
                            </div>
                        </div>
                        <div class="col-md-12">
                            <table class="table table-condensed table-hover table-striped table-11cert" id='tablaConfProductos'>
                                <caption>Si alguno de sus sistemas tiene configuración se marca como que el producto entero tiene configuración.</caption>
                                <thead>
                                    <tr>
                                        <th data-column-id="Producto" data-header-css-class="productoCol" id="Producto">PRODUCTO</th>
                                        <th data-column-id="TieneBia" data-header-css-class="TieneBiaCol" id="TieneBia">TIENE BIA</th>
                                        <th data-column-id="TieneAct" data-header-css-class="TieneActCol" id="TieneAct">TIENE ACTIVO</th>
                                    </tr>
                                </thead>
                                <tbody id='PS3BiaTotal'>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <hr>
                    <div class="row PS3RowBia justify-content-end mt-3">
                        <div class="col-md-6 d-flex align-items-end">
                            <h3 class="minititle">Configuración sistemas con tratamiento de datos personales</h3>
                        </div>
                        <div class="col-md-6 loading3PSBia d-flex justify-content-end align-items-center">
                            <div class="spinner-animation position-relative" id="loadingConfProductos">
                                <svg class="spinner-a" height="60" viewBox="0 0 66 66" width="60">
                                    <circle class="spinner-circle" cx="33" cy="33" fill="none" r="30" stroke-width="3" stroke="#0d6efd"></circle>
                                </svg>
                                <div class="position-absolute top-50 start-50 translate-middle">
                                    <span class="porcentajePrivacidad porcentaje" id="porcentaje">0%</span>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-12">
                            <div class="graficaPrivacidad">
                            </div>
                        </div>
                        <div class="col-md-12">
                            <table class="table table-condensed table-hover table-striped table-11cert" id='tablaConf'>
                                <caption>Configuración sistemas con tratamiento de datos personales</caption>
                                <thead>
                                    <tr>
                                        <th data-column-id="Producto" data-header-css-class="productoCol" id="Producto">PRODUCTO</th>
                                        <th data-column-id="Sistema" data-header-css-class="SistemaCol" id="Sistema">SISTEMA</th>
                                        <th data-column-id="TieneBia" data-header-css-class="TieneBiaCol" id="TieneBia">TIENE BIA</th>
                                        <th data-column-id="TieneAct" data-header-css-class="TieneActCol" id="TieneAct">TIENE ACTIVO</th>
                                        <th data-column-id="TipoConfig" data-header-css-class="TipoConfigCol" id="TipoConfig">TIPO CONFIGURACIÓN</th>
                                    </tr>
                                </thead>
                                <tbody id='PS3BiaTotal'>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <hr>
                </div>
                <div id="continuidad" class='tab-pane fade show continuidad content'>
                    <?php insertLoadingDinamic('Productos y su plan de continuidad', 'continuidadLoading') ?>
                    <div class="col-md-12">
                        <div class="graficaContinuidad">
                        </div>
                    </div>
                    <div class="col-md-12">
                        <table class="table table-condensed table-hover table-striped table-11cert mshide" id='productosTotalesContinuidad'>
                            <caption>Productos plan de continuidad estado finalizado</caption>
                            <thead>
                                <tr>
                                    <th data-column-id="Producto" data-header-css-class="productoCol" id="Producto">Producto</th>
                                    <th data-column-id="PlanContinuidad" data-header-css-class="planContinuidadCol" id="planContinuidad">Plan de continuidad finalizado</th>
                                </tr>
                            </thead>
                            <tbody id='productosTotalesContinuidadBody'>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div id="gbu" class='tab-pane fade show gbu content'>
                    <div class="col-md-12">
                        <div class="grafica-gbu">
                        </div>
                    </div>
                </div>
                <div id="eas" class='tab-pane fade show eas content'>
                    <?php insertLoadingDinamic('Relaciones de las suscripciones', 'easLoading') ?>
                    <div class="tablaEas col-md-12">
                        <table class="table table-condensed table-hover table-striped table-11cert" id='easTable'>
                            <caption>Relaciones de las suscripciones</caption>
                            <thead>
                                <tr>
                                    <th data-column-id="id" data-header-css-class="idCol" data-visible="false" data-identifier="true" id="id">ID</th>
                                    <th data-column-id="Padre" data-header-css-class="padreCol" id="Producto">Producto</th>
                                    <th data-column-id="Activo" data-header-css-class="activoCol" id="Activo">Servicio</th>
                                    <th data-column-id="Suscripcion" data-header-css-class="suscripcionCol" id="Suscripcion">Nombre suscripción</th>
                                    <th data-column-id="idSuscripcion" data-header-css-class="idSuscripcionCol" id="idSuscripcion">ID suscripción</th>
                                    <th data-column-id="commands" data-header-css-class="col-commands" data-formatter="commands" data-sortable="false">Acciones</th>
                                </tr>
                            </thead>
                            <tbody id='easTableBody'>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php getfooter() ?>
</body>

</html>
