<div style="font-family: Arial, sans-serif; color: #333; margin: 0; padding: 0">
  <table style="border-collapse: collapse; margin-bottom: 10px">
    <tr>
      <th
        style="
          width: 100%;
          padding: 0;
          vertical-align: middle;
          text-align: right;
        ">
        <strong style="font-size: 12pt; color: #031a34">Open Security Architecture (OSA)</strong>
      </th>
    </tr>
  </table>

  <table style="border-collapse: collapse; margin-bottom: 20px">
    <thead>
      <tr>
        <th
          style="
            background-color: #031a34;
            padding: 15px;
            color: #ffffff;
            text-align: left;
          "
          scope="col">
          <p style="margin: 0 0 8px; font-size: 18pt; line-height: 1">
            <strong>Resultados del análisis de arquitectura</strong>
          </p>
          <p style="margin: 0; font-size: 12pt; line-height: 1.4">
            <strong>Nombre revisión:</strong> {service_name}<br />
            <strong>Fecha:</strong> {fecha_final}<br />
            <strong>Arquitecto:</strong> {arquitecto}
          </p>
        </th>
      </tr>
    </thead>
  </table>

  <div style="padding: 0 15px">
    <h2 style="font-size: 14pt; color: #595959; margin: 0 0 8px">
      Metodología y alcance
    </h2>
    <p
      style="
        margin: 0 0 12px;
        font-size: 11pt;
        line-height: 1.4;
        text-align: justify;
      ">
      El catálogo de control de OSA se basa actualmente en la norma NIST 800-53.
      Al utilizar un único catálogo de controles, permitimos establecer
      claramente cómo cumplir con los objetivos de múltiples estándares, y dar
      unos principios de diseño de seguridad que sustentan esta revisión.
    </p>
    <p
      style="
        margin-top: 0pt;
        margin-left: 36pt;
        margin-bottom: 8pt;
        text-indent: -36pt;
      ">
      Los principales objetivos por alcanzar son:
    </p>
    <ul style="margin: 0pt; padding-left: 0pt">
      <li
        style="
          margin-left: 28.06pt;
          text-align: justify;
          line-height: normal;
          padding-left: 7.94pt;
          font-family: serif;
        ">
        <strong><span style="font-family: Calibri">Evaluar la</span></strong><span style="font-family: Calibri">&nbsp;</span><strong><span style="font-family: Calibri">Arquitectura de Seguridad (SA)</span></strong><span style="font-family: Calibri">&nbsp;del Servicio y de los Sistemas de Informaci&oacute;n que lo
          soportan.</span>
      </li>
      <li
        style="
          margin-left: 28.06pt;
          text-align: justify;
          line-height: normal;
          padding-left: 7.94pt;
          font-family: serif;
        ">
        <strong><span style="font-family: Calibri">Diagnosticar su nivel de adecuaci&oacute;n</span></strong><span style="font-family: Calibri">&nbsp;respecto de los requisitos aplicables y mejores
          pr&aacute;cticas existentes.</span>
      </li>
      <li
        style="
          margin-left: 28.06pt;
          text-align: justify;
          line-height: normal;
          padding-left: 7.94pt;
          font-family: serif;
        ">
        <strong><span style="font-family: Calibri">Identificar posibles puntos de mejora y Debilidades</span></strong><span style="font-family: Calibri">&nbsp;asociadas a la Arquitectura de Seguridad (SA Weaknesses).</span><span style="font-family: Calibri">&nbsp;&nbsp;</span>
      </li>
    </ul>
    <p style="margin-top: 0pt; margin-bottom: 8pt; background-color: #ffffff">
      &nbsp;
    </p>
    <p
      style="
        margin-top: 0pt;
        margin-bottom: 0pt;
        text-align: justify;
        line-height: normal;
      ">
      En el alcance de las pruebas se identifican los siguientes activos:
    </p>
    <p
      style="
        margin-top: 0pt;
        margin-bottom: 0pt;
        text-align: justify;
        line-height: normal;
      ">
      &nbsp;
    </p>
    <table
      style="
        width: 106.82%;
        border: 1pt solid #0066ff;
        border-collapse: collapse;
      ">
      <thead>
        <tr>
          <th
            scope="col"
            style="
              width: 53.1%;
              border-right: 1pt solid #0066ff;
              border-bottom: 1pt solid #0066ff;
              padding: 4.25pt 4.9pt;
              vertical-align: top;
              background-color: #0066ff;
            ">
            <p
              style="
                margin-top: 0pt;
                margin-bottom: 0pt;
                text-align: justify;
                font-size: 11pt;
              ">
              <strong>Activo</strong>
            </p>
          </th>
          <th
            scope="col"
            style="
              width: 53.1%;
              border-right: 1pt solid #0066ff;
              border-bottom: 1pt solid #0066ff;
              padding: 4.25pt 4.9pt;
              vertical-align: top;
              background-color: #0066ff;
            ">
            <p
              style="
                margin-top: 0pt;
                margin-bottom: 0pt;
                text-align: justify;
                font-size: 11pt;
              ">
              <strong>ID Suscripción</strong>
            </p>
          </th>
          <th
            scope="col"
            style="
              width: 20.3%;
              border-right: 1pt solid #0066ff;
              border-bottom: 1pt solid #0066ff;
              padding: 4.25pt 4.9pt 4.25pt 5.4pt;
              vertical-align: top;
              background-color: #0066ff;
            ">
            <p
              style="
                margin-top: 0pt;
                margin-bottom: 0pt;
                text-align: justify;
                font-size: 11pt;
              ">
              <strong>Tipo</strong>
            </p>
          </th>
          <th
            scope="col"
            style="
              width: 26.6%;
              border-bottom: 1pt solid #0066ff;
              padding: 4.25pt 4.9pt 4.25pt 5.4pt;
              vertical-align: top;
              background-color: #0066ff;
            ">
            <p
              style="
                margin-top: 0pt;
                margin-bottom: 0pt;
                text-align: justify;
                font-size: 11pt;
              ">
              <strong>Tipo de prueba</strong>
            </p>
          </th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td
            style="
              width: 53.1%;
              border-right: 1pt solid #0066ff;
              padding: 4.25pt 4.9pt;
              vertical-align: top;
            ">
            <p
              style="
                margin-top: 0pt;
                margin-bottom: 0pt;
                text-align: justify;
                font-size: 11pt;
              ">
              {suscription_name}
            </p>
          </td>
          <td
            style="
              width: 53.1%;
              border-right: 1pt solid #0066ff;
              padding: 4.25pt 4.9pt;
              vertical-align: top;
            ">
            <p
              style="
                margin-top: 0pt;
                margin-bottom: 0pt;
                text-align: justify;
                font-size: 11pt;
              ">
              {cloudId}
            </p>
          </td>
          <td
            style="
              width: 20.3%;
              border-right: 1pt solid #0066ff;
              padding: 4.25pt 4.9pt 4.25pt 5.4pt;
              vertical-align: top;
            ">
            <p
              style="
                margin-top: 0pt;
                margin-bottom: 0pt;
                text-align: justify;
                font-size: 11pt;
              ">
              <em>Suscripci&oacute;n</em>
            </p>
          </td>
          <td
            style="
              width: 26.6%;
              padding: 4.25pt 4.9pt 4.25pt 5.4pt;
              vertical-align: top;
            ">
            <p
              style="
                margin-top: 0pt;
                margin-bottom: 0pt;
                text-align: justify;
                font-size: 11pt;
              ">
              <em>Bastionado</em>
            </p>
            <p
              style="
                margin-top: 0pt;
                margin-bottom: 0pt;
                text-align: justify;
                font-size: 11pt;
              ">
              <em>An&aacute;lisis vulnerabilidades</em>
            </p>
            <p
              style="
                margin-top: 0pt;
                margin-bottom: 0pt;
                text-align: justify;
                font-size: 11pt;
              ">
              &nbsp;
            </p>
          </td>
        </tr>
      </tbody>
    </table>
    <p
      style="
        margin-top: 0pt;
        margin-bottom: 0pt;
        text-align: justify;
        line-height: normal;
      ">
      &nbsp;
    </p>
    <p
      style="
        margin-top: 0pt;
        margin-bottom: 8pt;
        text-align: center;
        line-height: 108%;
        font-size: 14pt;
      ">
      <span style="letter-spacing: 0.75pt; color: #595959">● ● ●</span>
    </p>
    <p
      style="
        margin-top: 0pt;
        margin-bottom: 8pt;
        line-height: 108%;
        font-size: 14pt;
      ">
      <span style="letter-spacing: 0.75pt; color: #595959">&nbsp;</span><span style="letter-spacing: 0.75pt; color: #595959">&nbsp;</span>
    </p>
    <table
      style="width: 100%; border: 1pt solid #ffffff; border-collapse: collapse">
      <thead>
        <tr>
          <th
            scope="col"
            style="
              width: 48.34%;
              text-align: left;
              padding: 4pt;
              color: #595959;
              font-size: 11pt;
            "></th>
          <th
            scope="col"
            style="
              width: 51.66%;
              text-align: right;
              padding: 4pt;
              color: #595959;
              font-size: 11pt;
            "></th>
        </tr>
      </thead>
      <tbody>
        <tr style="height: 47.45pt">
          <td
            style="
              width: 48.34%;
              border-right: 1pt solid #ffffff;
              vertical-align: top;
            ">
            <p
              style="
                margin-top: 0pt;
                margin-bottom: 8pt;
                line-height: 108%;
                font-size: 14pt;
              ">
              <strong><span style="letter-spacing: 0.75pt; color: #595959">Resumen</span></strong><span style="letter-spacing: 0.75pt; color: #595959">&nbsp;</span>
            </p>
            <p
              style="
                margin-top: 0pt;
                margin-bottom: 8pt;
                line-height: 108%;
                font-size: 14pt;
              ">
              <strong><span style="letter-spacing: 0.75pt; color: #595959">{n} vulnerabilidades</span></strong><span style="letter-spacing: 0.75pt; color: #595959">&nbsp;</span>
            </p>
          </td>
          <td style="width: 51.66%; vertical-align: top">
            <div style="text-align: right">
              <table
                style="margin-left: auto; border-spacing: 5.6pt; width: 100%">
                <thead>
                  <tr>
                    <th
                      scope="col"
                      style="width: 41.9pt; text-align: center; font-size: 9pt">
                      Crítica
                    </th>
                    <th
                      scope="col"
                      style="width: 44.6pt; text-align: center; font-size: 9pt">
                      Alta
                    </th>
                    <th
                      scope="col"
                      style="width: 44.8pt; text-align: center; font-size: 9pt">
                      Media
                    </th>
                    <th
                      scope="col"
                      style="
                        width: 41.75pt;
                        text-align: center;
                        font-size: 9pt;
                      ">
                      Baja
                    </th>
                  </tr>
                </thead>
                <tbody>
                  <tr style="height: 37.45pt">
                    <td
                      style="
                        width: 41.9pt;
                        vertical-align: middle;
                        background-color: #db0009;
                      ">
                      <p
                        style="
                          margin-top: 0pt;
                          margin-bottom: 0pt;
                          text-align: center;
                          font-size: 11pt;
                        ">
                        <span style="color: #ffffff">{n_crit}</span>
                      </p>
                      <p
                        style="
                          margin-top: 0pt;
                          margin-bottom: 0pt;
                          text-align: center;
                          font-size: 9pt;
                        ">
                        <span style="color: #ffffff">Cr&iacute;tica</span>
                      </p>
                    </td>
                    <td
                      style="
                        width: 44.6pt;
                        vertical-align: middle;
                        background-color: #fd8b1a;
                      ">
                      <p
                        style="
                          margin-top: 0pt;
                          margin-bottom: 0pt;
                          text-align: center;
                          font-size: 11pt;
                        ">
                        <span style="color: #ffffff">{n_high}</span>
                      </p>
                      <p
                        style="
                          margin-top: 0pt;
                          margin-bottom: 0pt;
                          text-align: center;
                          font-size: 9pt;
                        ">
                        <span style="color: #ffffff">Alta</span>
                      </p>
                    </td>
                    <td
                      style="
                        width: 44.8pt;
                        vertical-align: middle;
                        background-color: #ffbb1c;
                      ">
                      <p
                        style="
                          margin-top: 0pt;
                          margin-bottom: 0pt;
                          text-align: center;
                          font-size: 11pt;
                        ">
                        <span style="color: #ffffff">{n_mid}</span>
                      </p>
                      <p
                        style="
                          margin-top: 0pt;
                          margin-bottom: 0pt;
                          text-align: center;
                          font-size: 9pt;
                        ">
                        <span style="color: #ffffff">Media</span>
                      </p>
                    </td>
                    <td
                      style="
                        width: 41.75pt;
                        vertical-align: middle;
                        background-color: #1184d0;
                      ">
                      <p
                        style="
                          margin-top: 0pt;
                          margin-bottom: 0pt;
                          text-align: center;
                          font-size: 11pt;
                        ">
                        <span style="color: #ffffff">{n_low}</span>
                      </p>
                      <p
                        style="
                          margin-top: 0pt;
                          margin-bottom: 0pt;
                          text-align: center;
                          font-size: 9pt;
                        ">
                        <span style="color: #ffffff">Baja</span>
                      </p>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
            <p
              style="
                margin-top: 0pt;
                margin-bottom: 8pt;
                line-height: 108%;
                font-size: 14pt;
              ">
              <br />
            </p>
          </td>
        </tr>
      </tbody>
    </table>
    <p
      style="
        margin-top: 0pt;
        margin-bottom: 8pt;
        line-height: 108%;
        font-size: 14pt;
      ">
      <span style="letter-spacing: 0.75pt; color: #595959">&nbsp;</span>
    </p>
    <p style="margin-top: 0pt; margin-bottom: 8pt">&nbsp;</p>
    <p style="margin-top: 0pt; margin-bottom: 8pt">
      <strong>Se han identificado las siguientes vulnerabilidades, clasificadas en
        {n} niveles de seguridad:</strong>
    </p>
    <p style="margin-top: 0pt; margin-bottom: 8pt"><strong>&nbsp;</strong></p>
    <!-- block_critic_start -->
    <table style="width: 100%; border-collapse: collapse">
      <thead>
        <tr>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td
            style="
              width: 8.34%;
              border-top: 1pt solid #0066ff;
              padding: 11.35pt 5.4pt;
              vertical-align: top;
            ">
            <div style="text-align: center">
              <table
                style="
                  width: 57.8pt;
                  margin-right: auto;
                  margin-left: auto;
                  border-collapse: collapse;
                ">
                <thead>
                  <tr>
                    <th
                      scope="col"
                      style="font-size: 9pt; text-align: center"></th>
                  </tr>
                </thead>
                <tbody>
                  <tr style="height: 22.5pt">
                    <td
                      style="
                        width: 47pt;
                        padding-right: 5.4pt;
                        padding-left: 5.4pt;
                        vertical-align: middle;
                        background-color: #db0009;
                      ">
                      <p
                        style="
                          margin-top: 0pt;
                          margin-bottom: 8pt;
                          text-align: center;
                          line-height: 108%;
                          font-size: 11pt;
                        ">
                        {critic}
                      </p>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </td>
          <td
            style="
              width: 91.66%;
              border-top: 1pt solid #0066ff;
              padding: 11.35pt 5.4pt;
              vertical-align: top;
            ">
            <p
              style="
                margin-top: 0pt;
                margin-bottom: 8pt;
                line-height: 108%;
                font-size: 11pt;
              ">
              <strong>{critic_nombre_vuln} / {critic_issue}</strong>
            </p>
            <p
              style="
                margin-top: 0pt;
                margin-left: 36pt;
                margin-bottom: 8pt;
                text-indent: -36pt;
                line-height: 108%;
                font-size: 11pt;
              ">
              {critic_descripcion}
            </p>
          </td>
        </tr>
      </tbody>
    </table>
    <!-- block_critic_end -->

    <!-- block_high_start -->
    <table style="width: 100%; border-collapse: collapse">
      <thead>
        <tr>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td
            style="
              width: 8.34%;
              border-top: 1pt solid #0066ff;
              padding: 11.35pt 5.4pt;
              vertical-align: top;
            ">
            <div style="text-align: center">
              <table
                style="
                  width: 57.8pt;
                  margin-right: auto;
                  margin-left: auto;
                  border-collapse: collapse;
                ">
                <thead>
                  <tr>
                    <th
                      scope="col"
                      style="font-size: 9pt; text-align: center"></th>
                  </tr>
                </thead>
                <tbody>
                  <tr style="height: 22.5pt">
                    <td
                      style="
                        width: 47pt;
                        padding-right: 5.4pt;
                        padding-left: 5.4pt;
                        vertical-align: middle;
                        background-color: #fd8b1a;
                      ">
                      <p
                        style="
                          margin-top: 0pt;
                          margin-bottom: 8pt;
                          text-align: center;
                          line-height: 108%;
                          font-size: 11pt;
                        ">
                        {high}
                      </p>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </td>
          <td
            style="
              width: 91.66%;
              border-top: 1pt solid #0066ff;
              padding: 11.35pt 5.4pt;
              vertical-align: top;
            ">
            <p
              style="
                margin-top: 0pt;
                margin-bottom: 8pt;
                line-height: 108%;
                font-size: 11pt;
              ">
              <strong>{high_nombre_vuln} / {high_issue}</strong>
            </p>
            <p
              style="
                margin-top: 0pt;
                margin-left: 36pt;
                margin-bottom: 8pt;
                text-indent: -36pt;
                line-height: 108%;
                font-size: 11pt;
              ">
              {high_descripcion}
            </p>
          </td>
        </tr>
      </tbody>
    </table>
    <!-- block_high_end -->

    <!-- block_mid_start -->
    <table style="width: 100%; border-collapse: collapse">
      <thead>
        <tr>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td
            style="
              width: 8.34%;
              border-top: 1pt solid #0066ff;
              padding: 11.35pt 5.4pt;
              vertical-align: top;
            ">
            <div style="text-align: center">
              <table
                style="
                  width: 57.8pt;
                  margin-right: auto;
                  margin-left: auto;
                  border-collapse: collapse;
                ">
                <thead>
                  <tr>
                    <th
                      scope="col"
                      style="font-size: 9pt; text-align: center"></th>
                  </tr>
                </thead>
                <tbody>
                  <tr style="height: 22.5pt">
                    <td
                      style="
                        width: 47pt;
                        padding-right: 5.4pt;
                        padding-left: 5.4pt;
                        vertical-align: middle;
                        background-color: #ffbb1c;
                      ">
                      <p
                        style="
                          margin-top: 0pt;
                          margin-bottom: 8pt;
                          text-align: center;
                          line-height: 108%;
                          font-size: 11pt;
                        ">
                        {mid}
                      </p>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </td>
          <td
            style="
              width: 91.66%;
              border-top: 1pt solid #0066ff;
              padding: 11.35pt 5.4pt;
              vertical-align: top;
            ">
            <p
              style="
                margin-top: 0pt;
                margin-bottom: 8pt;
                line-height: 108%;
                font-size: 11pt;
              ">
              <strong>{mid_nombre_vuln} / {mid_issue}</strong>
            </p>
            <p
              style="
                margin-top: 0pt;
                margin-left: 36pt;
                margin-bottom: 8pt;
                text-indent: -36pt;
                line-height: 108%;
                font-size: 11pt;
              ">
              {mid_descripcion}
            </p>
          </td>
        </tr>
      </tbody>
    </table>
    <!-- block_mid_end -->

    <!-- block_low_start -->
    <table style="width: 100%; border-collapse: collapse">
      <thead>
        <tr>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td
            style="
              width: 8.34%;
              border-top: 1pt solid #0066ff;
              border-bottom: 1pt solid #0066ff;
              padding: 11.35pt 5.4pt;
              vertical-align: top;
            ">
            <div style="text-align: center">
              <table
                style="
                  width: 57.8pt;
                  margin-right: auto;
                  margin-left: auto;
                  border-collapse: collapse;
                ">
                <thead>
                  <tr>
                    <th
                      scope="col"
                      style="font-size: 9pt; text-align: center"></th>
                  </tr>
                </thead>
                <tbody>
                  <tr style="height: 22.5pt">
                    <td
                      style="
                        width: 47pt;
                        padding-right: 5.4pt;
                        padding-left: 5.4pt;
                        vertical-align: middle;
                        background-color: #1184d0;
                      ">
                      <p
                        style="
                          margin-top: 0pt;
                          margin-bottom: 8pt;
                          text-align: center;
                          line-height: 108%;
                          font-size: 11pt;
                        ">
                        {low}
                      </p>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </td>
          <td
            style="
              width: 91.66%;
              border-top: 1pt solid #0066ff;
              border-bottom: 1pt solid #0066ff;
              padding: 11.35pt 5.4pt;
              vertical-align: top;
            ">
            <p
              style="
                margin-top: 0pt;
                margin-bottom: 8pt;
                line-height: 108%;
                font-size: 11pt;
              ">
              <strong>{low_nombre_vuln} / {low_issue}</strong>
            </p>
            <p
              style="
                margin-top: 0pt;
                margin-left: 36pt;
                margin-bottom: 8pt;
                text-indent: -36pt;
                line-height: 108%;
                font-size: 11pt;
              ">
              {low_descripcion}
            </p>
          </td>
        </tr>
      </tbody>
    </table>
    <!-- block_low_end -->

    <p style="margin-top: 0pt; margin-bottom: 8pt">&nbsp;</p>
    <p
      style="
        margin-top: 0pt;
        margin-bottom: 8pt;
        line-height: 108%;
        font-size: 14pt;
      ">
      <span style="letter-spacing: 0.75pt; color: #595959">Observaciones</span>
    </p>
    <p style="margin-top: 0pt; margin-bottom: 8pt">{observaciones}</p>
    <p
      style="
        margin-top: 0pt;
        margin-bottom: 8pt;
        text-align: center;
        line-height: 108%;
        font-size: 14pt;
      ">
      <span style="letter-spacing: 0.75pt; color: #595959">● ● ●</span>
    </p>
    <p
      style="
        margin-top: 0pt;
        margin-bottom: 8pt;
        line-height: 108%;
        font-size: 14pt;
      ">
      <span style="letter-spacing: 0.75pt; color: #595959">Monitorizaci&oacute;n y resoluci&oacute;n de vulnerabilidades</span>
    </p>
    <p style="margin-top: 0pt; margin-bottom: 8pt">
      Desde la Direcci&oacute;n CISO de CDO, junto al propietario del activo y/o
      su contacto t&eacute;cnico, se definen las acciones a llevar a cabo para
      la resoluci&oacute;n total de la vulnerabilidad o la aplicaci&oacute;n de
      controles de seguridad complementarios y/o compensatorios. En cualquiera
      de los casos, a continuaci&oacute;n, se definen los plazos aplicables:
    </p>
    <div style="text-align: center">
      <table
        style="
          margin-right: auto;
          margin-left: auto;
          border: 1pt solid rgb(0, 102, 255);
          border-collapse: collapse;
          width: 100%;
        ">
        <thead>
          <tr style="height: 33.05pt">
            <th
              style="
                width: 81.1pt;
                border-right: 1pt solid #0066ff;
                border-bottom: 1pt solid #0066ff;
                padding-right: 4.9pt;
                padding-left: 4.9pt;
                vertical-align: middle;
                background-color: #0066ff;
              ">
              <p
                style="
                  margin-top: 0pt;
                  margin-bottom: 8pt;
                  line-height: 108%;
                  font-size: 11pt;
                ">
                <strong>Criticidad</strong>
              </p>
            </th>
            <th
              style="
                width: 120.3pt;
                border-right: 1pt solid #0066ff;
                border-bottom: 1pt solid #0066ff;
                padding-right: 4.9pt;
                padding-left: 5.4pt;
                vertical-align: middle;
                background-color: #0066ff;
              ">
              <p
                style="
                  margin-top: 0pt;
                  margin-bottom: 8pt;
                  line-height: 108%;
                  font-size: 11pt;
                ">
                <strong>Tiempo objetivo para activos cr&iacute;ticos</strong>
              </p>
            </th>
            <th
              style="
                width: 120.35pt;
                border-bottom: 1pt solid #0066ff;
                padding-right: 4.9pt;
                padding-left: 5.4pt;
                vertical-align: middle;
                background-color: #0066ff;
              ">
              <p
                style="
                    margin-top: 0pt;
                    margin-bottom: 8pt;
                    line-height: 108%;
                    font-size: 11pt;
                  ">
                <strong>Tiempo objetivo para activos no cr&iacute;ticos</strong>
              </p>
            </th>
          </tr>
        </thead>
        <tr style="height: 28.4pt">
          <td
            style="
                width: 81.1pt;
                border-right: 1pt solid #0066ff;
                border-bottom: 1pt solid #0066ff;
                padding-right: 4.9pt;
                padding-left: 4.9pt;
                vertical-align: middle;
              ">
            <p
              style="
                  margin-top: 0pt;
                  margin-bottom: 8pt;
                  line-height: 108%;
                  font-size: 11pt;
                ">
              <strong>Cr&iacute;tica</strong>
            </p>
          </td>
          <td
            style="
                width: 120.3pt;
                border-right: 1pt solid #0066ff;
                border-bottom: 1pt solid #0066ff;
                padding-right: 4.9pt;
                padding-left: 5.4pt;
                vertical-align: middle;
              ">
            <p
              style="
                  margin-top: 0pt;
                  margin-bottom: 8pt;
                  line-height: 108%;
                  font-size: 11pt;
                ">
              72 horas
            </p>
          </td>
          <td
            style="
                width: 120.35pt;
                border-bottom: 1pt solid #0066ff;
                padding-right: 4.9pt;
                padding-left: 5.4pt;
                vertical-align: middle;
              ">
            <p
              style="
                  margin-top: 0pt;
                  margin-bottom: 8pt;
                  line-height: 108%;
                  font-size: 11pt;
                ">
              7 d&iacute;as
            </p>
          </td>
        </tr>
        <tr style="height: 28.4pt">
          <td
            style="
                width: 81.1pt;
                border-right: 1pt solid #0066ff;
                border-bottom: 1pt solid #0066ff;
                padding-right: 4.9pt;
                padding-left: 4.9pt;
                vertical-align: middle;
              ">
            <p
              style="
                  margin-top: 0pt;
                  margin-bottom: 8pt;
                  line-height: 108%;
                  font-size: 11pt;
                ">
              <strong>Alta</strong>
            </p>
          </td>
          <td
            style="
                width: 120.3pt;
                border-right: 1pt solid #0066ff;
                border-bottom: 1pt solid #0066ff;
                padding-right: 4.9pt;
                padding-left: 5.4pt;
                vertical-align: middle;
              ">
            <p
              style="
                  margin-top: 0pt;
                  margin-bottom: 8pt;
                  line-height: 108%;
                  font-size: 11pt;
                ">
              1 mes
            </p>
          </td>
          <td
            style="
                width: 120.35pt;
                border-bottom: 1pt solid #0066ff;
                padding-right: 4.9pt;
                padding-left: 5.4pt;
                vertical-align: middle;
              ">
            <p
              style="
                  margin-top: 0pt;
                  margin-bottom: 8pt;
                  line-height: 108%;
                  font-size: 11pt;
                ">
              3 meses
            </p>
          </td>
        </tr>
        <tr style="height: 28.4pt">
          <td
            style="
                width: 81.1pt;
                border-right: 1pt solid #0066ff;
                border-bottom: 1pt solid #0066ff;
                padding-right: 4.9pt;
                padding-left: 4.9pt;
                vertical-align: middle;
              ">
            <p
              style="
                  margin-top: 0pt;
                  margin-bottom: 8pt;
                  line-height: 108%;
                  font-size: 11pt;
                ">
              <strong>Media</strong>
            </p>
          </td>
          <td
            style="
                width: 120.3pt;
                border-right: 1pt solid #0066ff;
                border-bottom: 1pt solid #0066ff;
                padding-right: 4.9pt;
                padding-left: 5.4pt;
                vertical-align: middle;
              ">
            <p
              style="
                  margin-top: 0pt;
                  margin-bottom: 8pt;
                  line-height: 108%;
                  font-size: 11pt;
                ">
              Basado en<br />planificaci&oacute;n de negocio
            </p>
          </td>
          <td
            style="
                width: 120.35pt;
                border-bottom: 1pt solid #0066ff;
                padding-right: 4.9pt;
                padding-left: 5.4pt;
                vertical-align: middle;
              ">
            <p
              style="
                  margin-top: 0pt;
                  margin-bottom: 8pt;
                  line-height: 108%;
                  font-size: 11pt;
                ">
              Basado en<br />planificaci&oacute;n de negocio
            </p>
          </td>
        </tr>
        <tr style="height: 28.4pt">
          <td
            style="
                width: 81.1pt;
                border-right: 1pt solid #0066ff;
                padding-right: 4.9pt;
                padding-left: 4.9pt;
                vertical-align: middle;
              ">
            <p
              style="
                  margin-top: 0pt;
                  margin-bottom: 8pt;
                  line-height: 108%;
                  font-size: 11pt;
                ">
              <strong>Baja</strong>
            </p>
          </td>
          <td
            style="
                width: 120.3pt;
                border-right: 1pt solid #0066ff;
                padding-right: 4.9pt;
                padding-left: 5.4pt;
                vertical-align: middle;
              ">
            <p
              style="
                  margin-top: 0pt;
                  margin-bottom: 8pt;
                  line-height: 108%;
                  font-size: 11pt;
                ">
              Basado en<br />planificaci&oacute;n de negocio
            </p>
          </td>
          <td
            style="
                width: 120.35pt;
                padding-right: 4.9pt;
                padding-left: 5.4pt;
                vertical-align: middle;
              ">
            <p
              style="
                  margin-top: 0pt;
                  margin-bottom: 8pt;
                  line-height: 108%;
                  font-size: 11pt;
                ">
              Basado en<br />planificaci&oacute;n de negocio
            </p>
          </td>
        </tr>
        </tbody>
      </table>
    </div>
    <p style="margin-top: 0pt; margin-bottom: 8pt">&nbsp;</p>
    <p style="margin-top: 0pt; margin-bottom: 8pt">
      Con independencia del origen y naturaleza de la
      vulnerabilidad,&nbsp;<strong>la responsabilidad sobre la remediaci&oacute;n de la misma recae sobre
        el propietario del activo</strong>
      (junto con su personal t&eacute;cnico de referencia).
    </p>
    <p style="margin-top: 0pt; margin-bottom: 8pt">
      En caso de que &eacute;ste decida no implantar las acciones establecidas a
      tal efecto por la Direcci&oacute;n CISO, el propietario del activo debe
      aceptar formalmente el riesgo.
    </p>
    <p
      style="
        margin-top: 0pt;
        margin-bottom: 8pt;
        text-align: center;
        line-height: 108%;
        font-size: 14pt;
      ">
      <span style="letter-spacing: 0.75pt; color: #595959">● ● ●</span>
    </p>
    <p style="margin-top: 0pt; margin-bottom: 8pt">
      Cualquier duda o comentario, estamos a vuestra disposici&oacute;n.
    </p>
    <p style="margin-top: 0pt; margin-bottom: 8pt">
      Dise&ntilde;o de Seguridad: e.arquitecturaseguridad.cdo@telefonica.com
    </p>
  </div>
</div>
