<!DOCTYPE html>
<html lang="es" xml:lang="es" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns:m="http://schemas.microsoft.com/office/2004/12/omml" xmlns="http://www.w3.org/TR/REC-html40">

<head>
    <title>Reporte KPMs</title>
    <meta http-equiv=Content-Type content="text/html; charset=windows-1252">
    <meta name=ProgId content=Word.Document>
    <meta name=Generator content="Microsoft Word 15">
    <meta name=Originator content="Microsoft Word 15">
    <style>
        /* Font Definitions */
        @font-face {
            font-family: "Cambria Math";
            panose-1: 2 4 5 3 5 4 6 3 2 4;
            mso-font-charset: 0;
            mso-generic-font-family: roman;
            mso-font-pitch: variable;
            mso-font-signature: -536869121 1107305727 33554432 0 415 0;
        }

        @font-face {
            font-family: Calibri;
            panose-1: 2 15 5 2 2 2 4 3 2 4;
            mso-font-charset: 0;
            mso-generic-font-family: swiss;
            mso-font-pitch: variable;
            mso-font-signature: -469750017 -1073732485 9 0 511 0;
        }

        /* Style Definitions */
        p.MsoNormal,
        li.MsoNormal,
        div.MsoNormal {
            margin: 0cm;
            font-size: 11.0pt;
            font-family: "Arial", sans-serif;
        }

        a:link,
        span.MsoHyperlink {
            color: #59C2C9;
            text-decoration: underline;
        }

        a:visited,
        span.MsoHyperlinkFollowed {
            color: #C366EF;
            text-decoration: underline;
        }

        p.msonormal0,
        li.msonormal0,
        div.msonormal0 {
            margin-right: 0cm;
            margin-left: 0cm;
            font-size: 11.0pt;
            font-family: "Calibri", sans-serif;
        }

        p.msonormal00,
        li.msonormal00,
        div.msonormal00 {
            margin-right: 0cm;
            margin-left: 0cm;
            font-size: 11.0pt;
            font-family: "Calibri", sans-serif;
        }

        p.msochpdefault,
        li.msochpdefault,
        div.msochpdefault {
            margin-right: 0cm;
            margin-left: 0cm;
            font-size: 10.0pt;
            font-family: "Arial", sans-serif;
        }

        span.estilocorreo18 {
            font-family: "Arial", sans-serif;
            color: windowtext;
        }

        .MsoChpDefault {
            font-size: 10.0pt;
        }

        @page WordSection1 {
            size: 612.0pt 792.0pt;
            margin: 70.85pt 3.0cm 70.85pt 3.0cm;
            mso-header-margin: 36.0pt;
            mso-footer-margin: 36.0pt;
            mso-paper-source: 0;
        }

        div.WordSection1 {
            page: WordSection1;
        }
    </style>

    <style>
        /* Style Definitions */
        table.MsoNormalTable {
            font-size: 10.0pt;
            font-family: "Times New Roman", serif;
        }

        table.MsoTable15Grid1LightAccent3 {
            border: solid #DBDBDB 1.0pt;
            font-size: 10.0pt;
            font-family: "Times New Roman", serif;
        }
    </style>
</head>

<body lang=ES>
    <div class=WordSection1>
        <p class=MsoNormal>
            <o:p>&nbsp;</o:p>
        </p>
        <div>
            <div>
                <table class=MsoNormalTable border=0 style='width:100.0%;background:#EEEDEC;border-collapse:collapse'>
                    <thead>
                        <tr>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tr>
                        <td style='width:100.0%;padding:7.5pt 7.5pt 7.5pt 7.5pt'>
                            <div>
                                <table class=MsoNormalTable border=0 style='width:463.5pt;border-collapse:collapse'>
                                    <thead>
                                        <tr>
                                            <th></th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tr>
                                        <td style='width:463.5pt;padding:0cm 0cm 0cm 0cm'>
                                            <p class=MsoNormal>&nbsp;<o:p></o:p>
                                            </p>
                                            <div>
                                                <table class=MsoNormalTable border=0 style='max-width:487.5pt;border-collapse:collapse'>
                                                    <thead>
                                                        <tr>
                                                            <th></th>
                                                            <th></th>
                                                        </tr>
                                                    </thead>
                                                    <tr>
                                                        <td style='background:#EEEDEC;padding:6.75pt 0cm 6.75pt 0cm'></td>
                                                    </tr>
                                                    <tr>
                                                        <td style='background:white;padding:0cm 0cm 0cm 0cm' id=templateHeader>
                                                            <table class=MsoNormalTable border=0 style='width:100.0%;border-collapse:collapse'>
                                                                <thead>
                                                                    <tr>
                                                                        <th></th>
                                                                        <th></th>
                                                                    </tr>
                                                                </thead>
                                                                <tr>
                                                                    <td style='padding:0cm 0cm 0cm 0cm'>
                                                                        <table class=MsoNormalTable border=0 style='border-collapse:collapse'>
                                                                            <thead>
                                                                                <tr>
                                                                                    <th></th>
                                                                                    <th></th>
                                                                                </tr>
                                                                            </thead>
                                                                            <tr>
                                                                                <td style='padding:0cm 0cm 0cm 0cm'>
                                                                                    <p class=MsoNormal style='text-align:center'><span><img width=650 height=188 id="_x0000_i1025" src="https://bxbucket.blob.core.windows.net/bxbucket/resources/mail/ciso/cabecera-11cert-2023.JPG" alt="Offsite CDO 2022"></span>
                                                                                        <o:p></o:p>
                                                                                    </p>
                                                                                </td>
                                                                            </tr>
                                                                        </table>
                                                                    </td>
                                                                </tr>
                                                            </table>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td style='border:none;border-bottom:solid #EAEAEA 1.5pt;
      background:white;padding:0cm 0cm 6.75pt 0cm' id=templateBody>
                                                            <table class=MsoNormalTable border=0 style='width:100.0%;border-collapse:collapse;min-width:100%'>
                                                                <thead>
                                                                    <tr>
                                                                        <th></th>
                                                                        <th></th>
                                                                    </tr>
                                                                </thead>
                                                                <tr>
                                                                    <td style='padding:6.75pt 0cm 0cm 0cm;min-width:100%'>
                                                                        <table class=MsoNormalTable border=0 style='width:100.0%;border-collapse:collapse;min-width:100%'>
                                                                            <thead>
                                                                                <tr>
                                                                                    <th></th>
                                                                                    <th></th>
                                                                                </tr>
                                                                            </thead>
                                                                            <tr>
                                                                                <td style='width:450.0pt;padding:0cm 0cm 0cm 0cm;
          min-width:100%'>
                                                                                    <table class=MsoNormalTable border=0 style='width:100.0%;border-collapse:collapse;min-width:100%'>
                                                                                        <thead>
                                                                                            <tr>
                                                                                                <th></th>
                                                                                                <th></th>
                                                                                            </tr>
                                                                                        </thead>
                                                                                        <tr>
                                                                                            <td style='width:100.0%;padding:15.0pt 30.0pt 6.75pt 30.0pt;min-width:100%'>
                                                                                                <p class=MsoNormal style='line-height:150%'><span style='color:
            #414B61'>Estimado usuario,<o:p></o:p></span></p>
                                                                                                <p class=MsoNormal style='line-height:150%'><span style='color:
            #414B61'>
                                                                                                        <o:p>&nbsp;</o:p>
                                                                                                    </span></p>
                                                                                                <p class=MsoNormal style='line-height:150%'><span style='color:
            #414B61'>Te informamos de que este es un <b>mensaje automático</b>
                                                                                                        enviado desde la herramienta <b>11Cert.</b>
                                                                                                        <br><br>
                                                                                                        <o:p></o:p>
                                                                                                    </span></p>
                                                                                                <p class=MsoNormal style='line-height:150%'><span style='color:
            #414B61'>Nos ponemos en contacto contigo para notificarte que {user} ha reportado los KPMs de <b>{area}</b> con <b>ID de reporte {idReporte} </b>, y hemos encontrado posibles incongruencias en los siguientes KPMs: <o:p></o:p></span></p>
                                                                                                <p class=MsoNormal style='line-height:150%'>
                                                                                                    <o:p>&nbsp;</o:p>
                                                                                                </p>
                                                                                                <p class=MsoNormal style='line-height:150%'><span style='color:
            #414B61'>{kpms}<o:p></o:p></span></p>
                                                                                                <p class=MsoNormal style='line-height:150%'><span style='font-size:
            10.5pt;line-height:150%;color:#414B61;display:none'>&nbsp;</span>
                                                                                                    <o:p></o:p>
                                                                                                </p>
                                                                                                <table class=MsoTable15Grid1LightAccent3 border=0 style='width:100.0%;border-collapse:collapse;border:none;min-width:100%'>
                                                                                                    <thead>
                                                                                                        <tr>
                                                                                                            <th></th>
                                                                                                            <th></th>
                                                                                                        </tr>
                                                                                                    </thead>
                                                                                                    <tr>
                                                                                                        <td style='border:none;border-bottom:solid #C9C9C9 1.5pt;padding:0cm 5.4pt 0cm 5.4pt'>
                                                                                                            <p class=MsoNormal style='margin-bottom:12.0pt;line-height:150%'><span style='font-size:10.5pt;line-height:150%;
              color:#414B61'>Recuerda que estamos a tu disposición y<b> </b></span><b><span style='color:#414B61'>puedes</span></b><span style='color:#414B61'>
                                                                                                                    <b>contactar con nosotros</b></span><b><span style='font-size:
              10.5pt;line-height:150%;color:#414B61'> </span></b><span style='font-size:10.5pt;line-height:150%;color:#414B61'>a través
                                                                                                                    del consultor de 11cert asociado a tu servicio o escribiéndonos
                                                                                                                    al buzón:<b> </b></span><span class=MsoHyperlink><b><a href="mailto:ciso.cdo@telefonica.com">ciso.cdo@telefonica.com</a></b></span><span class=MsoHyperlink><span style='color:windowtext;text-decoration:
              none'>.</span></span><b>
                                                                                                                    <o:p></o:p>
                                                                                                                </b></p>
                                                                                                            <table class=MsoNormalTable border=0 style='width:100.0%;border-collapse:collapse;min-width:100%'>
                                                                                                                <thead>
                                                                                                                    <tr>
                                                                                                                        <th></th>
                                                                                                                        <th></th>
                                                                                                                    </tr>
                                                                                                                </thead>
                                                                                                                <tr>
                                                                                                                    <td style='width:26.25pt;padding:0cm 0cm 0cm 0cm'></td>
                                                                                                                    <td style='padding:0cm 0cm 0cm 0cm'></td>
                                                                                                                </tr>
                                                                                                            </table>
                                                                                                        </td>
                                                                                                    </tr>
                                                                                                </table>
                                                                                                <p class=MsoNormal style='line-height:150%'><span style='font-size:10.5pt;line-height:150%;color:#414B61;display:none'>&nbsp;</span>
                                                                                                    <o:p></o:p>
                                                                                                </p>
                                                                                                <table class=MsoNormalTable border=0 style='width:100.0%;border-collapse:collapse;min-width:100%'>
                                                                                                    <thead>
                                                                                                        <tr>
                                                                                                            <th></th>
                                                                                                            <th></th>
                                                                                                        </tr>
                                                                                                    </thead>
                                                                                                    <tr>
                                                                                                        <td style='padding:0cm 0cm 0cm 0cm'>
                                                                                                            <p class=MsoNormal style='margin-bottom:7.5pt;
              text-align:center;line-height:150%'><strong><span style='font-size:10.5pt;line-height:150%;font-family:"Arial",sans-serif;
              color:#0066FF'>La seguridad es responsabilidad de todos.
                                                                                                                        ¡Contamos contigo!</span></strong>
                                                                                                                <o:p></o:p>
                                                                                                            </p>
                                                                                                            <p class=MsoNormal style='margin-bottom:7.5pt;
              text-align:center;line-height:150%'><span style='color:#414B61'>Dirección
                                                                                                                    CISO de CDO</span>
                                                                                                                <o:p></o:p>
                                                                                                            </p>
                                                                                                        </td>
                                                                                                    </tr>
                                                                                                    <tr>
                                                                                                        <td style='padding:0cm 0cm 0cm 0cm'></td>
                                                                                                    </tr>
                                                                                                </table>
                                                                                                <p class=MsoNormal><span style='font-size:10.0pt;font-family:"Times New Roman",serif'>
                                                                                                        <o:p></o:p>
                                                                                                    </span></p>
                                                                                            </td>
                                                                                        </tr>
                                                                                    </table>
                                                                                </td>
                                                                            </tr>
                                                                        </table>
                                                                    </td>
                                                                </tr>
                                                            </table>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td style='padding:6.75pt 0cm 6.75pt 0cm' id=templateFooter>
                                                            <table class=MsoNormalTable border=0 style='width:100.0%;border-collapse:collapse;min-width:100%'>
                                                                <thead>
                                                                    <tr>
                                                                        <th></th>
                                                                        <th></th>
                                                                    </tr>
                                                                </thead>
                                                                <tr>
                                                                    <td style='padding:6.75pt 6.75pt 6.75pt 6.75pt;min-width:100%'>
                                                                        <div>
                                                                            <table class=MsoNormalTable border=0 style='width:100.0%;border-collapse:collapse;min-width:100%'>
                                                                                <thead>
                                                                                    <tr>
                                                                                        <th></th>
                                                                                        <th></th>
                                                                                    </tr>
                                                                                </thead>
                                                                                <tr>
                                                                                    <td style='padding:6.75pt 0cm 0cm 0cm;min-width:100%'>
                                                                                        <table class=MsoNormalTable border=0 lign=leftstyle='width:100.0%;border-collapse:collapse;min-width:100%'>
                                                                                            <thead>
                                                                                                <tr>
                                                                                                    <th></th>
                                                                                                    <th></th>
                                                                                                </tr>
                                                                                            </thead>
                                                                                            <tr>
                                                                                                <td style='width:450.0pt;padding:0cm 0cm 0cm 0cm;
            min-width:100%'>
                                                                                                    <table class=MsoNormalTable border=0 style='width:100.0%;border-collapse:collapse;min-width:100%'>
                                                                                                        <thead>
                                                                                                            <tr>
                                                                                                                <th></th>
                                                                                                                <th></th>
                                                                                                            </tr>
                                                                                                        </thead>
                                                                                                        <tr>
                                                                                                            <td style='padding:0cm 7.5pt 6.75pt 7.5pt;min-width:100%'>
                                                                                                                <p class=MsoNormal style='margin-bottom:7.5pt;text-align:justify;
              line-height:150%'><span style='font-size:9.0pt;line-height:150%;
              color:#656565'>© 2022 Telefónica Digital España S.L.U. Todos los
                                                                                                                        derechos reservados.</span>
                                                                                                                    <o:p></o:p>
                                                                                                                </p>
                                                                                                                <p class=MsoNormal style='margin-bottom:7.5pt;text-align:justify;
              line-height:150%'><span style='font-size:9.0pt;line-height:150%;
              color:#656565'>Este documento es exclusivamente para uso interno
                                                                                                                        por parte del personal de Telefónica. Ninguna parte del mismo
                                                                                                                        puede circularse, citarse o reproducirse para su distribución
                                                                                                                        externa, ni su contenido puede ser difundido por ningún medio
                                                                                                                        fuera de la compañía. Si usted no es empleado de Telefónica,
                                                                                                                        queda notificado de que la lectura, utilización, divulgación y/o
                                                                                                                        copia sin autorización está prohibida en virtud de la legislación
                                                                                                                        vigente. Si ha recibido este mensaje por error, le rogamos que
                                                                                                                        proceda a su destrucción. El correo electrónico vía Internet no
                                                                                                                        permite asegurar la confidencialidad de los mensajes que se
                                                                                                                        transmiten ni su integridad o correcta recepción. Telefónica no
                                                                                                                        asume ninguna responsabilidad por estas circunstancias.</span>
                                                                                                                    <o:p></o:p>
                                                                                                                </p>
                                                                                                            </td>
                                                                                                        </tr>
                                                                                                    </table>
                                                                                                </td>
                                                                                            </tr>
                                                                                        </table>
                                                                                    </td>
                                                                                </tr>
                                                                            </table>
                                                                        </div>
                                                                    </td>
                                                                </tr>
                                                            </table>
                                                        </td>
                                                    </tr>
                                                </table>
                                            </div>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                        </td>
                    </tr>
                </table>

            </div>

            <p class=MsoNormal style='text-align:center'>&nbsp;<o:p></o:p>
            </p>

            <p class=MsoNormal>&nbsp;<o:p></o:p>
            </p>

        </div>

    </div>

</body>

</html>
