<!DOCTYPE html>
<html lang="es">

<head>
    <?php
    if (isset($message)) {
        $message = htmlspecialchars($message, ENT_QUOTES, 'UTF-8');
    } else {
        $message = "Error desconocido";
    }
    getheader("Error - " . $message . " - 11Cert", false)
    ?>
    <title>Error - <?php if (isset($message)) {
                        echo $message;
                    } ?></title>
</head>

<body class="d-flex flex-column h-100">
    <?php getmenu(false, false) ?>
    <div class="container h-100">
        <div class="row justify-content-center align-items-center h-100">
            <div class="col-md-6">
                <div class="row">
                    <div class="col-md-12">
                        <div class="alert-container justify-content-center">
                            <img src="./img/alert.svg" class="icon-40" alt="Alerta">
                            <div class="error-text">ERROR</div>
                        </div>
                    </div>

                    <div class="col-md-12 d-flex justify-content-center">
                        <div class="dragon-container position-relative">
                            <img src="./img/computer.svg" class="icon-300 d-inline-block" alt="Ordenador">
                            <div class="error-code position-absolute d-inline-block"><?php if (isset($statusCode)) {
                                                                                            echo $statusCode;
                                                                                        } ?></div>
                        </div>
                    </div>



                    <div class="col-md-12 text-center">
                        <h1 class="font-28"><?php
                                            if (isset($message)) {
                                                echo $message;
                                            }
                                            ?></h1>
                        <a href="./" class="btn btn-primary">Volver a la página de inicio</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php getfooter(); ?>
</body>

</html>

</html>
