<!DOCTYPE html>
<html lang="es">

<head>
    <title>Módulo EVS</title>
    <?php getheader("Módulo EVS", false) ?>
    <script type="module" src="./js/modules/evsModule.js" type="text/javascript" integrity="<?php echo "sha384-" . base64_encode(hash_file('sha384', "./js/modules/evsModule.js", true)) ?>" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="./css/update.css">
    <link rel="stylesheet" href="./css/styleLoading.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.2/fullcalendar.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.2/fullcalendar.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.2/locale-all.js"></script>

</head>

<body class="d-flex flex-column h-100">
    <?php getmenu() ?>
    <div class="container pag-EVS">
        <div class='col-12 response mb-3 EVS'>
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a class="nav-link pointer" id="#solicitudesPentest">Solicitudes de pentest</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active pointer" id="#planificacion-tab" data-bs-toggle="tab">Planificación</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link pointer" id="#pentest">Pentests activos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link pointer" id="#issues">Issues</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link pointer" id="#pynt">Pynt</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link pointer" id="#sdlc">sSDLC</a>
                </li>
            </ul>
        </div>
        <div class="tab-content mshide" id="issues">
            <!-- Contenido de Issues -->
            <?php insertLoadingDinamic("Issues de Jira", "issuesLoading", "mb-2") ?>
            <div class="tablaIssues row justify-content-end">
                <div class="col-md-3 mb-3">
                    <div class="rounded sombraRegistro contRegistradas d-flex flex-column align-items-center">
                        <p class="textContador my-auto">Registradas</p>
                        <p class="textContador my-auto"><span
                                class="textRegistradas">0</span></p>
                    </div>
                </div>
                <div class="col-md-3 mb-3">
                    <div class="contador sombraContador rounded contAbiertas d-flex flex-column align-items-center">
                        <p class="textContador my-auto">Abiertas</p>
                        <p class="textContador textAbiertas my-auto">0</p>
                    </div>
                </div>
                <div class="col-md-3 mb-3">
                    <div class="contador sombraContador rounded contCerradas d-flex flex-column align-items-center">
                        <p class="textContador my-auto">Cerradas</p>
                        <p class="textContador textCerradas my-auto">0</p>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="contador sombraContador rounded contClonadas d-flex flex-column align-items-center">
                        <p class="textContador my-auto">Clonadas cerradas</p>
                        <p class="textContador textClonadas my-auto">0</p>
                    </div>
                </div>
            </div>
            <div class="col-sm">
                <button class="btn btn-primary btn-volver mshide">Volver</button>
            </div>
            <div class="col-sm">
                <button class="btn btn-primary btn-editIssue moduloInfo float-right btn-spacer mshide">Editar
                    issue</button>
                <button class="btn btn-primary btn-delIssue moduloInfo float-right btn-spacer mshide">Eliminar
                    issue</button>
            </div>
            <div class='tablaIssues mshide'>
                <button class="btn btn-primary btn-newIssue float-right">Crear issue</button>
                <div class="issues">
                    <table class="table table-condensed table-hover table-striped table-issues" id='issuesTabla'>
                        <caption>Listado de Issues de Jira</caption>
                        <thead>
                            <tr>
                                <th data-column-id="id" data-header-css-class="IDCol" id="id">CISO ID</th>
                                <th data-column-id="Estado" data-header-css-class="estadoCol" id="nombre">Estado</th>
                                <th data-column-id="EstadoClonada" data-header-css-class="estadoClonadaCol"
                                    data-visible="false" id="nombre">Estado clonada</th>
                                <th data-column-id="Resumen" data-header-css-class="resumenCol" id="descripcion">Resumen
                                </th>
                                <th data-column-id="Proyecto" data-header-css-class="proyectoCol" id="tipo">Proyecto
                                </th>
                                <th data-column-id="Responsable" data-header-css-class="responsableCol"
                                    data-visible="false" id="by">Informada por:</th>
                                <th data-column-id="Pentest" data-header-css-class="pentestCol" data-visible="false"
                                    id="by">Pentest</th>
                                <th data-column-id="Fecha" data-header-css-class="fechaCol"
                                    data-type="date" id="date">Fecha</th>
                                <th data-column-id="Dias" data-header-css-class="diasCol" data-visible="false"
                                    id="dias">Antigüedad</th>
                                <th data-column-id="Prioridad" data-header-css-class="prioridadCol" id="prio">Prioridad</th>
                                <th data-column-id="commands" data-header-css-class="editarCol trTable" data-formatter="commands" data-sortable="false" data-searchable="false">Acciones</th>
                            </tr>
                        </thead>
                        <tbody id='tiposIssues'>
                        </tbody>
                    </table>
                </div>
                <div class="ClonadasCerradas mshide">
                    <table class="table table-condensed table-hover table-striped table-issues"
                        id='cerradasClonadasTabla'>
                        <caption>Listado de Issues de Jira</caption>
                        <thead>
                            <tr>
                                <th data-column-id="id" data-header-css-class="IDCol" id="id">CISO ID</th>
                                <th data-column-id="Estado" data-header-css-class="estadoCol" id="nombre">Estado</th>
                                <th data-column-id="EstadoClonada" data-header-css-class="estadoClonadaCol"
                                    data-visible="false" id="nombre">Estado clonada</th>
                                <th data-column-id="Resumen" data-header-css-class="resumenCol" id="descripcion">Resumen
                                </th>
                                <th data-column-id="Proyecto" data-header-css-class="proyectoCol" id="tipo">Proyecto
                                </th>
                                <th data-column-id="Responsable" data-header-css-class="responsableCol"
                                    data-visible="false" id="by">Informada por:</th>
                                <th data-column-id="Pentest" data-header-css-class="pentestCol" data-visible="false"
                                    id="by">Pentest</th>
                                <th data-column-id="Fecha" data-header-css-class="fechaCol" data-visible="false"
                                    id="date">Fecha</th>
                                <th data-column-id="Dias" data-header-css-class="diasCol" data-visible="false"
                                    id="dias">Antigüedad</th>
                                <th data-column-id="Prioridad" data-header-css-class="prioridadCol" id="prio">Prioridad
                                </th>
                            </tr>
                        </thead>
                        <tbody id='tiposCerradas'>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="infoIssue mshide mt-5">
                <div class="row">
                    <div class="col-md-12">
                        <h5 class="text-center infoKey mshide">Cargando key...</h5>
                        <h5 class="text-center"> <a href="" target="_blank" class="enlaceIssue">Cargando key...</a> / <a
                                href="" target="_blank" class="enlaceClonada">Cargando key...</a></h5>
                        <h1 class="text-center font-weight-bold infoSummary mb-2">Cargando resumen...</h1>
                        <div class="row mb-3">
                            <div class="col-md-12">
                                <button class="btn btn-primary btn-status btn-closeIssue float-right mshide">Cerrar
                                    issue</button>
                                <button class="btn btn-primary btn-status btn-openIssue float-right mshide">Abrir
                                    issue</button>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <table class="table table-borderless">
                                    <thead>
                                        <tr>
                                            <th scope="col">Campo</th>
                                            <th scope="col">Valor</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td class="titulo">Estado:</td>
                                            <td class="infoEstado">Cargando...</td>
                                        </tr>
                                        <tr>
                                            <td class="titulo">Resolución:</td>
                                            <td class="infoRes">Cargando...</td>
                                        </tr>
                                        <tr>
                                            <td class="titulo">Nivel de seguridad:</td>
                                            <td class="infoNivel">Cargando...</td>
                                        </tr>
                                        <tr>
                                            <td class="titulo">Etiquetas:</td>
                                            <td class="infoTag">Cargando...</td>
                                        </tr>
                                    </tbody>
                                </table>
                                <table class="table table-borderless">
                                    <thead>
                                        <tr>
                                            <th scope="col">Campo</th>
                                            <th scope="col">Valor</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <th class="titulo" scope="row">Descripción:</th>
                                            <td class="infoDesc">Cargando...</td>
                                        </tr>
                                    </tbody>
                                </table>
                                <table class="table table-borderless">
                                    <thead>
                                        <tr>
                                            <th scope="col">Campo</th>
                                            <th scope="col">Valor</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td class="titulo">Evidencias:</td>
                                            <td class="insertEvidence">
                                                <form class="ArchivosForm">
                                                    <input type="file" class="form-control-file" id="archivos"
                                                        name="file[]" multiple>
                                                    <div class="btn btn-primary ms-2 btnEnviarArchivos">Enviar</div>
                                                </form>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            <div class="col-md-6">
                                <table class="table table-borderless table-transparent">
                                    <thead>
                                        <tr>
                                            <th scope="col">Campo</th>
                                            <th scope="col">Valor</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td class="titulo">Prioridad Ciso:</td>
                                            <td class="infoPrio">Cargando...</td>
                                        </tr>
                                        <tr>
                                            <td class="titulo">Proyecto de area/servicio:</td>
                                            <td class="infoProy">Cargando...</td>
                                        </tr>
                                        <tr>
                                            <td class="titulo">Metodología - Definicion de la vulnerabilidad:</td>
                                            <td class="infoMeto">Cargando...</td>
                                        </tr>
                                        <tr>
                                            <td class="titulo">CVSS:</td>
                                            <td class="infoCVSS">Cargando...</td>
                                        </tr>
                                        <tr>
                                            <td class="titulo">Tipo de vulnerabilidad:</td>
                                            <td class="infoVulne">Cargando...</td>
                                        </tr>
                                        <tr>
                                            <td class="titulo">Tipo de análisis:</td>
                                            <td class="infoAnalysis">Cargando...</td>
                                        </tr>
                                        <tr>
                                            <td class="titulo">Impacto de vulnerabilidad:</td>
                                            <td class="infoImpact">Cargando...</td>
                                        </tr>
                                        <tr>
                                            <td class="titulo">Probabilidad de explotación:</td>
                                            <td class="infoProb">Cargando...</td>
                                        </tr>
                                        <tr>
                                            <td class="titulo">Estado de la vulnerabilidad:</td>
                                            <td class="infoStatus">Cargando...</td>
                                        </tr>
                                        <tr>
                                            <td class="titulo">URL:</td>
                                            <td class="infoUrl">Cargando...</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <h4 class="text-center mt-5">Comentarios</h4>
                    <div class="chat-container">
                        <div class="col-12 chat">
                            <div class="card mb-2">
                                <div class="card-header writter">
                                    <h6 class="card-title mb-0 escritor">Cargando comentarios...</h6>
                                </div>
                                <div class="card-body">
                                    <p class="card-text comentario">Cargando comentarios...</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-12 input-container d-flex align-items-center">
                            <input type="text" class="form-control flex-grow-1 commentWritter"
                                placeholder="Escribe un mensaje...">
                            <button class="btn btn-primary ms-2 btnEnviarComentario">Enviar</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-content mshide" id="sdlc">
            <div class="tablaIssues row justify-content-end">
                <div class="col-md-6 mb-3">
                    <div class="contador sombraRegistroKiuwan rounded contKiuwan d-flex flex-column align-items-center">
                        <p class="textContador my-auto">APPs en Kiuwan</p>
                        <p class="textContador my-auto"><span class="textKiuwanTotal">0</span>/<span
                                class="textKiuwanTotal">0</span></p>
                    </div>
                </div>
                <div class="col-md-6 mb-3">
                    <div class="contador sombraContador rounded contSonarqube d-flex flex-column align-items-center">
                        <p class="textContador my-auto">APPs en Sonarqube</p>
                        <p class="textContador my-auto"><span class="textSonarqube">0</span>/<span
                                class="textSonarqube">0</span></p>
                    </div>
                </div>
            </div>

            <!-- Tabla para Kiuwan (inicialmente visible) -->
            <div id="kiuwanTable" class="app-table">
                <button class="btn btn-primary btn-newAPP ms-2 float-right">Registrar aplicación</button>
                <button class="btn btn-primary btn-downloadSDLC ms-2 float-right">Descargar tabla</button>
                <table class="table table-condensed table-hover table-striped table-issues" id="sdlcTablaKiuwan">
                    <caption>Tabla SDLC - Kiuwan</caption>
                    <thead>
                        <tr>
                            <th data-column-id="id" data-header-css-class="id" id="id" data-searchable="true" data-visible="false">ID</th>
                            <th data-column-id="Direccion" data-header-css-class="direccionCol" data-visible="false" id="direccion">
                                Dirección</th>
                            <th data-column-id="Area" data-header-css-class="areaCol" data-visible="false" id="area">
                                Área</th>
                            <th data-column-id="Producto" data-header-css-class="productoCol" id="producto">
                                Producto</th>
                            <th data-column-id="slot_kiuwan" data-header-css-class="appCol" id="appKiuwan" class="app-switcher">
                                Slot en Kiuwan</th>
                            <th data-column-id="Criticidad" data-header-css-class="criticidadCol" id="criticidad">
                                Crítico</th>
                            <th data-column-id="Exposicion" data-header-css-class="exposicionCol" id="exposicion">
                                Exposición</th>
                            <th data-column-id="Analisis" data-header-css-class="analisisCol" data-visible="false"
                                id="analisis">Análisis
                            </th>
                            <th data-column-id="CMM" data-header-css-class="CMMCol" id="cmm">CMM</th>
                            <th data-column-id="Comentarios" data-header-css-class="ComentariosCol" data-visible="false"
                                id="com">Comentarios</th>
                            <th data-column-id="fechaAnalisis" data-header-css-class="fechaAnalisis" data-type="date" id="fechaAnalisis">
                                Fecha Analisis</th>
                            <th data-column-id="cumpleKPM07" data-header-css-class="cumpleKPM07" id="cumpleKPM07">
                                KPM07</th>
                            <th data-column-id="commands" data-header-css-class="editarCol" data-searchable="false" data-formatter="commands"
                                data-sortable="false">Editar</th>
                        </tr>
                    </thead>
                    <tbody id="sdlcTotalKiuwan">
                        <!-- Aquí van las filas de datos generadas dinámicamente -->
                    </tbody>
                </table>
            </div>

            <!-- Tabla para Sonarqube (inicialmente oculta) -->
            <div id="sonarqubeTable" class="app-table" style="display: none;">
                <table class="table table-condensed table-hover table-striped table-issues" id="sdlcTablaSonarqube">
                    <caption>Tabla SDLC - Sonarqube</caption>
                    <thead>
                        <tr>
                            <th data-column-id="id" data-header-css-class="id" id="id" data-searchable="true" data-visible="false">ID</th>
                            <th data-column-id="Direccion" data-header-css-class="direccionCol" data-visible="false" id="direccion">
                                Dirección</th>
                            <th data-column-id="Area" data-header-css-class="areaCol" data-visible="false" id="area">
                                Área</th>
                            <th data-column-id="Producto" data-header-css-class="productoCol" id="producto">
                                Producto</th>
                            <th data-column-id="url_sonar" data-header-css-class="sonarUrlCol" id="sonarUrl">URL
                                SonarQube</th>
                            <th data-column-id="slot_sonarqube" data-header-css-class="appColSonar" id="appSonarQube" class="app-switcher">
                                Slot en Sonarqube</th>
                            <th data-column-id="Criticidad" data-header-css-class="criticidadCol" id="criticidad">
                                Crítico</th>
                            <th data-column-id="Exposicion" data-header-css-class="exposicionCol" id="exposicion">
                                Exposición</th>
                            <th data-column-id="Analisis" data-header-css-class="analisisCol" data-visible="false"
                                id="analisis">Análisis</th>
                            <th data-column-id="CMM" data-header-css-class="CMMCol" id="cmm">CMM</th>
                            <th data-column-id="Comentarios" data-header-css-class="ComentariosCol" data-visible="false"
                                id="com">Comentarios</th>
                            <th data-column-id="fechaAnalisisSonar" data-header-css-class="fechaAnalisisSonar" id="fechfechaAnalisisSonaraAnalisis">
                                Fecha Analisis</th>
                            <th data-column-id="cumpleKPM07" data-header-css-class="cumpleKPM07" id="cumpleKPM07">
                                KPM07</th>
                            <th data-column-id="commands" data-header-css-class="editarCol" data-searchable="false" data-formatter="commands"
                                data-sortable="false">Editar</th>
                        </tr>
                    </thead>
                    <tbody id="sdlcTotalSonarqube">
                        <!-- Aquí van las filas de datos generadas dinámicamente -->
                    </tbody>
                </table>
            </div>

        </div>
        <div class="tab-content mshide" id="pentest">
            <div class="row">
                <h2 class="text-center">Administrador de pentest</h2>
                <div class="col-12">
                    <button class="btn btn-primary float-right btn-ImpPentest ms-2 mb-3">Importar pentest</button>
                    <input class="inputExcel excelPent mshide" type="file" name="excelPent" />
                </div>
            </div>
            <div class="row tarjetasPentest">

            </div>
            <div class="row">
                <table class="table table-condensed table-hover table-striped table-issues" id='pentestTabla'>
                    <caption>Tabla pentests</caption>
                    <thead>
                        <tr>
                            <th data-column-id="Id" data-header-css-class="id" id="id" data-visible="false">id</th>
                            <th data-column-id="Nombre" data-header-css-class="nombreCol" id="nombre">Nombre</th>
                            <th data-column-id="Proyecto" data-header-css-class="Proyecto" data-visible="true"
                                id="proyecto">Proyecto</th>
                            <th data-column-id="FechaInicio" data-header-css-class="fechaInicioCol" id="fechaInicio">
                                Fecha inicio</th>
                            <th data-column-id="FechaFinal" data-header-css-class="fechaFinalCol" id="fechaFinal">Fecha
                                final</th>
                            <th data-column-id="Estado" data-header-css-class="estadoCol" id="estado">Estado</th>
                            <th data-column-id="commands" data-formatter="commands" data-header-css-class="editarCol"
                                data-sortable="false" data-searchable="false"></th>
                        </tr>
                    </thead>
                    <tbody id='pentestTotal'>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="tab-content mshide" id="pynt">
            <div class="row">
                <h2 class="text-center">Administrador de Pynt</h2>
                <div class="col-12">
                    <button class="btn btn-primary float-right btn-newPynt ms-2 mb-3">Nueva prueba</button>
                </div>
            </div>
            <div class="row">
                <table class="table table-condensed table-hover table-striped table-issues" id='pyntTabla'>
                    <caption>Tabla Pynt</caption>
                    <thead>
                        <tr>
                            <th data-column-id="Id" data-header-css-class="id" id="id" data-visible="false">id</th>
                            <th data-column-id="Nombre" data-header-css-class="nombreCol" id="nombre">Nombre</th>
                            <th data-column-id="Proyecto" data-header-css-class="Proyecto" data-visible="true"
                                id="proyecto">Proyecto</th>
                            <th data-column-id="FechaInicio" data-header-css-class="fechaInicioCol" id="fechaInicio">
                                Fecha inicio</th>
                            <th data-column-id="FechaFinal" data-header-css-class="fechaFinalCol" id="fechaFinal">Fecha
                                final</th>
                            <th data-column-id="Estado" data-header-css-class="estadoCol" id="estado">Estado</th>
                            <th data-column-id="commands" data-formatter="commands" data-header-css-class="editarCol"
                                data-sortable="false" data-searchable="false"></th>
                        </tr>
                    </thead>
                    <tbody id='pyntTotal'>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="tab-content mshide" id="solicitudesPentest">
            <div class="container" id="pentestContainer">
                <!-- Aquí se añadirán los nuevos contenedores -->
            </div>
        </div>
        <div class="tab-content" id="planificacion-tab">
            <div class="row">
                <div class="col-md-10" id="calendarContainer">
                    <div id="calendar" class="calendar-style"></div>
                </div>
                <div class="col-md-2" id="eventListContainer">
                    <h5>Próximos eventos</h5>
                    <ul id="upcomingEventsList" class="list-group"></ul>
                </div>
            </div>
        </div>
    </div>
    <?php getfooter() ?>
</body>

</html>
