<!DOCTYPE html>
<html lang="es">

<head>
    <title>Home</title>
    <?php getheader("Home", false) ?>
    <link rel="stylesheet" href="./css/home.css">
</head>

<body class="d-flex flex-column h-100">
    <?php getmenu(true, false) ?>
    <div class="container">
        <div class="row">
            <?php
            if (isset($_)) {
                $token = $_->getAttribute(TOKEN);
            }

            if (isset($token["data"])) {
                $db_user = new Usuarios(DB_USER);
                $cards = $db_user->getCardsHomeByUser($token["data"]);
                if (isset($cards)) {
                    $col_class = count($cards) > 1 ? 'col-md-4' : 'col-md-12';
                    foreach ($cards as $card) {
                        $title = $card["title"];
                        $description = $card["description"];
                        $img = $card["img"];
                        $url = $card["url"];

                        echo '<div class="' . $col_class . ' mb-5">
                            <div class="card d-flex flex-column">
                                <div class="text-center">
                                    <img src="' . $img . '" class="card-img-top cardImg mt-4 mb-3" alt="icono formulario">
                                </div>
                                <div class="card-body d-flex flex-column justify-content-between">
                                    <div>
                                        <b>
                                            <h2 class="card-title
                                            ">' . $title . '</h2>
                                        </b>
                                        <h3 class="card-text">' . $description . '</h3>
                                    </div>
                                    <div class="mt-auto">
                                        <a href="' . $url . '" class="btn btn-secondary my-btn">Entrar</a>
                                    </div>
                                </div>
                            </div>
                        </div>';
                    }
                }
            }
            ?>
        </div>
    </div>
    <?php getfooter(); ?>
</body>

</html>
