<!DOCTYPE html>
<html lang="es" xml:lang="es" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns:m="http://schemas.microsoft.com/office/2004/12/omml" xmlns="http://www.w3.org/TR/REC-html40">

<head>
    <meta http-equiv=Content-Type content="text/html; charset=windows-1252">
    <meta name=ProgId content=Word.Document>
    <meta name=Generator content="Microsoft Word 15">
    <meta name=Originator content="Microsoft Word 15">
    <style>
        /* Font Definitions */
        @font-face {
            font-family: "Cambria Math";
            panose-1: 2 4 5 3 5 4 6 3 2 4;
            mso-font-charset: 0;
            mso-generic-font-family: roman;
            mso-font-pitch: variable;
            mso-font-signature: -536869121 1107305727 33554432 0 415 0;
        }

        @font-face {
            font-family: Calibri;
            panose-1: 2 15 5 2 2 2 4 3 2 4;
            mso-font-charset: 0;
            mso-generic-font-family: swiss;
            mso-font-pitch: variable;
            mso-font-signature: -469750017 -1073732485 9 0 511 0;
        }

        /* Style Definitions */
        p.MsoNormal,
        li.MsoNormal,
        div.MsoNormal {
            margin: 0cm;
            font-size: 11.0pt;
            font-family: "Arial", sans-serif;
        }

        a:link,
        span.MsoHyperlink {
            color: #59C2C9;
            text-decoration: underline;
        }

        a:visited,
        span.MsoHyperlinkFollowed {
            color: #C366EF;
            text-decoration: underline;
        }

        p.msonormal0,
        li.msonormal0,
        div.msonormal0 {
            margin-right: 0cm;
            margin-left: 0cm;
            font-size: 11.0pt;
            font-family: "Calibri", sans-serif;
        }

        p.msonormal00,
        li.msonormal00,
        div.msonormal00 {
            margin-right: 0cm;
            margin-left: 0cm;
            font-size: 11.0pt;
            font-family: "Calibri", sans-serif;
        }

        p.msochpdefault,
        li.msochpdefault,
        div.msochpdefault {
            margin-right: 0cm;
            margin-left: 0cm;
            font-size: 10.0pt;
            font-family: "Arial", sans-serif;
        }

        span.estilocorreo18 {
            font-family: "Arial", sans-serif;
            color: windowtext;
        }

        .MsoChpDefault {
            font-size: 10.0pt;
        }

        @page WordSection1 {
            size: 612.0pt 792.0pt;
            margin: 70.85pt 3.0cm 70.85pt 3.0cm;
            mso-header-margin: 36.0pt;
            mso-footer-margin: 36.0pt;
            mso-paper-source: 0;
        }

        div.WordSection1 {
            page: WordSection1;
        }

        -->
    </style>
    <!--[if gte mso 10]>
<style>
 /* Style Definitions */
 table.MsoNormalTable
    {mso-style-name:"Tabla normal";
    mso-tstyle-rowband-size:0;
    mso-tstyle-colband-size:0;
    mso-style-noshow:yes;
    mso-style-priority:99;
    mso-style-parent:"";
    mso-padding-alt:0cm 5.4pt 0cm 5.4pt;
    mso-para-margin:0cm;
    mso-pagination:widow-orphan;
    font-size:10.0pt;
    font-family:"Times New Roman",serif;}
table.MsoTable15Grid1LightAccent3
    {mso-style-name:"Tabla con cuadrícula 1 clara - Énfasis 3";
    mso-tstyle-rowband-size:1;
    mso-tstyle-colband-size:1;
    mso-style-priority:46;
    mso-style-unhide:no;
    border:solid #DBDBDB 1.0pt;
    mso-border-themecolor:accent3;
    mso-border-themetint:102;
    mso-border-alt:solid #DBDBDB .5pt;
    mso-border-themecolor:accent3;
    mso-border-themetint:102;
    mso-padding-alt:0cm 5.4pt 0cm 5.4pt;
    mso-border-insideh:.5pt solid #DBDBDB;
    mso-border-insideh-themecolor:accent3;
    mso-border-insideh-themetint:102;
    mso-border-insidev:.5pt solid #DBDBDB;
    mso-border-insidev-themecolor:accent3;
    mso-border-insidev-themetint:102;
    mso-para-margin:0cm;
    mso-pagination:widow-orphan;
    font-size:10.0pt;
    font-family:"Times New Roman",serif;}
table.MsoTable15Grid1LightAccent3FirstRow
    {mso-style-name:"Tabla con cuadrícula 1 clara - Énfasis 3";
    mso-table-condition:first-row;
    mso-style-priority:46;
    mso-style-unhide:no;
    mso-tstyle-border-bottom:1.5pt solid #C9C9C9;
    mso-tstyle-border-bottom-themecolor:accent3;
    mso-tstyle-border-bottom-themetint:153;
    mso-ansi-font-weight:bold;
    mso-bidi-font-weight:bold;}
table.MsoTable15Grid1LightAccent3LastRow
    {mso-style-name:"Tabla con cuadrícula 1 clara - Énfasis 3";
    mso-table-condition:last-row;
    mso-style-priority:46;
    mso-style-unhide:no;
    mso-tstyle-border-top:.75pt double #C9C9C9;
    mso-tstyle-border-top-themecolor:accent3;
    mso-tstyle-border-top-themetint:153;
    mso-ansi-font-weight:bold;
    mso-bidi-font-weight:bold;}
table.MsoTable15Grid1LightAccent3FirstCol
    {mso-style-name:"Tabla con cuadrícula 1 clara - Énfasis 3";
    mso-table-condition:first-column;
    mso-style-priority:46;
    mso-style-unhide:no;
    mso-ansi-font-weight:bold;
    mso-bidi-font-weight:bold;}
table.MsoTable15Grid1LightAccent3LastCol
    {mso-style-name:"Tabla con cuadrícula 1 clara - Énfasis 3";
    mso-table-condition:last-column;
    mso-style-priority:46;
    mso-style-unhide:no;
    mso-ansi-font-weight:bold;
    mso-bidi-font-weight:bold;}
</style>
</head>

<body lang=ES link="#59C2C9" vlink="#C366EF" style='tab-interval:35.4pt;
word-wrap:break-word'>

    <div class=WordSection1>
        <p class=MsoNormal>
            <o:p>&nbsp;</o:p>
        </p>

        <div>

            <div align=center>

                <table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width="100%" style='width:100.0%;background:#EEEDEC;border-collapse:collapse;mso-yfti-tbllook:
 1184;mso-padding-alt:0cm 0cm 0cm 0cm'>
                    <tr style='mso-yfti-irow:0;mso-yfti-firstrow:yes;mso-yfti-lastrow:yes'>
                        <td width="100%" valign=top style='width:100.0%;padding:7.5pt 7.5pt 7.5pt 7.5pt'>
                            <div align=center>
                                <table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width=618 style='width:463.5pt;border-collapse:collapse;mso-yfti-tbllook:1184;
   mso-padding-alt:0cm 0cm 0cm 0cm'>
                                    <tr style='mso-yfti-irow:0;mso-yfti-firstrow:yes;mso-yfti-lastrow:yes'>
                                        <td width=618 valign=top style='width:463.5pt;padding:0cm 0cm 0cm 0cm'>
                                            <p class=MsoNormal>&nbsp;<o:p></o:p>
                                            </p>
                                            <div align=center>
                                                <table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 style='max-width:487.5pt;border-collapse:collapse;mso-yfti-tbllook:1184;
     mso-padding-alt:0cm 0cm 0cm 0cm'>
                                                    <tr style='mso-yfti-irow:0;mso-yfti-firstrow:yes'>
                                                        <td valign=top style='background:#EEEDEC;padding:6.75pt 0cm 6.75pt 0cm'></td>
                                                    </tr>
                                                    <tr style='mso-yfti-irow:1'>
                                                        <td valign=top style='background:white;padding:0cm 0cm 0cm 0cm' id=templateHeader>
                                                            <table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width="100%" style='width:100.0%;border-collapse:collapse;mso-yfti-tbllook:
       1184;mso-padding-alt:0cm 0cm 0cm 0cm'>
                                                                <tr style='mso-yfti-irow:0;mso-yfti-firstrow:yes;mso-yfti-lastrow:yes'>
                                                                    <td valign=top style='padding:0cm 0cm 0cm 0cm'>
                                                                        <table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 style='border-collapse:collapse;mso-yfti-tbllook:1184;mso-padding-alt:
         0cm 0cm 0cm 0cm'>
                                                                            <tr style='mso-yfti-irow:0;mso-yfti-firstrow:yes;mso-yfti-lastrow:
          yes'>
                                                                                <td valign=top style='padding:0cm 0cm 0cm 0cm'>
                                                                                    <p class=MsoNormal align=center style='text-align:center'><span style='mso-no-proof:yes'><img width=650 height=188 id="_x0000_i1025" src="https://bxbucket.blob.core.windows.net/bxbucket/resources/mail/ciso/cabecera-11cert-2023.JPG" alt="Offsite CDO 2022"></span>
                                                                                        <o:p></o:p>
                                                                                    </p>
                                                                                </td>
                                                                            </tr>
                                                                        </table>
                                                                    </td>
                                                                </tr>
                                                            </table>
                                                        </td>
                                                    </tr>
                                                    <tr style='mso-yfti-irow:2'>
                                                        <td valign=top style='border:none;border-bottom:solid #EAEAEA 1.5pt;
      background:white;padding:0cm 0cm 6.75pt 0cm' id=templateBody>
                                                            <table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width="100%" style='width:100.0%;border-collapse:collapse;mso-yfti-tbllook:
       1184;mso-padding-alt:0cm 0cm 0cm 0cm;min-width:100%'>
                                                                <tr style='mso-yfti-irow:0;mso-yfti-firstrow:yes;mso-yfti-lastrow:yes'>
                                                                    <td valign=top style='padding:6.75pt 0cm 0cm 0cm;min-width:100%'>
                                                                        <table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 align=left width="100%" style='width:100.0%;border-collapse:collapse;
         mso-yfti-tbllook:1184;mso-table-lspace:2.25pt;mso-table-rspace:2.25pt;
         mso-table-anchor-vertical:paragraph;mso-table-anchor-horizontal:column;
         mso-table-left:left;mso-padding-alt:0cm 0cm 0cm 0cm;min-width:100%'>
                                                                            <tr style='mso-yfti-irow:0;mso-yfti-firstrow:yes;mso-yfti-lastrow:
          yes'>
                                                                                <td width=600 valign=top style='width:450.0pt;padding:0cm 0cm 0cm 0cm;
          min-width:100%'>
                                                                                    <table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 align=left width="100%" style='width:100.0%;border-collapse:collapse;
           mso-yfti-tbllook:1184;mso-table-lspace:2.25pt;mso-table-rspace:2.25pt;
           mso-table-anchor-vertical:paragraph;mso-table-anchor-horizontal:
           column;mso-table-left:left;mso-padding-alt:0cm 0cm 0cm 0cm;
           min-width:100%'>
                                                                                        <tr style='mso-yfti-irow:0;mso-yfti-firstrow:yes;mso-yfti-lastrow:
            yes'>
                                                                                            <td width="100%" valign=top style='width:100.0%;padding:15.0pt 30.0pt 6.75pt 30.0pt;
            min-width:100%'>
                                                                                                <p class=MsoNormal style='line-height:150%'><span style='color:
            #414B61'>Estimado usuario,<o:p></o:p></span></p>
                                                                                                <p class=MsoNormal style='line-height:150%'><span style='color:
            #414B61'>
                                                                                                        <o:p>&nbsp;</o:p>
                                                                                                    </span></p>
                                                                                                <p class=MsoNormal style='line-height:150%'><span style='color:#414B61'>Te informamos de que este es un <b>mensaje automático</b>
                                                                                                        enviado desde la herramienta <b>11CERT.</b>
                                                                                                        <o:p></o:p>
                                                                                                    </span></p>
                                                                                                <p class=MsoNormal style='line-height:150%'><span style='color:
            #414B61'>Se le ha creado un nuevo usuario en la herramienta https://11certools.d-consumer.com/<o:p></o:p></span></p>
                                                                                                <p class=MsoNormal style='line-height:150%'>
                                                                                                    <o:p>&nbsp;</o:p>
                                                                                                </p>
                                                                                                <p class=MsoNormal style='line-height:150%'><span style='color:
            #414B61'>Usuario: {email}<o:p></o:p></span></p>
                                                                                                <p class=MsoNormal style='line-height:150%'>
                                                                                                    <o:p>&nbsp;</o:p>
                                                                                                </p>
<p class=MsoNormal style='line-height:150%'><span style='color:
            #414B61'>Contraseña: {password}<o:p></o:p></span></p>
                                                                                                            <p class=MsoNormal style='line-height:150%'>
                                                                                                    <o:p>&nbsp;</o:p>
                                                                                                </p>
<p class=MsoNormal style='line-height:150%'><span style='color:
            #414B61'>Se le ha creado un usuario local. El login con O365 está reservado a cuentas @telefonica.com.<o:p></o:p></span></p>
                                                                                                            <p class=MsoNormal style='line-height:150%'>
                                                                                                    <o:p>&nbsp;</o:p>
                                                                                                </p>
<p class=MsoNormal style='line-height:150%'><span style='color:
            #414B61'>Si tiene algún problema con la herramienta contacte con el administrador (raul.llamasyanez@telefonica.com).<o:p></o:p></span></p>
                                                                                                <p class=MsoNormal style='line-height:150%'><span style='font-size:
            10.5pt;line-height:150%;color:#414B61;display:none;mso-hide:all'>&nbsp;</span>
                                                                                                    <o:p></o:p>
                                                                                                </p>
                                                                                                <table class=MsoTable15Grid1LightAccent3 border=0 cellspacing=0 cellpadding=0 align=left width="100%" style='width:100.0%;
             border-collapse:collapse;border:none;mso-yfti-tbllook:1184;
             mso-table-lspace:2.25pt;mso-table-rspace:2.25pt;mso-table-anchor-vertical:
             paragraph;mso-table-anchor-horizontal:column;mso-table-left:left;
             mso-padding-alt:0cm 5.4pt 0cm 5.4pt;mso-border-insideh:none;
             mso-border-insidev:none;max-width:100%;min-width:100%'>
                                                                                                    <tr style='mso-yfti-irow:-1;mso-yfti-firstrow:yes;mso-yfti-lastfirstrow:
              yes;mso-yfti-lastrow:yes'>
                                                                                                        <td valign=top style='border:none;border-bottom:solid #C9C9C9 1.5pt;
              mso-border-bottom-themecolor:accent3;mso-border-bottom-themetint:
              153;padding:0cm 5.4pt 0cm 5.4pt'>
                                                                                                            <p class=MsoNormal style='margin-bottom:12.0pt;line-height:150%;
              mso-yfti-cnfc:5'><span style='font-size:10.5pt;line-height:150%;
              color:#414B61'>Recuerda que estamos a tu disposición y<b> </b></span><b><span style='color:#414B61'>puedes</span></b><span style='color:#414B61'>
                                                                                                                    <b>contactar con nosotros</b></span><b><span style='font-size:
              10.5pt;line-height:150%;color:#414B61'> </span></b><span style='font-size:10.5pt;line-height:150%;color:#414B61'>a través
                                                                                                                    del consultor de 11cert asociado a tu servicio o escribiéndonos
                                                                                                                    al buzón:<b> </b></span><span class=MsoHyperlink><b><a href="mailto:ciso.cdo@telefonica.com">ciso.cdo@telefonica.com</a></b></span><span class=MsoHyperlink><span style='color:windowtext;text-decoration:
              none;text-underline:none'>.</span></span><b>
                                                                                                                    <o:p></o:p>
                                                                                                                </b></p>
                                                                                                            <table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 align=left width="100%" style='width:100.0%;border-collapse:
               collapse;mso-yfti-tbllook:1184;mso-table-lspace:2.25pt;
               mso-table-rspace:2.25pt;mso-table-anchor-vertical:paragraph;
               mso-table-anchor-horizontal:column;mso-table-left:left;
               mso-padding-alt:0cm 0cm 0cm 0cm;max-width:100%;min-width:100%'>
                                                                                                                <tr style='mso-yfti-irow:0;mso-yfti-firstrow:yes;mso-yfti-lastrow:
                yes'>
                                                                                                                    <td width=35 valign=top style='width:26.25pt;padding:0cm 0cm 0cm 0cm'></td>
                                                                                                                    <td valign=top style='padding:0cm 0cm 0cm 0cm'></td>
                                                                                                                </tr>
                                                                                                            </table>
                                                                                                        </td>
                                                                                                    </tr>
                                                                                                </table>
                                                                                                <p class=MsoNormal style='line-height:150%'><span style='font-size:
            10.5pt;line-height:150%;color:#414B61;display:none;mso-hide:all'>&nbsp;</span>
                                                                                                    <o:p></o:p>
                                                                                                </p>
                                                                                                <table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 align=left width="100%" style='width:100.0%;border-collapse:collapse;
             mso-yfti-tbllook:1184;mso-table-lspace:2.25pt;mso-table-rspace:
             2.25pt;mso-table-anchor-vertical:paragraph;mso-table-anchor-horizontal:
             column;mso-table-left:left;mso-padding-alt:0cm 0cm 0cm 0cm;
             max-width:100%;min-width:100%'>
                                                                                                    <tr style='mso-yfti-irow:0;mso-yfti-firstrow:yes'>
                                                                                                        <td style='padding:0cm 0cm 0cm 0cm'>
                                                                                                            <p class=MsoNormal align=center style='margin-bottom:7.5pt;
              text-align:center;line-height:150%'><strong><span style='font-size:10.5pt;line-height:150%;font-family:"Arial",sans-serif;
              color:#0066FF'>La seguridad es responsabilidad de tod@s.
                                                                                                                        ¡Contamos contigo!</span></strong>
                                                                                                                <o:p></o:p>
                                                                                                            </p>
                                                                                                            <p class=MsoNormal align=center style='margin-bottom:7.5pt;
              text-align:center;line-height:150%'><span style='color:#414B61'>Dirección
                                                                                                                    CISO de CDO</span>
                                                                                                                <o:p></o:p>
                                                                                                            </p>
                                                                                                        </td>
                                                                                                    </tr>
                                                                                                    <tr style='mso-yfti-irow:1;mso-yfti-lastrow:yes'>
                                                                                                        <td style='padding:0cm 0cm 0cm 0cm'></td>
                                                                                                    </tr>
                                                                                                </table>
                                                                                                <p class=MsoNormal><span style='font-size:10.0pt;font-family:"Times New Roman",serif;
            mso-fareast-font-family:"Times New Roman"'>
                                                                                                        <o:p></o:p>
                                                                                                    </span></p>
                                                                                            </td>
                                                                                        </tr>
                                                                                    </table>
                                                                                </td>
                                                                            </tr>
                                                                        </table>
                                                                    </td>
                                                                </tr>
                                                            </table>
                                                        </td>
                                                    </tr>
                                                    <tr style='mso-yfti-irow:3;mso-yfti-lastrow:yes'>
                                                        <td valign=top style='padding:6.75pt 0cm 6.75pt 0cm' id=templateFooter>
                                                            <table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width="100%" style='width:100.0%;border-collapse:collapse;mso-yfti-tbllook:
       1184;mso-padding-alt:0cm 0cm 0cm 0cm;min-width:100%'>
                                                                <tr style='mso-yfti-irow:0;mso-yfti-firstrow:yes;mso-yfti-lastrow:yes'>
                                                                    <td valign=top style='padding:6.75pt 6.75pt 6.75pt 6.75pt;min-width:100%'>
                                                                        <div align=center>
                                                                            <table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 width="100%" style='width:100.0%;border-collapse:collapse;mso-yfti-tbllook:
         1184;mso-padding-alt:0cm 0cm 0cm 0cm;min-width:100%'>
                                                                                <tr style='mso-yfti-irow:0;mso-yfti-firstrow:yes;mso-yfti-lastrow:
          yes'>
                                                                                    <td valign=top style='padding:6.75pt 0cm 0cm 0cm;min-width:100%'>
                                                                                        <table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 align=left width="100%" style='width:100.0%;border-collapse:collapse;
           mso-yfti-tbllook:1184;mso-table-lspace:2.25pt;mso-table-rspace:2.25pt;
           mso-table-anchor-vertical:paragraph;mso-table-anchor-horizontal:
           column;mso-table-left:left;mso-padding-alt:0cm 0cm 0cm 0cm;
           min-width:100%'>
                                                                                            <tr style='mso-yfti-irow:0;mso-yfti-firstrow:yes;mso-yfti-lastrow:
            yes'>
                                                                                                <td width=600 valign=top style='width:450.0pt;padding:0cm 0cm 0cm 0cm;
            min-width:100%'>
                                                                                                    <table class=MsoNormalTable border=0 cellspacing=0 cellpadding=0 align=left width="100%" style='width:100.0%;border-collapse:collapse;
             mso-yfti-tbllook:1184;mso-table-lspace:2.25pt;mso-table-rspace:
             2.25pt;mso-table-anchor-vertical:paragraph;mso-table-anchor-horizontal:
             column;mso-table-left:left;mso-padding-alt:0cm 0cm 0cm 0cm;
             min-width:100%'>
                                                                                                        <tr style='mso-yfti-irow:0;mso-yfti-firstrow:yes;mso-yfti-lastrow:
              yes'>
                                                                                                            <td valign=top style='padding:0cm 7.5pt 6.75pt 7.5pt;min-width:100%'>
                                                                                                                <p class=MsoNormal style='margin-bottom:7.5pt;text-align:justify;
              line-height:150%'><span style='font-size:9.0pt;line-height:150%;
              color:#656565'>© 2022 Telefónica Digital España S.L.U. Todos los
                                                                                                                        derechos reservados.</span>
                                                                                                                    <o:p></o:p>
                                                                                                                </p>
                                                                                                                <p class=MsoNormal style='margin-bottom:7.5pt;text-align:justify;
              line-height:150%'><span style='font-size:9.0pt;line-height:150%;
              color:#656565'>Este documento es exclusivamente para uso interno
                                                                                                                        por parte del personal de Telefónica. Ninguna parte del mismo
                                                                                                                        puede circularse, citarse o reproducirse para su distribución
                                                                                                                        externa, ni su contenido puede ser difundido por ningún medio
                                                                                                                        fuera de la compañía. Si usted no es empleado de Telefónica,
                                                                                                                        queda notificado de que la lectura, utilización, divulgación y/o
                                                                                                                        copia sin autorización está prohibida en virtud de la legislación
                                                                                                                        vigente. Si ha recibido este mensaje por error, le rogamos que
                                                                                                                        proceda a su destrucción. El correo electrónico vía Internet no
                                                                                                                        permite asegurar la confidencialidad de los mensajes que se
                                                                                                                        transmiten ni su integridad o correcta recepción. Telefónica no
                                                                                                                        asume ninguna responsabilidad por estas circunstancias.</span>
                                                                                                                    <o:p></o:p>
                                                                                                                </p>
                                                                                                            </td>
                                                                                                        </tr>
                                                                                                    </table>
                                                                                                </td>
                                                                                            </tr>
                                                                                        </table>
                                                                                    </td>
                                                                                </tr>
                                                                            </table>
                                                                        </div>
                                                                    </td>
                                                                </tr>
                                                            </table>
                                                        </td>
                                                    </tr>
                                                </table>
                                            </div>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                        </td>
                    </tr>
                </table>

            </div>

            <p class=MsoNormal align=center style='text-align:center'>&nbsp;<o:p></o:p>
            </p>

            <p class=MsoNormal>&nbsp;<o:p></o:p>
            </p>

        </div>

    </div>

</body>
</html>
