<!DOCTYPE html>
<html lang="es">

<head>
    <title>Detalle Issue</title>
    <?php getheader("Detalle Issue", false) ?>
    <link rel="stylesheet" href="./css/styleEAS.css">
    <link rel="stylesheet" href="./css/styleLoading.css">
    <link rel="stylesheet" href="./css/issueDetail.css">
    <script type="module" src="./js/modules/issueDetailModule.js"></script>

</head>

<body>
    <?php getmenu() ?>
    <div class="container pag-IssueDetail">

        <div class="infoIssue mshide mt-5">
            <div class="row">
                <div class="col-sm">
                    <button class="btn btn-primary btn-volver mshide">Volver</button>
                </div>
                <div class="col-sm d-flex justify-content-end">
                    <button class="btn btn-primary btn-delIssue moduloInfo btn-spacer">Eliminar issue</button>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <h5 class="text-center infoKey mshide">Cargando key...</h5>
                    <h5 class="text-center">
                        <a href="" target="_blank" class="enlaceIssue">Cargando key...</a> /
                        <a href="" target="_blank" class="enlaceClonada">Cargando key...</a>
                    </h5>
                    <h1 class="text-center font-weight-bold infoSummary mb-2">Cargando resumen...</h1>
                    <div class="row mb-3">
                        <div class="col-md-12">
                            <button class="btn btn-primary btn-status btn-closeIssue float-right mshide">Cerrar issue</button>
                            <button class="btn btn-primary btn-status btn-openIssue float-right mshide">Abrir issue</button>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <table class="table table-borderless">
                                <thead>
                                    <tr>
                                        <th>Propiedad</th>
                                        <th>Valor</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td class="titulo">Estado:</td>
                                        <td class="infoEstado">Cargando...</td>
                                    </tr>
                                    <tr>
                                        <td class="titulo">Resolución:</td>
                                        <td class="infoRes">Cargando...</td>
                                    </tr>
                                    <tr>
                                        <td class="titulo">Nivel de seguridad:</td>
                                        <td class="infoNivel">Cargando...</td>
                                    </tr>
                                    <tr>
                                        <td class="titulo">Etiquetas:</td>
                                        <td class="infoTag">Cargando...</td>
                                    </tr>
                                </tbody>
                            </table>
                            <table class="table table-borderless">
                                <thead>
                                    <tr>
                                        <th>Campo</th>
                                        <th>Contenido</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td class="titulo">Descripción:</td>
                                        <td class="infoDesc">Cargando...</td>
                                    </tr>
                                </tbody>
                            </table>
                            <table class="table table-borderless">
                                <thead>
                                    <tr>
                                        <th>Campo</th>
                                        <th>Contenido</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td class="titulo">Evidencias:</td>
                                        <td class="insertEvidence">
                                            <form class="ArchivosForm">
                                                <input type="file" class="form-control-file" id="archivos" name="file[]" multiple>
                                                <div class="btn btn-primary ms-2 btnEnviarArchivos">Enviar</div>
                                            </form>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        <div class="col-md-6">
                            <table class="table table-borderless table-transparent">
                                <thead>
                                    <tr>
                                        <th>Propiedad</th>
                                        <th>Valor</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td class="titulo">Prioridad Ciso:</td>
                                        <td class="infoPrio">Cargando...</td>
                                    </tr>
                                    <tr>
                                        <td class="titulo">Proyecto de area/servicio:</td>
                                        <td class="infoProy">Cargando...</td>
                                    </tr>
                                    <tr>
                                        <td class="titulo">Metodología - Definicion de la vulnerabilidad:</td>
                                        <td class="infoMeto">Cargando...</td>
                                    </tr>
                                    <tr>
                                        <td class="titulo">CVSS:</td>
                                        <td class="infoCVSS">Cargando...</td>
                                    </tr>
                                    <tr>
                                        <td class="titulo">Tipo de vulnerabilidad:</td>
                                        <td class="infoVulne">Cargando...</td>
                                    </tr>
                                    <tr>
                                        <td class="titulo">Tipo de análisis:</td>
                                        <td class="infoAnalysis">Cargando...</td>
                                    </tr>
                                    <tr>
                                        <td class="titulo">Impacto de vulnerabilidad:</td>
                                        <td class="infoImpact">Cargando...</td>
                                    </tr>
                                    <tr>
                                        <td class="titulo">Probabilidad de explotación:</td>
                                        <td class="infoProb">Cargando...</td>
                                    </tr>
                                    <tr>
                                        <td class="titulo">Estado de la vulnerabilidad:</td>
                                        <td class="infoStatus">Cargando...</td>
                                    </tr>
                                    <tr>
                                        <td class="titulo">Alertas reportadas:</td>
                                        <td class="infoReference">Cargando...</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <h4 class="text-center mt-5">Estado de las alertas</h4>
                <div class="col-12">
                    <div class="infoAlertas">
                    </div>
                </div>
            </div>
            <div class="row">
                <h4 class="text-center mt-5">Comentarios</h4>
                <div class="chat-container">
                    <div class="col-12 chat">
                        <div class="card mb-2">
                            <div class="card-header writter">
                                <h6 class="card-title mb-0 escritor">Cargando comentarios...</h6>
                            </div>
                            <div class="card-body">
                                <p class="card-text comentario">Cargando comentarios...</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 input-container d-flex align-items-center">
                        <input type="text" class="form-control flex-grow-1 commentWritter" placeholder="Escribe un mensaje...">
                        <button class="btn btn-primary ms-2 btnEnviarComentario">Enviar</button>
                    </div>
                </div>
            </div>
        </div>

        <div class="tablaIssues mshide">
        </div>

        <div class="moduloInfo mshide">
        </div>
    </div>
    <?php getfooter() ?>
</body>

</html>
