<!DOCTYPE html>
<html lang="es">

<head>
    <title>Reporte KPMS - Métricas</title>
    <?php getheader("Reporte KPMS - Métricas", false) ?>
    <link rel="stylesheet" href="./css/update.css">
    <link rel="stylesheet" href="./css/gestorKpms.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Sortable/1.14.0/Sortable.min.js"></script>
    <link rel="stylesheet" href="./css/styleLoading.css">
</head>

<body class="d-flex flex-column h-100">
    <script type="module" src="./js/kpms/gestorKpms.js"></script>
    <?php getmenu() ?>
    <div class="container">
        <div class="check-login"></div>

        <ul class="nav nav-tabs">
            <li class="nav-item">
                <button class="nav-link active" id="metricas-tab" data-bs-toggle="tab" data-bs-target="#info-kpms-metricas" type="button" role="tab" aria-controls="info-kpms-metricas" aria-selected="true">Métricas</button>
            </li>
            <li class="nav-item">
                <button class="nav-link" id="madurez-tab" data-bs-toggle="tab" data-bs-target="#info-kpms-madurez" type="button" role="tab" aria-controls="info-kpms-madurez" aria-selected="true">Madurez</button>
            </li>
            <li class="nav-item">
                <button class="nav-link" id="csirt-tab" data-bs-toggle="tab" data-bs-target="#info-kpms-csirt" type="button" role="tab" aria-controls="info-kpms-csirt" aria-selected="true">CSIRT</button>
            </li>
            <li class="nav-item">
                <button class="nav-link" id="gestor-tab" data-bs-toggle="tab" data-bs-target="#gestor-kpms" type="button" role="tab" aria-controls="gestor-kpms" aria-selected="true">Gestor KPMs</button>
            </li>
            <li class="nav-item">
                <button class="nav-link" id="reporters-tab" data-bs-toggle="tab" data-bs-target="#reporters-kpms" type="button" role="tab" aria-controls="reporters-kpms" aria-selected="true">Reporters</button>
            </li>
        </ul>


        <div class="toast-container">

        </div>

        <div class="tab-content" id="myTabContent">
            <div class="divtable tab-pane fade show active info-kpms-metricas" id="info-kpms-metricas" role="tabpanel" aria-labelledby="home-tab">
                <table id="table-metricas" class="table table-condensed table-hover table-striped table-11cert mshide">
                    <caption>Listado de KPMS métrica</caption>
                    <thead>
                        <th id='id' data-column-id="id" data-type="numeric" data-identifier="true" data-visible='false'>id</th>
                        <th id='usuario_id' data-column-id="usuario" data-visible='false'>usuario</th>
                        <th id='update' data-column-id="update" data-visible='false'>Update</th>
                        <th id='fecha' data-column-id="fecha">Fecha</th>
                        <th id='reporte' data-column-id="reporte">Reporte</th>
                        <th id='area' data-column-id="area">Área</th>
                        <th id='direccion' data-column-id="unidad">Dirección</th>
                        <th id='cuarto' data-column-id="criticidad">Cuarto</th>
                        <th id='auditoria' data-column-id="prioridad">Auditoria</th>
                        <th id='KPM04' data-column-id="KPM04">KPM04</th>
                        <th id='KPM61' data-column-id="KPM61" data-visible='false'>KPM61</th>
                        <th id='KPM31' data-column-id="KPM31" data-visible='false'>KPM31</th>
                        <th id='KPM06' data-column-id="KPM06" data-visible='false'>KPM06</th>
                        <th id='KPM41' data-column-id="KPM41" data-visible='false'>KPM41</th>
                        <th id='KPM43' data-column-id="KPM43" data-visible='false'>KPM43</th>
                        <th id='KPM55' data-column-id="KPM55" data-visible='false'>KPM55</th>
                        <th id='KPM24' data-column-id="KPM24" data-visible='false'>KPM24</th>
                        <th id='KPM26' data-column-id="KPM26" data-visible='false'>KPM26</th>
                        <th id='KPM01' data-column-id="KPM01" data-visible='false'>KPM01</th>
                        <th id='KPM02' data-column-id="KPM02" data-visible='false'>KPM02</th>
                        <th id='KPM03' data-column-id="KPM03" data-visible='false'>KPM03</th>
                        <th id='KPM28' data-column-id="KPM28" data-visible='false'>KPM28</th>
                        <th id='KPM37' data-column-id="KPM37" data-visible='false'>KPM37</th>
                        <th id='KPM33' data-column-id="KPM33" data-visible='false'>KPM33</th>
                        <th id='KPM12' data-column-id="KPM12" data-visible='false'>KPM12</th>
                        <th id='KPM14' data-column-id="KPM14" data-visible='false'>KPM14</th>
                        <th id='KPM16' data-column-id="KPM16" data-visible='false'>KPM16</th>
                        <th id='KPM18' data-column-id="KPM18" data-visible='false'>KPM18</th>
                        <th id='KPM50' data-column-id="KPM50" data-visible='false'>KPM50</th>
                        <th id='KPM54' data-column-id="KPM54" data-visible='false'>KPM54</th>
                        <th id='KPM05' data-column-id="KPM05" data-visible='false'>KPM05</th>
                        <th id='KPM07' data-column-id="KPM07" data-visible='false'>KPM07</th>
                        <th id='KPM09' data-column-id="KPM09" data-visible='false'>KPM09</th>
                        <th id='KPM11' data-column-id="KPM11" data-visible='false'>KPM11</th>
                        <th id='KPM08' data-column-id="KPM08" data-visible='false'>KPM08</th>
                        <th id='KPM10' data-column-id="KPM10" data-visible='false'>KPM10</th>
                        <th id='KPM13' data-column-id="KPM13" data-visible='false'>KPM13</th>
                        <th id='KPM15' data-column-id="KPM15" data-visible='false'>KPM15</th>
                        <th id='KPM17' data-column-id="KPM17" data-visible='false'>KPM17</th>
                        <th id='KPM19' data-column-id="KPM19" data-visible='false'>KPM19</th>
                        <th id='KPM32' data-column-id="KPM32" data-visible='false'>KPM32</th>
                        <th id='KPM20' data-column-id="KPM20" data-visible='false'>KPM20</th>
                        <th id='KPM22' data-column-id="KPM22" data-visible='false'>KPM22</th>
                        <th id='KPM25' data-column-id="KPM25" data-visible='false'>KPM25</th>
                        <th id='KPM27' data-column-id="KPM27" data-visible='false'>KPM27</th>
                        <th id='KPM21' data-column-id="KPM21" data-visible='false'>KPM21</th>
                        <th id='KPM23' data-column-id="KPM23" data-visible='false'>KPM23</th>
                        <th id='KPM29' data-column-id="KPM29" data-visible='false'>KPM29</th>
                        <th id='KPM30' data-column-id="KPM30" data-visible='false'>KPM30</th>
                        <th id='KPM34' data-column-id="KPM34" data-visible='false'>KPM34</th>
                        <th id='KPM35' data-column-id="KPM35" data-visible='false'>KPM35</th>
                        <th id='KPM36' data-column-id="KPM36" data-visible='false'>KPM36</th>
                        <th id='KPM38' data-column-id="KPM38" data-visible='false'>KPM38</th>
                        <th id='KPM39' data-column-id="KPM39" data-visible='false'>KPM39</th>
                        <th id='KPM40' data-column-id="KPM40" data-visible='false'>KPM40</th>
                        <th id='KPM42' data-column-id="KPM42" data-visible='false'>KPM42</th>
                        <th id='KPM44' data-column-id="KPM44" data-visible='false'>KPM44</th>
                        <th id='KPM46' data-column-id="KPM46" data-visible='false'>KPM46</th>
                        <th id='KPM47' data-column-id="KPM47" data-visible='false'>KPM47</th>
                        <th id='KPM71' data-column-id="KPM71" data-visible='false'>KPM71</th>
                        <th id='KPM48' data-column-id="KPM48" data-visible='false'>KPM48</th>
                        <th id='KPM51' data-column-id="KPM51" data-visible='false'>KPM51</th>
                        <th id='KPM52' data-column-id="KPM52" data-visible='false'>KPM52</th>
                        <th id='KPM56' data-column-id="KPM56" data-visible='false'>KPM56</th>
                        <th id='KPM57' data-column-id="KPM57" data-visible='false'>KPM57</th>
                        <th id='KPM53' data-column-id="KPM53" data-visible='false'>KPM53</th>
                        <th id='KPM58' data-column-id="KPM58" data-visible='false'>KPM58</th>
                        <th id='KPM59A' data-column-id="KPM59A" data-visible='false'>KPM59A</th>
                        <th id='KPM59B' data-column-id="KPM59B" data-visible='false'>KPM59B</th>
                        <th id='KPM60A' data-column-id="KPM60A" data-visible='false'>KPM60A</th>
                        <th id='KPM60B' data-column-id="KPM60B" data-visible='false'>KPM60B</th>
                        <th id='KPM62' data-column-id="KPM62" data-visible='false'>KPM62</th>
                        <th id='KPM63' data-column-id="KPM63" data-visible='false'>KPM63</th>
                        <th id='KPM64' data-column-id="KPM64" data-visible='false'>KPM64</th>
                        <th id='KPM70' data-column-id="KPM70" data-visible='false'>KPM70</th>
                        <th id='KPM72' data-column-id="KPM72" data-visible='false'>KPM72</th>
                        <th id='KPM73' data-column-id="KPM73" data-visible='false'>KPM73</th>
                        <th id='KPM73_1' data-column-id="KPM73_1" data-visible='false'>KPM73_1</th>
                        <th id='KPM73_2' data-column-id="KPM73_2" data-visible='false'>KPM73_2</th>
                        <th id='KPM73_3' data-column-id="KPM73_3" data-visible='false'>KPM73_3</th>
                        <th id='KPM73_4' data-column-id="KPM73_4" data-visible='false'>KPM73_4</th>
                        <th id='KPM74' data-column-id="KPM74" data-visible='false'>KPM74</th>
                        <th id='comentario' data-column-id="comentario" data-visible='false'>comentario</th>
                        <th id='sugerencia' data-column-id="sugerencia" data-visible='false'>sugerencia</th>
                        <th id='bloqueado' data-column-id="bloqueado" data-visible='false'>bloqueado</th>
                        <th data-column-id="commands" data-formatter="commands" data-sortable="false">Acciones</th>
                    </thead>
                    <tbody id='table-metrica-data'>
                    </tbody>
                </table>
            </div>
            <div class="divtable tab-pane fade show info-kpms-madurez" id="info-kpms-madurez" role="tabpanel" aria-labelledby="home-tab">
                <table id="table-madurez" class="mshide table table-condensed table-hover table-striped table-11cert">
                    <caption>Listado de KPMS madurez</caption>
                    <thead>
                        <th id='id' data-column-id="id" data-type="numeric" data-identifier="true" data-visible='false'>id</th>
                        <th id='usuario_id' data-column-id="usuario" data-visible='false'>usuario</th>
                        <th id='fecha' data-column-id="fecha">Fecha</th>
                        <th id='reporte' data-column-id="reporte">Reporte</th>
                        <th id='area' data-column-id="area">Área</th>
                        <th id='direccion' data-column-id="unidad">Dirección</th>
                        <th id='cuarto' data-column-id="criticidad">Cuarto</th>
                        <th id='auditoria' data-column-id="prioridad">Auditoria</th>
                        <th id='M01_1' data-column-id="M01_1">M01_1</th>
                        <th id='M01_2' data-column-id="M01_2" data-visible='false'>M01_2</th>
                        <th id='M01_3' data-column-id="M01_3" data-visible='false'>M01_3</th>
                        <th id='M02_1' data-column-id="M02_1" data-visible='false'>M02_1</th>
                        <th id='M02_2' data-column-id="M02_2" data-visible='false'>M02_2</th>
                        <th id='M02_3' data-column-id="M02_3" data-visible='false'>M02_3</th>
                        <th id='M03_1' data-column-id="M03_1" data-visible='false'>M03_1</th>
                        <th id='M03_2' data-column-id="M03_2" data-visible='false'>M03_2</th>
                        <th id='M03_3' data-column-id="M03_3" data-visible='false'>M03_3</th>
                        <th id='M03_4' data-column-id="M03_4" data-visible='false'>M03_4</th>
                        <th id='M04_1' data-column-id="M04_1" data-visible='false'>M04_1</th>
                        <th id='M04_2' data-column-id="M04_2" data-visible='false'>M04_2</th>
                        <th id='M04_3' data-column-id="M04_3" data-visible='false'>M04_3</th>
                        <th id='M04_4' data-column-id="M04_4" data-visible='false'>M04_4</th>
                        <th id='M05_1' data-column-id="M05_1" data-visible='false'>M05_1</th>
                        <th id='M05_2' data-column-id="M05_2" data-visible='false'>M05_2</th>
                        <th id='M06_1' data-column-id="M06_1" data-visible='false'>M06_1</th>
                        <th id='M06_2' data-column-id="M06_2" data-visible='false'>M06_2</th>
                        <th id='M06_7' data-column-id="M06_7" data-visible='false'>M06_7</th>
                        <th id='M07_1' data-column-id="M07_1" data-visible='false'>M07_1</th>
                        <th id='M07_2' data-column-id="M07_2" data-visible='false'>M07_2</th>
                        <th id='M07_3' data-column-id="M07_3" data-visible='false'>M07_3</th>
                        <th id='M08_1' data-column-id="M08_1" data-visible='false'>M08_1</th>
                        <th id='M08_2' data-column-id="M08_2" data-visible='false'>M08_2</th>
                        <th id='M09_1' data-column-id="M09_1" data-visible='false'>M09_1</th>
                        <th id='M09_2' data-column-id="M09_2" data-visible='false'>M09_2</th>
                        <th id='M09_3' data-column-id="M09_3" data-visible='false'>M09_3</th>
                        <th id='M10_1' data-column-id="M10_1" data-visible='false'>M10_1</th>
                        <th id='M10_2' data-column-id="M10_2" data-visible='false'>M10_2</th>
                        <th id='M10_3' data-column-id="M10_3" data-visible='false'>M10_3</th>
                        <th id='M11_1' data-column-id="M11_1" data-visible='false'>M11_1</th>
                        <th id='M11_2' data-column-id="M11_2" data-visible='false'>M11_2</th>
                        <th id='M11_3' data-column-id="M11_3" data-visible='false'>M11_3</th>
                        <th id='M11_4' data-column-id="M11_4" data-visible='false'>M11_4</th>
                        <th id='M12_1' data-column-id="M12_1" data-visible='false'>M12_1</th>
                        <th id='M12_2' data-column-id="M12_2" data-visible='false'>M12_2</th>
                        <th id='M12_3' data-column-id="M12_3" data-visible='false'>M12_3</th>
                        <th id='M12_4' data-column-id="M12_4" data-visible='false'>M12_4</th>
                        <th id='M13_1' data-column-id="M13_1" data-visible='false'>M13_1</th>
                        <th id='M13_2' data-column-id="M13_2" data-visible='false'>M13_2</th>
                        <th id='M13_3' data-column-id="M13_3" data-visible='false'>M13_3</th>
                        <th id='M13_4' data-column-id="M13_4" data-visible='false'>M13_4</th>
                        <th id='M14_1' data-column-id="M14_1" data-visible='false'>M14_1</th>
                        <th id='M14_2' data-column-id="M14_2" data-visible='false'>M14_2</th>
                        <th id='M14_3' data-column-id="M14_3" data-visible='false'>M14_3</th>
                        <th id='comentario' data-column-id="comentario" data-visible='false'>comentario</th>
                        <th id='sugerencia' data-column-id="sugerencia" data-visible='false'>sugerencia</th>
                        <th id='bloqueado' data-column-id="bloqueado" data-visible='false'>bloqueado</th>
                        <th data-column-id="commands" data-formatter="commands" data-sortable="false">Acciones</th>
                    </thead>
                    <tbody id='table-madurez-data'>
                    </tbody>
                </table>
            </div>
            <div class="divtable tab-pane fade show info-kpms-csirt" id="info-kpms-csirt" role="tabpanel" aria-labelledby="home-tab">
                <table id="table-metricas-csirt" class="table table-condensed table-hover table-striped table-11cert">
                    <caption>Listado de KPMS métrica</caption>
                    <thead>
                        <th data-column-id="id" data-header-css-class="IDCol" id="id" data-identifier="true">id</th>
                        <th id='usuario_id' data-column-id="usuario_id" data-visible='false'>usuario</th>
                        <th id='fecha' data-type="date" data-column-id="fecha">Fecha</th>
                        <th id='actualizado' data-column-id="actualizado">Actualizado</th>
                        <th id='reporte' data-column-id="reporte">Reporte</th>
                        <th id='area' data-column-id="area">Área</th>
                        <th id='direccion' data-column-id="direccion">Dirección</th>
                        <th id='cuarto' data-column-id="cuarto">Cuarto</th>
                        <th id='KPM48' data-column-id="KPM48">KPM48</th>
                        <th id='KPM50' data-column-id="KPM50" data-visible='false'>KPM50</th>
                        <th id='KPM51' data-column-id="KPM51" data-visible='false'>KPM51</th>
                        <th id='KPM52' data-column-id="KPM52" data-visible='false'>KPM52</th>
                        <th id='KPM58' data-column-id="KPM58" data-visible='false'>KPM58</th>
                        <th id='KPM59A' data-column-id="KPM59A" data-visible='false'>KPM59A</th>
                        <th id='KPM59B' data-column-id="KPM59B" data-visible='false'>KPM59B</th>
                        <th id='KPM60A' data-column-id="KPM60A" data-visible='false'>KPM60A</th>
                        <th id='KPM60B' data-column-id="KPM60B" data-visible='false'>KPM60B</th>
                        <th id='comentario' data-column-id="comentario" data-visible='false'>comentario</th>
                        <th id='sugerencia' data-column-id="sugerencia" data-visible='false'>sugerencia</th>
                        <th id='bloqueado' data-column-id="bloqueado" data-visible='false'>bloqueado</th>
                        <th data-column-id="commands" data-formatter="commands" data-sortable="false" data-visible='true'>Acciones</th>
                    </thead>
                    <tbody id='table-metricas-csirt-data'>
                    </tbody>
                </table>
            </div>
            <div class="row d-flex justify-content-center form-metricas tarjeta mshide">
                <div class="padding-bottom-22">
                    <h3>Reporte KPMS - Métricas</h3>
                    <h5 class="">Instrucciones Generales</h5>
                    <div>
                        Si tiene dudas de como rellenar este formulario, consulte la <a href="https://telefonicacorp.sharepoint.com/:b:/r/sites/SeguridadCDCOKPIs.TMELA/Shared%20Documents/General/KPMS/Indicadores%20de%20seguridad%20digital_v.3.pdf">documentación</a> oficial facilitada desde corporativo.
                    </div>
                </div>
                <form class="col-12 form-metricas">
                    <div class="col-12 formularioKPMs metricas">
                        <div class="tab">
                            <h3>Introducción</h3>
                            <div class="form-group">
                                <label class="control-label" for="reportAs">Reportar como:</label>
                                <select class="form-select-custom reportAs" name="activo" id="reportAs">
                                </select>
                            </div>
                            <div class="form-group">
                                <label class="control-label" for="reportingPeriod">Período que se reporta:</label>
                                <select class="form-select-custom reportingPeriod" name="cuarto">
                                    <option value='q1'>Q1</option>
                                    <option value='q2'>Q2</option>
                                    <option value='q3'>Q3</option>
                                    <option value='q4'>Q4</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label class="control-label" for="questionAudit">¿Este reporte se comunica después de haber sufrido una auditoría de Corporativo?</label>
                                <select class="form-select-custom questionAudit" name="auditoria">
                                    <option value='1'>SI</option>
                                    <option value='0'>NO</option>
                                </select>
                            </div>
                        </div>
                        <div class="cuestionarioFinal tab mshide">
                            <h3>Observaciones</h3>
                            <small>Introduzca aquí todas las observaciones que considere necesarias relacionadas con los valores aportados o los comentarios que encuentre de interés</small>
                            <div class="form-group mb-2">
                                <label for="observaciones-metricas">Observaciones en relación a las metricas aportadas:</label>
                                <textarea id="observaciones-metricas" rows="4" cols="50" class="form-control" maxlength="200" name="comentario"></textarea>
                            </div>
                            <div class="form-group mb-2">
                                <label for="observaciones-sugerencias">Observaciones en relación a comentarios o sugerencias de mejora:</label>
                                <textarea id="observaciones-sugerencias" rows="4" cols="50" class="form-control" maxlength="200" name="sugerencia"></textarea>
                            </div>
                            <div class="form-group mb-2">
                                <label for="fecha-reporte">Fecha del reporte:</label>
                                <input id="fecha-reporte" type="text" class="form-control" name="fecha" readonly>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12 text-right">
                                <button class="btn btn-primary prevBtn" type="button">Atrás</button>
                                <button class="btn btn-primary nextBtn" type="button">Siguiente</button>
                                <button class="btn btn-primary saveBtn mshide" type="button">Enviar</button>
                            </div>
                        </div>
                        <div class="text-center block-step">
                            <span class="step"></span>
                        </div>
                    </div>
                </form>
            </div>
            <div class="row d-flex justify-content-center form-madurez tarjeta mshide">
                <form class="col-12 form-madurez">
                    <div class="col-12 formularioKPMs madurez">
                        <div class="tab">
                            <h3>Reporte KPMS - Madurez 3.0</h3>
                            <p class="pre-line">
                                TODAS LAS RESPUESTAS DEBEN SER VALORES COMPRENDIDOS ENTRE 0 y 5

                                Si tiene que hacer cualquier tipo de observación por favor cumplimente el campo al final del formulario.

                                Nombre
                                Nombre asignado al indicador de madurez

                                Descripción
                                Finalidad del indicador y qué trata de medir, valorar o conocer, incluyendo las actividades que comprende

                                NIVEL 1
                                Descripción de las condiciones necesarias para estar en el NIVEL 1 de madurez.
                                Como norma general, este nivel de madurez implica que las acciones relacionadas con las actividades reseñadas en la
                                descripción se han llevado a cabo alguna vez

                                NIVEL 2
                                Descripción de las condiciones necesarias para estar en el NIVEL 2 de madurez.
                                Como norma general, este nivel de madurez implica que las acciones relacionadas con las actividades reseñadas en la descripción se han llevado a cabo en múltiples ocasiones, pero sin un patrón definido

                                NIVEL 3
                                Descripción de las condiciones necesarias para estar en el NIVEL 3 de madurez.
                                Como norma general, este nivel de madurez implica que las actividades reseñadas en la descripción han sido definidas y reflejadas en un procedimiento, para regular que se lleven a cabo de forma sistemática y con una periodicidad
                                establecida formalmente

                                NIVEL 4
                                Descripción de las condiciones necesarias para estar en el NIVEL 4 de madurez.
                                Como norma general, este nivel de madurez implica que las actividades reseñadas en la descripción y en el procedimiento documentado según condiciones del NIVEL 3, se llevan a cabo y se establecen a raíz de ellos métricas e indicadores

                                NIVEL 5
                                Descripción de las condiciones necesarias para estar en el NIVEL 5 de madurez.
                                Como norma general, este nivel de madurez implica que las actividades reseñadas en la descripción y con procedimientos documentados acorde al NIVEL 3, se revisan y se mejoran. Para ello, se analizan los resultados de las métricas e indicadores descritos en el NIVEL 4 y se identifican y se implementan acciones de mejora
                            </p>
                            <h3>Introducción</h3>
                            <div class="form-group">
                                <label class="control-label" for="reportAs">Dirección a la que pertenece el área:</label>
                                <select class="form-select-custom reportAs" name="activo" id="reportAs">
                                </select>
                            </div>
                            <div class="form-group">
                                <label class="control-label" for="reportingPeriod">Periodo que se reporta:</label>
                                <select class="form-select-custom reportingPeriod" name='cuarto'>
                                    <option value='q1'>Q1</option>
                                    <option value='q2'>Q2</option>
                                    <option value='q3'>Q3</option>
                                    <option value='q4'>Q4</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label class="control-label" for="questionAudit">¿Este reporte se emite después de una auditoria desde Corporativo?</label>
                                <select class="form-select-custom questionAudit" name="auditoria">
                                    <option value='1'>SI</option>
                                    <option value='0'>NO</option>
                                </select>
                            </div>
                        </div>
                        <div class="tab mshide">
                            <h3>M01. Nivel de madurez de seguridad en aplicaciones y servicios</h3>
                            <p class="pre-line">
                                NIVEL 1
                                1.  En algunos casos se establecen requisitos de seguridad, y se llevan a cabo análisis de riesgos de manera puntual.
                                2.  Se realizan auditorias de seguridad en los aplicativos o servicios de manera puntual.
                                3.  Se revisan únicamente los errores y las vulnerabilidades mas criticas detectadas en las auditorias, priorizando sobre las aplicaciones y servicios clasificados como críticos.

                                NIVEL 2
                                1.  Se empiezan a definir diferentes fases de un análisis de seguridad en proyectos. En la toma de requisitos, se realizan análisis de riesgos, priorizando sobre los aplicaciones y servicios clasificados como críticos.
                                2.  Se hacen análisis de seguridad de los aplicaciones y servicios críticos y se comienza a llevar a cabo de manera más continua a lo largo del SDLC del proyecto.
                                3.  Se aplican acciones correctivas sobre las aplicaciones y servicios críticos, aplicando criterios de prioridad. Se realiza seguimiento y recertificaciones en aplicaciones y servicios críticos. En los no críticos, se remedian los errores y vulnerabilidades sin llevar a cabo seguimiento.

                                NIVEL 3
                                1.  Existe un procedimiento con el siguiente contenido mínimo:
                                        - Valoración de los proyectos en cuanto a criterios de seguridad.
                                        - Toma de requisitos de seguridad en los proyectos.
                                    Se lleva a cabo las acciones reflejadas en el procedimiento, con las frecuencias y periodicidades establecidas en el mismo, de al menos los siguientes puntos:
                                        - Toma de requisitos, valoración y análisis de riesgos de los proyectos sobre aplicaciones y servicios.
                                        - Criterios de seguridad previo comienzo de los proyectos y a lo largo del ciclo de desarrollo de estos.
                                2.  Existe un procedimiento con el siguiente contenido mínimo:
                                        - Realización de Análisis de riesgos al comienzo de los proyectos y revisión al final del proyecto y en la entrega.
                                    Se lleva a cabo las acciones reflejadas en el procedimiento, con las frecuencias y periodicidades establecidas en el mismo, de al menos los siguientes puntos:
                                        - Aplicación de auditorías y análisis de código fuente, tanto dinámico como estático, de acuerdo con el Reglamento Global de Seguridad en el Ciclo de Vida de Desarrollo.
                                3.  Existe un procedimiento con el siguiente contenido mínimo:
                                        - Realización de Análisis de riesgos al comienzo de los proyectos y revisión al final del proyecto y en la entrega.
                                        - Criterios y metodologías de las auditorias de seguridad, análisis de código sobre aplicaciones y servicios a lo largo del SDLC de acuerdo con el Reglamento Global de Seguridad en el Ciclo de Vida de Desarrollo [Ref. 3].
                                    Se lleva a cabo las acciones reflejadas en el procedimiento, con las frecuencias y periodicidades establecidas en el mismo, de al menos los siguientes puntos:
                                        - Acciones correctivas y de mejora sobre vulnerabilidades detectadas durante el desarrollo o el despliegue de proyectos de implantación y otros. Contacto y comunicación entre equipos implicados en la gestión de los proyectos.

                                NIVEL 4
                                1.  Se aplica las fases de un análisis de seguridad en proyectos, de manera detallada y más precisa. Se hacen análisis de riesgos de seguridad de los proyectos y de los más importantes se aprovecha el conocimiento para introducirlo en la mecánica del equipo. Se aplican medidas y controles de seguridad basado en prácticas recomendadas según procedimiento anterior.
                                2.  Se llevan a cabo auditorias de seguridad y seguimiento sobre los fallos o riesgos de seguridad detectados. 
                                3.  Se realizan revisiones periódicas sobre el producto entregado (aplicación o servicio o ambos) con respecto al cumplimiento de los criterios de seguridad establecidos, revisión de análisis de riesgos de seguridad y seguimiento de los resultados de las auditorias y medidas aplicadas para solventar errores y vulnerabilidades.

                                NIVEL 5
                                1.  L5 Se realizan informes para la alta dirección presentando el estado de los proyectos, estadios, hitos, etc. Se analizan los resultados de las medicaciones realizadas sobre este requisito en el nivel 4.
                                2.  Se aplican herramientas para el seguimiento de fallos de seguridad, se hacen uso de herramientas de revisión de código y se implementan módulos adicionales que permiten un análisis de código más eficiente. Se controlan las vulnerabilidades a través de herramientas a la par que se aplican mejoras en la gestión de estas, siempre en línea con el procedimiento. Se analizan los resultados de las medicaciones realizadas sobre este requisito en el nivel 4.
                                3.  Se revisan periódicamente los productos o servicios entregados, revisando los criterios y añadiendo mejoras o más requisitos de seguridad para siguientes revisiones y recertificaciones de las aplicaciones y servicios.
                            </p>
                            <div class="form-group">
                                <label for="M01_1">Análisis y definición de requisitos de Seguridad ( AARR )( este dato sera informado por el área CISO )</label>
                                <select class="form-select-custom" name="M01_1" id="M01_1">
                                    <option value='0'>No Aplica</option>
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='3'>3</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="M01_2">Análisis técnico de seguridad ( auditorias pentesting revision de código )( este dato sera informado por el área CISO )</label>
                                <select class=" form-select-custom" name="M01_2" id="M01_2">
                                    <option value='0'>No Aplica</option>
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='3'>3</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="M01_3">Seguimiento y revision del cumplimiento de los requisitos de seguridad ( este dato se informado por el area CISO )</label>
                                <select class="form-select-custom" name="M01_3" id="M01_3">
                                    <option value='0'>No Aplica</option>
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='3'>3</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                </select>
                            </div>
                        </div>
                        <div class="tab mshide">
                            <h3>M02 Nivel de madurez de gestión de identidad de los usuarios</h3>
                            <p class="pre-line">
                                NIVEL 1
                                1. El criterio de estandarización de identidades es variable, en función del área que lleva a cabo la acción en cada momento.
                                2. Se revisan sin periodicidad establecida las cuentas y sus permisos. Existe personal que lleva a cabo esta tarea, pero no de manera sistemática.
                                3. Se aplican algunas medidas de protección sobre las identidades y cuentas de usuarios privilegiados, de manera casual.

                                NIVEL 2
                                1. Se establece una estandarización de identidades en la denominación de cuentas, usando patrones específicos en la nomenclatura del identificador.
                                2. Se revisan con cierta periodicidad las cuentas y sus permisos. El mantenimiento de cuentas y permisos se lleva a cabo a petición de los interesados o las áreas. La recertificación de usuarios es manual. Existe personal que lleva a cabo estas tareas, pero la periodicidad no está formalizada.
                                3. Se aplican medidas de protección sobre las identidades y cuentas de usuarios, de manera más concreta y considerando determinados criterios específicos de seguridad reflejados en el Reglamento Global de Control de Acceso.

                                NIVEL 3
                                1. Existe un procedimiento con el siguiente contenido mínimo:
                                a. Procesos de gestión de la identidad y el alta, modificación y baja de los usuarios en los activos (aplicaciones, sistemas, etc.).
                                b. Modelo de roles IT y procedimientos de cómo aplicarlo.
                                c. Tareas, roles y responsabilidades del equipo a cargo de estas tareas.
                                d. Procedimiento de revisiones o recertificaciones de identidades con periodicidad establecida formalmente.
                                e. Auditorías de los procesos de gestión de identidad y accesos de los usuarios con periodicidad establecida formalmente.
                                f. Medidas de seguridad y protección sobre identidades y cuentas.
                                2. Se aplican las acciones de revisión y recertificación sobre las identidades y cuentas de usuarios conforme al procedimiento anterior.

                                NIVEL 4
                                1. La estandarización de identidades es plena y regulada. Se aplica la estandarización en el aprovisionamiento de identidades de acuerdo con el procedimiento establecido. El modelo de roles IT se aplica con plenitud. Se valora a través de métricas e indicadores que aportan datos acerca del grado de estandarización de identidades y alcance a la mayoría de los sistemas.
                                2. Se realizan recertificaciones automatizas y manuales en los casos en que no sea viable aplicarlo de manera automática. Se realizan revisiones o auditorías periódicas de los procesos de gestión de identidad y accesos de los usuarios en los activos conforme al procedimiento anterior. Existe un equipo de personas que realizan estas acciones de manera sistemática y con la frecuencia conforme al procedimiento anterior. Existen indicadores y KPI que analizan y miden la mayoría de las condiciones aquí reseñadas.
                                3. Se aplican medidas de seguridad y protección de manera sistemática y sobre identidades y cuentas conforme al procedimiento anterior. Existen indicadores y KPI que analizan y miden la mayoría de las condiciones aquí reseñadas.

                                NIVEL 5
                                1. Se revisa el cumplimiento de los criterios de estandarización de identidades, a través de las métricas e indicadores. Se aplican acciones correctivas en caso de desviaciones.
                                2. Se comprueba mediante las métricas e indicadores que la recertificación se está llevando a cabo, sin discrepancias y errores. Se implanta en aquellos sistemas donde sea viable una herramienta de IAM para automatizar el proceso de gestión de identidad y acceso.
                                3. Se realizan revisiones o auditorías periódicas de los procesos de gestión de identidad y accesos de los usuarios en los activos conforme al procedimiento anterior. Se revisan las medidas de seguridad y protección sobre identidades y cuentas de manera periódica y sistemática. Se valoran los resultados de los indicadores a este respecto para aplicar mejoras y automatizar ciertas revisiones siempre que sea viable.
                            </p>
                            <div class="form-group">
                                <label for="M02_1">Estandarización de Identidades:</label>
                                <select class="form-select-custom" name="M02_1" id="M02_1">
                                    <option value='0'>No Aplica</option>
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='3'>3</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="M02_2">Mantenimiento de cuentas y permisos de acceso:</label>
                                <select class="form-select-custom" name="M02_2" id="M02_2">
                                    <option value='0'>No Aplica</option>
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='3'>3</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="M02_3">Medidas de protección sobre identidades y cuentas:</label>
                                <select class="form-select-custom" name="M02_3" id="M02_3">
                                    <option value='0'>No Aplica</option>
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='3'>3</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                </select>
                            </div>
                        </div>
                        <div class="tab mshide">
                            <h3>M03 Nivel de madurez control usuarios privilegiados en sistemas</h3>
                            <p class="pre-line">
                                NIVEL 1
                                1. El criterio de estandarización de identidades es variable, en función del área que lleva a cabo la acción en cada momento.
                                2. Se revisan sin periodicidad establecida las cuentas privilegiadas y sus permisos. Existe personal que lleva a cabo esta tarea, pero no de manera sistemática.
                                3. Se aplican algunas medidas de protección sobre las identidades y cuentas de usuarios privilegiados, de manera casual.
                                4. Existen cuentas de usuario privilegiadas genéricas, compartidas entre grupos de usuarios y no son nominativas. El control y las auditorias sobre los accesos remotos de usuarios privilegiados es laxo, aleatorio y sin periodicidad.

                                NIVEL 2
                                1. Se establece una estandarización de identidades en la denominación de cuentas privilegiadas, usando patrones específicos en la nomenclatura del identificador.
                                2. Se revisan con cierta periodicidad las cuentas privilegiadas y sus permisos. El mantenimiento de cuentas y permisos se lleva a cabo a petición de los interesados o las áreas. La recertificación de usuarios privilegiados es manual. Existe personal que lleva a cabo estas tareas, pero la frecuencia no está formalizada.
                                3. Se aplican medidas de protección sobre las identidades y cuentas privilegiadas, de manera más concreta y considerando determinados criterios específicos de seguridad reflejados en el Reglamento Global de Control de Acceso.
                                4. Se provisionan cuentas de usuario privilegiadas nominativas y se comienza a prescindir de cuentas genéricas. Se planifican revisiones o auditorias periódicas de los procesos de acceso de las cuentas de usuario privilegiadas sobre los activos, de manera no formal.

                                NIVEL 3
                                1. Existe un procedimiento con el siguiente contenido mínimo:
                                a. Procesos de gestión de la identidad y el alta, modificación y baja de los usuarios privilegiados en activos (aplicaciones, sistemas, etc.).
                                b. Modelo de roles administrativos IT y procedimientos de cómo aplicarlo.
                                c. Tareas, roles y responsabilidades.
                                d. Procedimiento de revisiones o recertificaciones de identidades con periodicidad establecida formalmente.
                                e. Auditorías de los procesos de gestión de identidad y accesos de los usuarios privilegiados con periodicidad establecida formalmente.
                                f. Medidas de seguridad y protección sobre identidades y cuentas. Control y auditorias sobre los accesos remotos de usuarios privilegiados.
                                2. Se aplican las acciones de revisión y recertificación sobre las identidades y cuentas de usuarios privilegiados conforme al procedimiento anterior.

                                NIVEL 4
                                1. La estandarización de identidades es plena y regulada. Se aplica la estandarización en el aprovisionamiento de identidades privilegiadas de acuerdo con el procedimiento establecido. El modelo de roles administrativos IT se aplica con plenitud. Se valora a través de métricas e indicadores que aporten datos acerca del grado de estandarización de identidades y alcance a la mayoría de los sistemas.
                                2. Se realizan aprovisionamientos y recertificaciones automatizas principalmente. Se realizan revisiones o auditorías periódicas de los procesos de gestión de identidad y accesos de los usuarios en los activos conforme al procedimiento anterior. Existe un equipo de personas que realizan estas acciones de manera sistemática y con la frecuencia conforme al procedimiento anterior. Existe una integración de la herramienta IAM con la herramienta PIM/PAM para la provisión automática de usuarios.
                                Existen indicadores y KPI que analizan y miden la mayoría de las condiciones aquí reseñadas.
                                3. Se aplican medidas de seguridad y protección de manera sistemática y sobre identidades y cuentas privilegiadas conforme al procedimiento anterior. Existen indicadores y KPI que analizan y miden la mayoría de las condiciones aquí reseñadas.
                                4. Los controles sobre accesos remotos de cuentas privilegiadas se hacen mediante revisiones sistemáticas y periódicas, conforme al procedimiento anterior. Se ha definido e implantado un mecanismo de monitorización de la actividad de usuarios privilegiados
                            </p>
                            <div class="form-group">
                                <label for="M03_1">Estandarización de identidades:</label>
                                <select class="form-select-custom" name="M03_1" id="M03_1">
                                    <option value='0'>No Aplica</option>
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='3'>3</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="M03_2">Mantenimiento de cuentas y permisos de acceso:</label>
                                <select class="form-select-custom" name="M03_2" id="M03_2">
                                    <option value='0'>No Aplica</option>
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='3'>3</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="M03_3">Medidas de protección sobre identidades y cuentas:</label>
                                <select class="form-select-custom" name="M03_3" id="M03_3">
                                    <option value='0'>No Aplica</option>
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='3'>3</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="M03_4">Control y auditorias sobre accesos remotos de usuarios privilegiados:</label>
                                <select class="form-select-custom" name="M03_4" id="M03_4">
                                    <option value='0'>No Aplica</option>
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='3'>3</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                </select>
                            </div>
                        </div>
                        <div class="tab mshide">
                            <h3>M04 Nivel de madurez control usuarios privilegiados en elementos de red</h3>
                            <p class="pre-line">
                                NIVEL 1
                                1. El criterio de estandarización de identidades es variable, en función del área que lleva a cabo la acción en cada momento.
                                2. Se revisan sin periodicidad establecida en las cuentas privilegiadas y sus permisos. Existe personal que lleva a cabo esta tarea, pero no de manera sistemática.
                                3. Se aplican algunas medidas de protección sobre las identidades y cuentas de usuarios privilegiados, de manera casual.
                                4. Existen cuentas de usuario privilegiadas genéricas, compartidas entre grupos de usuarios y no son nominativas. El control y las auditorias sobre los accesos remotos de usuarios privilegiados es laxo, aleatorio y sin periodicidad.

                                NIVEL 2
                                1. Se establece una estandarización de identidades en la denominación de cuentas privilegiadas, usando patrones específicos en la nomenclatura del identificador, entre otras acciones de estandarización.
                                2. Se revisan con cierta periodicidad las cuentas privilegiadas y sus permisos. El mantenimiento de cuentas y permisos se lleva a cabo a petición de los interesados o las áreas. La recertificación de usuarios privilegiados es manual. Existe personal que lleva a cabo estas tareas, pero con una frecuencia no regulada.
                                3. Se aplican medidas de protección sobre las identidades y cuentas privilegiadas, de manera más concreta y considerando determinados criterios específicos de seguridad reflejados en el Reglamento Global de Control de Acceso.
                                4. Se provisionan cuentas de usuario privilegiadas nominativas y se comienzan a prescindir de cuentas genéricas. Se planifican revisiones o auditorias periódicas de los procesos de acceso de las cuentas de usuario privilegiadas sobre los activos, de manera no formal.

                                NIVEL 3
                                1. Existe un procedimiento con el siguiente contenido mínimo:
                                a. Procesos de gestión de la identidad y el alta, modificación y baja de los usuarios privilegiados en elementos de redes.
                                b. Modelo de roles administrativos de Redes y procedimientos de cómo aplicarlo.
                                c. Tareas, roles y responsabilidades.
                                d. Procedimiento de revisiones o recertificaciones de identidades con periodicidad establecida formalmente.
                                e. Auditorías de los procesos de gestión de identidad y accesos de los usuarios privilegiados con periodicidad establecida formalmente.
                                f. Medidas de seguridad y protección sobre identidades y cuentas. Control y auditorias sobre los accesos remotos de usuarios privilegiados.
                                2. Se aplican las acciones de revisión y recertificación sobre las identidades y cuentas de usuarios privilegiados conforme al procedimiento anterior.

                                NIVEL 4
                                1. La estandarización de identidades es plena y regulada. Se aplica la estandarización en el aprovisionamiento de identidades privilegiadas de acuerdo con el procedimiento establecido. El modelo de roles administrativos IT se aplica con plenitud. Se valora a través de métricas e indicadores que aporten datos acerca del grado de estandarización de identidades y alcance a la mayoría de los sistemas.
                                2. Se realizan aprovisionamientos y recertificaciones automáticas principalmente. Se realizan revisiones o auditorías periódicas de los procesos de gestión de identidad y accesos de los usuarios en los elementos de red conforme al procedimiento anterior. Existe un equipo de personas que realizan estas acciones de manera sistemática y con la frecuencia conforme al procedimiento anterior. Existe una integración de la herramienta IAM con la herramienta PIM/PAM para la provisión automática de usuarios.
                                Existen indicadores y KPI que analizan y miden la mayoría de las condiciones aquí reseñadas.
                                3. Se aplican medidas de seguridad y protección de manera sistemática y sobre identidades y cuentas privilegiadas conforme al procedimiento anterior. Existen indicadores y KPI que analizan y miden la mayoría de las condiciones aquí reseñadas.
                                4. Los controles sobre accesos remotos de cuentas privilegiadas se hacen mediante revisiones sistemáticas y periódicas, conforme al procedimiento anterior. Se ha definido e implantado un mecanismo de monitorización de la actividad.
                            </p>
                            <div class="form-group">
                                <label for="M04_1">Estandarización de Identidades:</label>
                                <select class="form-select-custom" name="M04_1" id="M04_1">
                                    <option value='0'>No Aplica</option>
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='3'>3</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="M04_2">Mantenimiento de cuentas y permisos de acceso:</label>
                                <select class="form-select-custom" name="M04_2" id="M04_2">
                                    <option value='0'>No Aplica</option>
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='3'>3</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="M04_3">Medidas de Protección sobre identidades y cuentas:</label>
                                <select class="form-select-custom" name="M04_3" id="M04_3">
                                    <option value='0'>No Aplica</option>
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='3'>3</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="M04_4">Control y Auditorias sobre accesos remotos de usuarios privilegiados:</label>
                                <select class="form-select-custom" name="M04_4" id="M04_4">
                                    <option value='0'>No Aplica</option>
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='3'>3</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                </select>
                            </div>
                        </div>
                        <div class="tab mshide">
                            <h3>M05 Nivel de madurez gestión de inventario y CMDB IT BSS</h3>
                            <p class="pre-line">
                                NIVEL 1
                                1. Existe un inventario de activos de IT y BSS de manera no formal. El inventario dispone de la información básica para la actividad de Seguridad Digital (por ejemplo: responsables, tipo de activo, direcciones IP). La estandarización de datos es irregular y no única, existiendo varios datos no relacionados.
                                2. Se revisa sin periodicidad establecida y a petición de algunas áreas que así lo requieran.

                                NIVEL 2
                                1. Se aplican estándares comunes para recabar datos más esenciales y se nombra roles y responsables del inventario. El inventario dispone de la información básica para la actividad de Seguridad Digital (por ejemplo: responsables, tipo de activo, direcciones IP). Se integran acciones de estandarización de datos.
                                2. Se revisa cada 6 meses o superior y a petición de algunas áreas que así lo requieran o por razones de auditoria. Se realizan tareas de mantenimiento básico y algunas comprobaciones sencillas. Se priorizan los datos de activos críticos.

                                NIVEL 3
                                1. Existe un procedimiento con el siguiente contenido mínimo:
                                a. Estandarización e integridad de datos de inventario de IT y BSS.
                                b. Fuentes de datos para recolección de información de inventario.
                                c. Tareas de gestión y mantenimiento de inventario.
                                d. Auditorias, revisiones y frecuencias de mantenimiento de inventario.
                                2. Se llevan a cabo las acciones y tareas conforme al procedimiento anterior.

                                NIVEL 4
                                1. Se revisa el cumplimiento en materia de estandarización del inventario conforme al procedimiento. Se comienza a integrar los datos en herramienta CMDB y usar la estandarización conforme a lo reflejado en el procedimiento.
                                2. Se revisa que se lleven a cabo las acciones de mantenimiento, gestión, control y chequeo de inventario de IT y BSS conforme al procedimiento. Se establecen métricas e indicadores a efectos de medir la eficacia y efectividad de estas acciones. Se integran datos de activos IT y BSS clasificados como críticos en CMDB y se automatizan algunas tareas de control y gestión.

                                NIVEL 5
                                1. Se establecen planes de mejora para la actualización y una plena estandarización de los datos del inventario del inventario.
                                2. Se analizan los datos aportados por las métricas e indicadores para implementar mejoras en el mantenimiento y gestión de inventarios. Se aplica un mayor alcance del CMDB a todo tipo de activos de IT y BSS. Se llevan a cabo integraciones de las herramientas CMDB con herramientas de ticketing de peticiones/incidencias y gestión del cambio y automatizar tareas.
                            </p>
                            <div class="form-group">
                                <label for="M05_1">Estandarización de inventario:</label>
                                <select class="form-select-custom" name="M05_1" id="M05_1">
                                    <option value='0'>No Aplica</option>
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='3'>3</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="M05_2">Mantenimiento de Inventario:</label>
                                <select class="form-select-custom" name="M05_2" id="M05_2">
                                    <option value='0'>No Aplica</option>
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='3'>3</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                </select>
                            </div>
                        </div>
                        <div class="tab mshide">
                            <h3>M06 Nivel de madurez parcheado y fortificación de servidores y estaciones de trabajo</h3>
                            <p class="pre-line">
                                NIVEL 1
                                1. Se parchean únicamente los servidores y estaciones de trabajo clasificados como críticos. Se aplican los parches más críticos y de manera manual en algunos casos.
                                2. Se bastiona únicamente aquellos servidores clasificados como críticos.

                                NIVEL 2
                                1. Se aplican parches críticos y de corrección de vulnerabilidades. Se aplican estos parches de acuerdo con las recomendaciones del fabricante. Se aplican a un mayor alcance y no únicamente a los clasificados como críticos.
                                2. Se bastionan según criterios de seguridad de fabricante. Este bastionado se lleva a cabo por un orden de criticidad del activo a bastionar.
                                3. Se aplican algunas medidas adicionales de seguridad tales como segmentación y priorización de medidas adicionales sobre los clasificados como servidores críticos y virtualización en el caso que así lo requieran.

                                NIVEL 3
                                1. Existe un procedimiento al menos con la siguiente información y contenido:
                                a. Gestión y control de parcheado. Uso de herramientas, preferiblemente automatizadas, para la aplicación de parches.
                                b. Metodología de actualización. Fases de aplicación de parcheado y actualizaciones, roll-back.
                                c. Metodología y criterios de seguridad para el bastionado.
                                d. Medidas adicionales de seguridad. Control, aplicación y gestión. Auditorias de seguridad para comprobación de aplicación de parches y bastionado.
                                2. Se aplican las acciones de parcheado, bastionado y medidas de seguridad adicionales acorde al procedimiento anterior.

                                NIVEL 4
                                1. Se aplica parcheado mediante herramientas automatizadas. Se contempla las necesidades de hacerlo sobre equipos remotos o no conectados directamente a la red corporativa (teletrabajo). Se implementan mediciones con indicadores para valorar el grado de aplicación de parches, especialmente sobre servidores críticos.
                                2. Se realiza el bastionado de servidores y de estaciones de trabajo, acorde al procedimiento. Se generan indicadores para la medición de la acción del bastionado, para su posterior valoración y aplicación de mejoras.
                                3. Se aplican medidas adicionales tales como revisiones o auditorías periódicas del grado de actualización y bastionado de los servidores y estaciones de trabajo. Se dispone de herramienta EDR desplegada en estaciones de trabajo y servidores Windows (entre el 50% y el 90% de las estaciones de trabajo y servidores).

                                NIVEL 5
                                1. Se dispone de una herramienta para automatizar el proceso de parcheado. Se chequea y audita que se esté llevando a cabo acorde al procedimiento y se analiza mediante los indicadores y métricas.
                                2. Se dispone de herramientas que ayudan a automatizar el bastionado y se realiza comprobación de errores en el caso de servidores críticos. Se audita que este alineado con el procedimiento y se comprueba los datos que aportan los indicadores.
                                3. Se realizan pruebas previas a la instalación de parches muy críticos que puedan afectar a la operatividad de la empresa y al funcionamiento correcto de los servicios. Se dispone de herramienta EDR desplegada en estaciones de trabajo y servidores Windows (más del 90% de las estaciones de trabajo y servidores). Se utilizan Golden Image bastionadas en fase previas al paso a producción. Se implanta procesos devSecOps para el despliegue automático de infraestructura por
                                Software.
                            </p>
                            <div class="form-group">
                                <label for="M06_1">Parcheado:</label>
                                <select class="form-select-custom" name="M06_1" id="M06_1">
                                    <option value='0'>No Aplica</option>
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='3'>3</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="M06_1">Bastionado:</label>
                                <select class="form-select-custom" name="M06_2" id="M06_2">
                                    <option value='0'>No Aplica</option>
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='3'>3</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="M06_7">Medidas adicionales de seguridad:</label>
                                <select class="form-select-custom" name="M06_7" id="M06_7">
                                    <option value='0'>No Aplica</option>
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='3'>3</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                </select>
                            </div>
                        </div>
                        <div class="tab mshide">
                            <h3>M07 Nivel de madurez de fortificación de directorios activos</h3>
                            <p class="pre-line">
                                NIVEL 1
                                1. El diseño lógico se ha hecho e implementado a medida que se necesitaba y sin ningún tipo de estandarización.
                                2. La fortificación de AD se hace únicamente sobre servidores clasificados como críticos, pero no el LDAP para el caso de servidores Unix/Linux.
                                3. Se parchean los servidores con AD, aplicando únicamente con los parches más críticos, de manera manual en algunos casos, y sin criterio establecido.

                                NIVEL 2
                                1. Se comienza a aplicar modelos de estructura lógica, ajustada a las necesidades y la estructura organizativa de la empresa.
                                2. El procedimiento de fortificación contempla los servidores críticos y no críticos con AD. Para ello se aplica el uso de directivas en el caso de datos críticos y para cuentas privilegiadas.
                                3. Se implementa parcheado sobre todos los servidores con AD, así como login scripts.

                                NIVEL 3
                                1. Existe un procedimiento al menos con la siguiente información y contenido:
                                a. Diseño y estructura.
                                b. Controles y medidas de hardening.
                                c. Administración y gestión de identidades y directivas. Mecanismos de autenticación. Roles.
                                d. Metodologías de buenas prácticas (IGDLA).
                                2. La estructura definida de AD esta segmentada. Se revisa cada año que se mantenga de manera correcta acorde al diseño y las necesidades de las áreas y negocio.
                                3. El bastionado de AD contempla uso de directivas y revisión de estas.

                                NIVEL 4
                                1. Se implementan estructuras lógicas avanzadas, con redundancia o virtualización en algunos casos para evitar fallos. Se dispone de Tier 0 de los AD’s. Se diseñan indicadores para la medición y valoración del grado de estructuración de los AD.
                                2. Se dispone de Microsoft ATA o Azure ATP o similar implementado en los directorios. Se aplican indicadores para medir el grado de implantación de estas soluciones.
                                3. Se realiza una monitorización reactiva de las alertas ATA. Se reportan para tomar decisiones a largo plazo, pero sin acciones a corto plazo. Se aplican mecanismos seguros de autenticación. Se dispone de roles FSMO y se gestionan acorde al procedimiento.

                                NIVEL 5
                                1. Se realizan revisiones sobre la estructura lógica y se revisa que se lleven a cabo los cambios acordes al procedimiento. Se dispone de una Arquitectura Tier 1 de los AD’s con estación de trabajo altamente bastionadas y dedicadas, desde donde se realiza la administración.
                                2. Se realizan pruebas del bastionado para comprobar su eficaz mediante ejercicios simulados de ciberataques, que impactan sobre el AD (Golden ticket Kerberos y escalada de privilegios entre otros).
                                3. Se realiza una monitorización proactiva de las alertas ATA, se revisan e implementa mejoras, de acuerdo con la información de los indicadores y de la monitorización.
                            </p>
                            <div class="form-group">
                                <label for="M07_1">Diseño y Estructura:</label>
                                <select class="form-select-custom" name="M07_1" id="M07_1">
                                    <option value='0'>No Aplica</option>
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='3'>3</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="M07_2">Bastionado y Hardening:</label>
                                <select class="form-select-custom" name="M07_2" id="M07_2">
                                    <option value='0'>No Aplica</option>
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='3'>3</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="M07_3">Controles de Seguridad:</label>
                                <select class="form-select-custom" name="M07_3" id="M07_3">
                                    <option value='0'>No Aplica</option>
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='3'>3</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                </select>
                            </div>
                        </div>
                        <div class="tab mshide">
                            <h3>M08 Nivel de madurez gestión de inventario y CMDB redes y OSS</h3>
                            <p class="pre-line">
                                NIVEL 1
                                1. Existe un inventario de activos de redes y OSS de manera no formal. El inventario dispone de la información básica para la actividad de Seguridad Digital (número de serie, responsables, etc.). La estandarización es irregular y no única, existiendo varios datos no relacionados.
                                2. Se revisa sin periodicidad establecida y bajo demanda.

                                NIVEL 2
                                1. Se aplican estándares comunes para recabar datos más esenciales y se nombra roles y responsables del inventario. El inventario dispone de la información básica para la actividad de Seguridad Digital (número de serie, responsables, etc.). Se integran acciones de estandarización de datos.
                                2. Se revisa cada 6 meses o superior y a petición de algunas áreas que así lo requieran o por razones de auditoria. Se realizan tareas de mantenimiento básico y comprobaciones sencillas. Se priorizan los datos de activos críticos.

                                NIVEL 3
                                1. Existe un procedimiento al menos con la siguiente información y contenido:
                                a. Estandarización e integridad de datos de inventario de redes y OSS
                                b. Fuentes de datos para recolección de información de inventario
                                c. Tareas de gestión y mantenimiento de inventario
                                d. Auditorias, revisiones y frecuencias de mantenimiento de inventario.
                                2. Se llevan a cabo las acciones y tareas conforme al procedimiento anterior.

                                NIVEL 4
                                1. Se revisa el cumplimiento en materia de estandarización del inventario conforme al procedimiento. Se comienza a integrar los datos en herramienta CMDB y usar la estandarización conforme a lo reflejado en el procedimiento.
                                2. Se revisa que se lleven a cabo las acciones de mantenimiento, gestión, control y chequeo de inventario de redes y OSS conforme al procedimiento. Se establecen métricas e indicadores a efectos de medir la eficacia y efectividad de estas acciones. Se integran datos de activos de redes y OSS clasificados como críticos en CMDB y se automatizan algunas tareas de control y gestión.

                                NIVEL 5
                                1. Se establecen planes de mejora para la actualización y una plena estandarización de los datos del inventario del inventario.
                                2. Se analizan los datos aportados por las métricas e indicadores para implementar mejoras en el mantenimiento y gestión de inventarios. Se aplica un mayor alcance del CMDB a todo tipo de activos de redes y OSS. Se llevan a cabo integraciones de las herramientas CMDB con herramientas de ticketing de peticiones/incidencias y gestión del cambio y automatizar tareas.
                            </p>
                            <div class="form-group">
                                <label for="M08_1">Estandarización de Inventario:</label>
                                <select class="form-select-custom" name="M08_1" id="M08_1">
                                    <option value='0'>No Aplica</option>
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='3'>3</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="M08_2">Mantenimiento de Inventario:</label>
                                <select class="form-select-custom" name="M08_2" id="M08_2">
                                    <option value='0'>No Aplica</option>
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='3'>3</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                </select>
                            </div>
                        </div>
                        <div class="tab mshide">
                            <h3>M09 Nivel de madurez parcheado y fortificación de elementos de red</h3>
                            <p class="pre-line">
                                NIVEL 1
                                1. Se parchean únicamente aquellos clasificados como críticos. Se aplican los parches más críticos y de manera manual en algunos casos.
                                2. Se bastiona únicamente aquellos clasificados como críticos.

                                NIVEL 2
                                1. Se aplican parches críticos y de corrección de vulnerabilidades. Existe una solución para actualizar los parches los elementos de red de manera automática. Se aplican a un mayor alcance y no únicamente a los clasificados como críticos.
                                2. Los elementos de red se bastionan según criterios de seguridad de fabricante. Este bastionado se lleva a cabo por un orden de criticidad del activo a bastionar.
                                3. Se aplican algunas medidas adicionales de seguridad tales como segmentación y priorización de medidas adicionales sobre los clasificados como elementos de red críticos y virtualización en el caso de elementos de red que así lo
                                requieran.

                                NIVEL 3
                                1. Existe un procedimiento al menos con la siguiente información y contenido:
                                a. Gestión y control de parcheado. Uso de herramientas para aplicación de parches.
                                b. Metodología de actualización de elementos de red. Fases de aplicación de parcheado y actualizaciones, roll-back.
                                c. Metodología y criterios de seguridad para el bastionado.
                                d. Medidas adicionales de seguridad. Control, aplicación y gestión. Auditorias de seguridad para comprobación de aplicación de parches y bastionado.
                                2. Se aplican las acciones de parcheado, bastionado y medidas de seguridad adicionales acorde al procedimiento
                                anterior.

                                NIVEL 4
                                1. Se aplica parcheado mediante herramientas automatizadas. Se contempla las necesidades de hacerlo sobre elementos remotos o no conectados directamente a la red corporativa (teletrabajo). Se implementan mediciones con indicadores para valorar el grado de aplicación de parches, especialmente sobre elementos de red críticos.
                                2. Se realiza el bastionado acorde al procedimiento. Se generan indicadores para la medición de la acción del bastionado, para su posterior valoración y aplicación de mejoras.
                                3. Se aplican medidas adicionales tales revisiones o auditorías periódicas del grado de actualización y bastionado.

                                NIVEL 5
                                1. Se dispone de una herramienta para automatizar el proceso de parcheado. Se chequea y audita que se esté llevando a cabo acorde al procedimiento y se analiza mediante los indicadores y métricas.
                                2. Se dispone de herramientas que ayudan a automatizar el bastionado y se realiza comprobación de errores en el caso de elementos de red críticos. Se audita que este alineado con el procedimiento y se comprueba los datos que aportan los indicadores.
                                3. Se realizan pruebas previas a la instalación de parches muy críticos que puedan afectar a la operatividad de la empresa y al funcionamiento correcto de los servicios. Se implanta procesos devSecOps para el despliegue automático de infraestructura por Software.
                            </p>
                            <div class="form-group">
                                <label for="M09_1">Parcheado:</label>
                                <select class="form-select-custom" name="M09_1" id="M09_1">
                                    <option value='0'>No Aplica</option>
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='3'>3</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="M09_2">Bastionado:</label>
                                <select class="form-select-custom" name="M09_2" id="M09_2">
                                    <option value='0'>No Aplica</option>
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='3'>3</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="M09_3">Medidas Adicionales de Seguridad:</label>
                                <select class="form-select-custom" name="M09_3" id="M09_3">
                                    <option value='0'>No Aplica</option>
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='3'>3</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                </select>
                            </div>
                        </div>
                        <div class="tab mshide">
                            <h3>M10 Nivel de madurez de monitorización de eventos</h3>
                            <p class="pre-line">
                                NIVEL 1
                                1. Alguna vez se ha analizado las fuentes necesarias.
                                2. Existen pocas fuentes integradas. Únicamente aquello valorado como muy crítico.
                                3. Se monitorizan los eventos cuando se reporta alguna anomalía o se recibe algún tipo de notificación. Las alertas se revisan con poca frecuencia.

                                NIVEL 2
                                1. Se analizan e identifican amenazas básicas y las fuentes que se requieren para la monitorización de eventos.
                                2. Existen algunas fuentes integradas. Únicamente aquello valorado como muy crítico.
                                3. Se monitorizan los eventos cuando se reporta alguna anomalía o se recibe algún tipo de notificación. Las alertas se revisan con poca frecuencia.

                                NIVEL 3
                                1. Existe un procedimiento con el siguiente contenido mínimo:
                                a. Análisis y criterios de fuentes a integrar.
                                b. Arquitectura y requisitos de integración.
                                c. Metodología de identificación de amenazas y correlación de eventos.
                                d. Generación de guías de actuación (playbooks) frente la detección de amenazas.
                                e. Monitorización de eventos integrados y gestión de alertas. Equipos y personal de respuesta.
                                2. Se realizan las siguientes acciones acorde al procedimiento:
                                a. Integración de fuentes.
                                b. Análisis de fuentes y de identificación de amenazas. Aplicación de guías de actuación.
                                c. Monitorización continua de eventos. Gestión de alarmas.

                                NIVEL 4
                                1. Se revisan que tanto las fuentes como las amenazas estén configuradas y alineadas según procedimiento. Se automatiza el análisis de fuentes.
                                2. Se chequea la correcta integración de las fuentes, la integridad de la información recibida.
                                3. Se revisan las acciones monitorización. Se configuran las alarmas y notificaciones de estas. Se automatizan determinadas tareas de monitorización. Se generan indicadores para la medición de las notificaciones y alarmas, así como para medir la monitorización.

                                NIVEL 5
                                1. Se miden y valoran las fuentes y amenazas a través de los indicadores. Se aplican mejoras a la hora de integrar fuentes, implantar nuevos sensores y aplicaciones que ayuden a la detección de amenazas.
                                2. Se comprueba la integración adecuada de fuentes y se aplican mejoras que permitan detectar aquellas fuentes que puedan sufrir desconexiones, especialmente las críticas, para que continuamente estén integradas correctamente.
                                3. Se revisan los valores aportados por los indicadores de monitorización y alarmas. Se implementan mejoras en la correlación de eventos y detección de amenazas, así como las guías de actuación (playbook).
                            </p>
                            <div class="form-group">
                                <label for="M10_1">Análisis de fuentes e identificación de amenazas ( se informa desde el area CISO )</label>
                                <select class="form-select-custom" name="M10_1" id="M10_1">
                                    <option value='0'>No Aplica</option>
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='3'>3</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="M10_2">Integración de Fuentes ( se informa desde el area CISO )</label>
                                <select class="form-select-custom" name="M10_2" id="M10_2">
                                    <option value='0'>No Aplica</option>
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='3'>3</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="M10_3">Monitorización de eventos integrados y gestión de alertas ( se informa desde el area CISO )</label>
                                <select class="form-select-custom" name="M10_3" id="M10_3">
                                    <option value='0'>No Aplica</option>
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='3'>3</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                </select>
                            </div>
                        </div>
                        <div class="tab mshide">
                            <h3>M11 Nivel de madurez gestión de incidentes</h3>
                            <p class="pre-line">
                                NIVEL 1
                                1. Se detectan algunos incidentes, sin filtrar por prioridad.
                                2. Se comienza a llevar a cabo hacer respuesta a incidentes en la organización, pero no existe un grupo dedicado ni está formalizado el procedimiento.

                                NIVEL 2
                                1. Se comienza a detectar incidentes de algunas fuentes y a dedicar tiempo a la tarea.
                                2. La respuesta comienza a darse por los grados de criticidad del incidente e impacto.
                                3. Se notifica a las áreas afectadas, aunque aún no se reporta todo lo que se detecta.
                                4. Se resuelve sin documentar en playbooks las acciones, aunque sí existen guías y manuales no reglados sobre acciones de N1 a llevar a cabo.

                                NIVEL 3
                                1. La detección esta filtrada y se gestiona de manera óptima con un gran número de fuentes y de alta confiabilidad.
                                2. La respuesta ante incidentes es rápida y eficaz, dando prioridad por la criticad del activo afectado, criticidad del incidente e impacto.
                                3. Existe un alto grado de coordinación con el CSIRT GLOBAL.
                                4. Se registran de los incidentes de seguridad y se toma nota para mejoras en playbooks y guías. Se genera procedimiento con las distintas fases de actuación frente incidentes de seguridad, junto con las acciones a llevar a cabo, la elaboración de playbooks y guías, la coordinación y notificación de incidentes, grados y tipos de incidentes por criticidad, impacto y otras categorías.

                                NIVEL 4
                                1. El CSIRT tiene recursos adecuados para la gestión de incidentes y los medios técnicos para realizar análisis forense (pueden estar subcontratados a un servicio externo). Se generan indicadores y métricas a efectos de medición tanto detección, como tiempos de respuesta, de resolución y similar, para comprobar el funcionamiento del CSIRT.
                                2. El CSIRT tiene atención en 24x7 para atención de incidentes críticos.
                                3. Los incidentes de severidad alta y crítica se comunican al CSIRT Global en tiempo y forma
                                4. Sistemáticamente se comparten IoCs de los incidentes en la plataforma de Ciberinteligencia.

                                NIVEL 5
                                1. El CSIRT cuenta con una plataforma para la orquestación y automatización de incidentes de seguridad que permite la respuesta automática de la mayor parte de los incidentes. La plataforma de automatización y orquestación de incidentes está integrada con la plataforma de Ciberinteligencia.
                                2. La respuesta y resolución de incidentes de seguridad es sistemática, metodológica y se lleva a cabo acciones preventivas para que no se reiteren algunos incidentes.
                                3. Se revisan los incidentes de seguridad y los indicadores para comprar el grado de efectividad en materia de notificación.
                                4. Se realizan Ciber ejercicios para entrenar las capacidades del CSIRT. Se elaboran informes periódicos donde se cuantifican los incidentes de la compañía conforme a la taxonomía definida.
                            </p>
                            <div class="form-group">
                                <label for="M11_1">Detección de Incidentes ( se informa desde el area CISO )</label>
                                <select class="form-select-custom" name="M11_1" id="M11_1">
                                    <option value='0'>No Aplica</option>
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='3'>3</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="M11_2">Respuesta a Incidentes ( se informa desde el area CISO )</label>
                                <select class="form-select-custom" name="M11_2" id="M11_2">
                                    <option value='0'>No Aplica</option>
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='3'>3</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="M11_3">Notificación / Coordinación con CSIRT Global ( se informa desde el area CISO )</label>
                                <select class="form-select-custom" name="M11_3" id="M11_3">
                                    <option value='0'>No Aplica</option>
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='3'>3</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="M11_4">Resolución y Lecciones Aprendidas ( se informa desde el area CISO )</label>
                                <select class="form-select-custom" name="M11_4" id="M11_4">
                                    <option value='0'>No Aplica</option>
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='3'>3</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                </select>
                            </div>
                        </div>
                        <div class="tab mshide">
                            <h3>M12 Nivel de madurez monitorización de vulnerabilidades</h3>
                            <p class="pre-line">
                                NIVEL 1
                                1. Existe un mapa o superficie de activos para la gestión de vulnerabilidades, pero no se conoce su estado de actualización y no está sometido a revisiones.
                                2. Se llevan a cabo monitorización o escaneo de vulnerabilidades de manera eventual.
                                3. La realización de pentesting se lleva únicamente sobre algunas aplicaciones críticas de manera puntual.
                                4. La resolución de las vulnerabilidades encontradas se hace a medida que se van notificando y sin asignarles una prioridad específica.

                                NIVEL 2
                                1. Existe un mapa o superficie de activos para la gestión de vulnerabilidades y se revisa, aunque no de manera “sistemática”.
                                2. Se llevan a cabo monitorización o escaneo de vulnerabilidades con mayor frecuencia de manera no formal y sin usar una metodología concreta.
                                3. Se comienzan a llevar a cabo test de penetración con mayor regularidad sobre aplicativos críticos.
                                4. La resolución de las vulnerabilidades encontradas se lleva a cabo de manera más regular a medida que se dispone de más medios para ello.

                                NIVEL 3
                                1. Existe un procedimiento con el siguiente contenido mínimo:
                                a. Punto que contempla la gestión del mapa o superficie de activos sometidos a monitorización de vulnerabilidades
                                b. Herramientas y procesos de monitorización continua de vulnerabilidades
                                c. Roles y responsabilidades
                                d. Frecuencias de monitorización, ventanas y de análisis de vulnerabilidades
                                e. Ciclo de notificación y gestión de vulnerabilidades
                                f. Comunicación con distintas áreas implicadas, así como comunicación con Red Team Global (a través de VAMPS u otros sistemas)
                                g. Requisitos y procesos de pentesting sobre activos
                                h. Gestión de vulnerabilidades según su estado (pendientes, abiertas, cerradas, en proceso, etc.)
                                2. Se lleva a cabo las acciones reflejadas en el procedimiento, con las frecuencias y periodicidades establecidas en el mismo, de al menos los siguientes puntos:
                                a. Gestión de mapa o superficie de activos
                                b. Monitorización de vulnerabilidades (tanto externas como internas)
                                c. Pentest sobre activos críticos
                                d. Gestión y resolución de vulnerabilidades

                                NIVEL 4
                                1. El mapa o superficie de activos a monitorizar se actualiza de forma sistemática (se tiene un proceso de descubrimiento y se alimenta a partir de las CMDBs e inventario de activos de la empresa). Se llevan a cabo los reportes de activos con exposición a internet al Red Team Global para su correcto control y gestión, a través de herramientas corporativas (tipo GUNNA).
                                2. Se llevan a cabo monitorización de vulnerabilidades de los activos internos y externos de acuerdo con el procedimiento definido. Se dispone de indicadores y métricas de activos monitorizados, número de vulnerabilidades, tiempos de resolución, etc.
                                3. Se realizan pentest de los activos críticos de forma periódica y metodológica.
                                4. Se hace uso de herramientas corporativas para la gestión y resolución de vulnerabilidades (por ejemplo, VAMPS). Se atienden y resuelven en 72 horas a las vulnerabilidades críticas notificadas por el Red Team Global.

                                NIVEL 5
                                1. Se implementan mejoras sobre la gestión del mapa o superficie de activos a monitorizar (herramientas automáticas, API de sincronismo de inventarios, CMDB específicos, etc.). Se llevan a cabo informes sobre activos con monitorización continua y otros datos relevantes a efectos de toma de decisiones.
                                2. Se dispone de un equipo especifico (tipo Red Team local) dedicado a labores de monitorización continua de vulnerabilidades sobre todos los activos. Se dispone de informes de los indicadores y métricas de activos monitorizados, número de vulnerabilidades, tiempos de resolución, etc. Que ayudan a la toma de decisiones y mejoras.
                                3. Se realizan pentest de los activos de forma periódica y metodológica. Se implementan técnicas avanzadas de pentest para aplicativos y activos críticos.
                                4. Se implementan mejoras en los procesos y herramientas que ayuden a la gestión y resolución de vulnerabilidades. Se resuelven y cierran y notifican de manera eficaz las vulnerabilidades críticas notificadas.
                            </p>
                            <div class="form-group">
                                <label for="M12_1">Mapa o superficie de activos para la gestión de vulnerabilidades ( se informa desde el area CISO )</label>
                                <select class="form-select-custom" name="M12_1" id="M12_1">
                                    <option value='0'>No Aplica</option>
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='3'>3</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="M12_2">La monitorización continua de vulnerabilidades: ( se informa desde el area CISO )
                                    a.- Vulnerabilidades externas ( apoyadas por el red team Global )
                                    b.- Vulnerabilidades internas</label>
                                <select class="form-select-custom" name="M12_2" id="M12_2">
                                    <option value='0'>No Aplica</option>
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='3'>3</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="M12_3">La realización de pentesting periódico sobre activos críticos y aquellos con exposición a internet ( se informa desde el area CISO )</label>
                                <select class="form-select-custom" name="M12_3" id="M12_3">
                                    <option value='0'>No Aplica</option>
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='3'>3</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="M12_4">La resolución de las vulnerabilidades encontradas ( se informa desde el area CISO )</label>
                                <select class="form-select-custom" name="M12_4" id="M12_4">
                                    <option value='0'>No Aplica</option>
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='3'>3</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                </select>
                            </div>
                        </div>
                        <div class="tab mshide">
                            <h3>M13 Nivel de madurez Ciberinteligencia</h3>
                            <p class="pre-line">
                                NIVEL 1
                                1. La identificación de necesidades de información ha sido puntual. La coordinación entre equipos internos/Externos/OBs es lenta y baja.
                                2. Se obtienen algunas fuentes de información de manera puntual.
                                3. Las fuentes se analizan de manera puntual. Se tiene acceso a la TIA (Plataforma global de Ciberinteligencia), pero no se revisan las alertas ni se generan casos.
                                4. La difusión es limitada y poco definida. La aportación que hace es básica, así como su difusión.

                                NIVEL 2
                                1. Tiene identificadas un conjunto de necesidades tácticas. Tiene medios para cubrir necesidades tácticas. Hay coordinación con Ciberinteligencia global.
                                2. Tiene identificadas las fuentes para cubrir necesidades y están coordinadas con global. Tiene captación de las fuentes identificadas. Tiene integración de las fuentes. Tiene las fuentes tácticas cubiertas y en explotación.
                                3. Análisis en obtención en TIA. Elaboración básica en TIA.
                                4. Identificados destinatarios básicos. Aportación predominantemente táctica. Aportación predominantemente táctica.

                                NIVEL 3
                                1. Existe un procedimiento al menos con la siguiente información y contenido:
                                a. Identificación de las necesidades (tácticas y operativas).
                                b. Difusión de la información y mecanismos de coordinación con Ciberinteligencia Global y con otras áreas de seguridad. Roles y responsabilidades.
                                c. Gestión, control e integración de fuentes.
                                d. Metodología de trabajo en base al ciclo de obtención de inteligencia.
                                e. Análisis/Elaboración de información. Uso y gestión de la TIA.
                                2. Se llevan a cabo acciones de identificación de necesidades, obtención de información, análisis y difusión acorde al procedimiento.

                                NIVEL 4
                                1. Se lleva a cabo la identificación del conjunto de necesidades y la coordinación con Ciberinteligencia Global acorde al procedimiento.
                                2. Se lleva a cabo la identificación de las fuentes para cubrir necesidades de manera coordinada con Ciberinteligencia Global acorde al procedimiento. Se aplica la metodología de trabajo en base ciclo de obtención de inteligencia acorde al procedimiento.
                                3. El análisis de fuentes se realiza a través de TIA de acuerdo con el ciclo de inteligencia y las indicaciones del área de Ciberinteligencia Global y acorde con lo indicado en el procedimiento.
                                4. Se Identifican los destinatarios acordes a lo indicado en el procedimiento. Se implementan métricas e indicadores en todas las fases y estadios del ciclo de Ciberinteligencia.

                                NIVEL 5
                                1. Se revisa y chequea que se llevan a cabo la identificación de necesidades y coordinación con Ciberinteligencia Global acorde al procedimiento.
                                2. Se dispone de medios suficientes para la elaboración de inteligencia propia, ejecutados de forma eficiente y efectiva. Ciberinteligencia mejorando los niveles de madurez de la compañía. Se dispone de captación de las fuentes identificadas y están integradas, acorde a lo que se indica en el procedimiento.
                                3. Se realizan análisis en obtención TIA en base al ciclo de inteligencia, con Op propias. Se mejora la elaboración de inteligencia TOE propia.
                                4. Se mejora la identificación procedimental y se automatiza en la medida de lo posible. Se revisan las métricas e indicadores para aplicar mejoras en las tareas y fases de Ciberinteligencia, nuevas herramientas y metodologías.
                            </p>
                            <div class="form-group">
                                <label for="M13_1">Dirección ( se informa desde el area CISO )</label>
                                <select class="form-select-custom" name="M13_1" id="M13_1">
                                    <option value='0'>No Aplica</option>
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='3'>3</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="M13_2">Obtención de fuentes ( se informa desde el area CISO )</label>
                                <select class="form-select-custom" name="M13_2" id="M13_2">
                                    <option value='0'>No Aplica</option>
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='3'>3</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="M13_3">Análisis de fuentes ( se informa desde el area CISO )</label>
                                <select class="form-select-custom" name="M13_3" id="M13_3">
                                    <option value='0'>No Aplica</option>
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='3'>3</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="M13_4">Difusión de información de Ciberinteligencia ( se informa desde el area CISO )</label>
                                <select class="form-select-custom" name="M13_4" id="M13_4">
                                    <option value='0'>No Aplica</option>
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='3'>3</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                </select>
                            </div>
                        </div>
                        <div class="tab mshide">
                            <h3>M14 Nivel de madurez concienciación y formación de usuarios en Seguridad Digital</h3>
                            <p class="pre-line">
                                NIVEL 1
                                1. Las iniciativas de concienciación para los empleados en materia de Seguridad Digital son limitadas y con poca
                                frecuencia.
                                2. De manera puntual se realizan algunos cursos o formación específica de carácter técnico y de Seguridad Digital en alguna área.

                                NIVEL 2
                                1. Se planifican e implantan al menos dos veces al año, algunas iniciativas y cursos de concienciación para los empleados en materia de Seguridad Digital.
                                2. Se estudian necesidades y se realizan cursos o formación específica de carácter técnico y de Seguridad Digital en varias áreas técnicas al menos una vez al año.

                                NIVEL 3
                                1. Se llevan a cabo dos veces al año o superior cursos de concienciación para los empleados. Se difunde entre los empleados píldoras de concienciación. Se usan fuentes de confianza en materia de Seguridad Digital para desarrollar material propio en concienciación.
                                2. Se realizan cursos específicos y técnicos en varias áreas técnicas con contenido especifico que pueda aplicarse en la empresa.
                                3. Se realiza 1 campaña de phishing (mínimo) al año. Se planifican y se ejecutan otras iniciativas en materia de concienciación de manera practica a lo largo del año (ejercicios red Team vs blue Team, etc.).

                                NIVEL 4
                                1. Se realiza seguimiento del personal que realiza de manera adecuada los cursos y formación concienciación de Seguridad Digital. Se elaboran indicadores al respecto, para medir este dato. Se designa a determinadas áreas su seguimiento (recursos humanos).
                                2. Se realiza un seguimiento del personal que realiza cursos específicos o de carácter técnico. Se comprueba que se mande gente a estos cursos, por parte de las áreas más afectadas, al menos 1 vez al año. Se definen indicadores y métricas para su medición.
                                3. Se implantan y miden indicadores para la valoración de las campañas de phishing u otras campañas en materia de concienciación.

                                NIVEL 5
                                1. Se revisan periódicamente los contenidos necesarios para el plan de formación y concienciación en Seguridad Digital. Se adaptan a las necesidades de la OB/GBU, de las áreas interesadas y de acuerdo con el análisis de riesgos global y las amenazas actuales. Se remiten boletines altamente técnicos a quienes puedan requerirlo.
                                2. Se implementan mejoras en las necesidades de cursos específicos o técnicos para las áreas que lo requieran con mayor necesidad. Se proporciona información acerca de qué aspectos o temas son prioritarios recibir formación. Se aplican los datos aportados por los indicadores para estas decisiones.
                                3. Se hace seguimiento, junto con el área de Ciberinteligencia, de mejoras y adaptaciones en las campañas de phishing para mejorar la formación y concienciación en Seguridad Digital. Se diseñan nuevas campañas y acciones de carácter práctico y ejercicios interesantes en materia de concienciación en Seguridad Digital.
                            </p>
                            <div class="form-group">
                                <label for="M14_1">Iniciativas de concienciación de Seguridad Digital a los empleados ( se informa desde el area CISO )</label>
                                <select class="form-select-custom" name="M14_1" id="M14_1">
                                    <option value='0'>No Aplica</option>
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='3'>3</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="M14_2">Cursos o formación especifica de carácter técnico y de Seguridad Digital ( se informa desde el area CISO )</label>
                                <select class="form-select-custom" name="M14_2" id="M14_2">
                                    <option value='0'>No Aplica</option>
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='3'>3</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="M14_3">Ejercicios y formación practica en materia de Seguridad Digital ( se informa desde el area CISO )</label>
                                <select class="form-select-custom" name="M14_3" id="M14_3">
                                    <option value='0'>No Aplica</option>
                                    <option value='1'>1</option>
                                    <option value='2'>2</option>
                                    <option value='3'>3</option>
                                    <option value='4'>4</option>
                                    <option value='5'>5</option>
                                </select>
                            </div>
                        </div>
                        <div class="tab mshide">
                            <h3>OBSERVACIONES</h3>
                            <p class="pre-line">
                                En este apartado añada cuantas observaciones considere de interés a los datos reportados
                            </p>
                            <div class="form-group">
                                <label for="comentario-observaciones">Observaciones relacionadas con los datos facilitados</label>
                                <textarea id="comentario-observaciones" rows="4" cols="50" class="form-control" maxlength="200" name="comentario"></textarea>
                            </div>
                            <div class="form-group">
                                <label for="sugerencia-observaciones">Sugerencias o Comentarios de mejora</label>
                                <textarea id="sugerencia-observaciones" rows="4" cols="50" class="form-control" maxlength="200" name="sugerencia"></textarea>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12 text-right">
                                <button class="btn btn-primary prevBtn" type="button">Atrás</button>
                                <button class="btn btn-primary nextBtn" type="button">Siguiente</button>
                                <button class="btn btn-primary saveBtn mshide" type="button">Enviar</button>
                            </div>
                        </div>
                        <div class="text-center block-step">
                            <span class="step"></span>
                        </div>
                    </div>
                    <div class="text-center block-step">
                        <span class="step"></span>
                    </div>
                </form>
            </div>
            <div class="row d-flex justify-content-center form-metricas-csirt tarjeta mshide  form-csirt">
                <div class="padding-bottom-22">
                    <h3>Reporte KPMS - Métricas CSIRT</h3>
                    <h5 class="">Instrucciones Generales</h5>
                    <div>
                        Si tiene dudas de como rellenar este formulario, consulte la <a href="https://telefonicacorp.sharepoint.com/:b:/r/sites/SeguridadCDCOKPIs.TMELA/Shared%20Documents/General/KPMS/Indicadores%20de%20seguridad%20digital_v.3.pdf">documentación</a> oficial facilitada desde corporativo.
                    </div>
                </div>
                <form class="col-12 form-metricas-csirt form-csirt">
                    <div class="col-12 formularioKPMs csirt">
                        <div class="tab">
                            <h3>Introducción</h3>
                            <div class="form-group">
                                <label class="control-label" for="reportAs">Reportar como:</label>
                                <select class="form-select-custom reportAs" name="activo">
                                </select>
                            </div>
                            <div class="form-group">
                                <label class="control-label" for="reportingPeriod">Período que se reporta:</label>
                                <select class="form-select-custom reportingPeriod" name="cuarto">
                                    <option value='q1'>Q1</option>
                                    <option value='q2'>Q2</option>
                                    <option value='q3'>Q3</option>
                                    <option value='q4'>Q4</option>
                                </select>
                            </div>
                        </div>
                        <div class="tab mshide cuestionarioFinal-csirt">
                            <h3>Observaciones</h3>
                            <small>Introduzca aquí todas las observaciones que considere necesarias relacionadas con los valores aportados o los comentarios que encuentre de interés</small>
                            <div class="form-group">
                                <label for="comentario-csirt">Observaciones en relación a las metricas aportadas:</label>
                                <textarea id="comentario-csirt" rows="4" cols="50" class="form-control" maxlength="200" name="comentario"></textarea>
                            </div>
                            <div class="form-group">
                                <label for="sugerencia-csirt">Observaciones en relación a comentarios o sugerencias de mejora:</label>
                                <textarea id="sugerencia-csirt" rows="4" cols="50" class="form-control" maxlength="200" name="sugerencia"></textarea>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12 text-right">
                                <button class="btn btn-primary prevBtn" type="button">Atrás</button>
                                <button class="btn btn-primary nextBtn" type="button">Siguiente</button>
                                <button class="btn btn-primary saveBtn mshide" type="button">Enviar</button>
                            </div>
                        </div>
                        <div class="text-center block-step">
                            <span class="step"></span>
                        </div>
                    </div>
                </form>
            </div>
            <div class="divtable tab-pane fade show gestor-kpms" id="gestor-kpms" role="tabpanel" aria-labelledby="home-tab">
                <div class="row mt-3">
                    <div class="col-md-12 d-flex mb-3 align-items-center">
                        <button id="newKpm" class="btn btn-primary ms-auto" type="button">Crear nuevo KPM</button>
                    </div>
                    <div class="col-md-6 KPMsNoAsignados">
                        <h2 class="mt-3"><b>Kpms sin asignar</b></h2>
                        <div class="row mt-3" id="kpmCerrados-cards">
                        </div>
                    </div>
                    <div class="col-md-6 KPMsAsignados">
                        <h2 class="mt-3"><b>Kpms asignados</b></h2>
                        <div class="row mt-3" id="kpmAbiertos-cards">
                        </div>
                    </div>
                </div>
            </div>
            <div class="divtable tab-pane fade show reporters-kpms" id="reporters-kpms" role="tabpanel" aria-labelledby="home-tab">
                <?php insertLoadingDinamic(
                    "Reporters de KPMs",
                    "loadingReporters"
                ) ?>
                <div class="col-md-12 mt-4">
                    <table class="table table-condensed table-hover table-striped table-11cert" id='tablaReportersKPMs' data-identifier="ID">
                        <caption>Catálogo completo de preguntas</caption>
                        <thead>
                            <tr id="reportersTR">
                                <th data-column-id="ID" data-header-css-class="IDCol" data-visible="false" data-identifier="true">ID</th>
                                <th data-column-id="Email" data-header-css-class="emailCol">Email</th>
                                <th data-column-id="Activo" data-header-css-class="activoCol">Activo</th>
                                <th data-column-id="idActivo" data-header-css-class="idActivoCol" data-visible="false">Activo ID</th>
                                <th data-column-id="idUser" data-header-css-class="idUserCol" data-visible="false">User ID</th>
                            </tr>
                        </thead>
                        <tbody id='bodyTablaReportersKPMs'>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <?php getfooter() ?>
</body>

</html>
