<!DOCTYPE html>
<html lang="es">

<head>
    <title>Visualizador de logs</title>
    <?php getheader("Visualizador de logs", false) ?>
    <script type="module" src="./js/logs.js" type="text/javascript" integrity="<?php echo "sha384-" . base64_encode(hash_file('sha384', "./js/logs.js", true)) ?>" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="./css/logs.css">
</head>

<body class="d-flex flex-column h-100">
    <?php getmenu() ?>
    <div class="container">
        <h1 class="mt-5 tituloLogs"><b>Visualizador de logs de 11Cert</b></h1>
        <div class="list-container mt-5">
            <div class="list-section">
                <h2 class="section-title">▾ Activos creados</h2>
                <ul id="NewActivos">
                </ul>
            </div>
            <div class="list-section">
                <h2 class="section-title">▾ Activos eliminados</h2>
                <ul id="DelActivos">
                </ul>
            </div>
            <div class="list-section">
                <h2 class="section-title">▾ Activos modificados</h2>
                <ul id="ModActivos">
                </ul>
            </div>
            <div class="list-section">
                <h2 class="section-title">▾ Cambios de relación en activos</h2>
                <ul id="ChangeActivos">
                </ul>
            </div>
        </div>
    </div>
    <?php getfooter() ?>
</body>

</html>
