<!DOCTYPE html>
<html lang="es">

<head>
    <title>PAC - Plan de Acciones Correctivas</title>
    <?php getheader("PAC - Plan de Acciones Correctivas", false) ?>
</head>

<body class="d-flex flex-column h-100">
    <?php getmenu() ?>
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb breadlist">
                <li class="breadcrumb-item active" aria-current="page">
                    <a class="b-home" href="./app">Inicio</a>
                </li>
                <li class="breadcrumb-item ml-auto">
                    <a class="b-item servId" level="2" href="#"><?php if (isset($servicio[0]["nombre"])) {
                                                                    echo $servicio[0]["nombre"];
                                                                } else {
                                                                    echo "null";
                                                                } ?>
                    </a>
                </li>
                <li class="breadcrumb-item ml-auto">
                    <a class="b-home" href="./historialservicio?id=<?php
                                                                    if (isset($id)) {
                                                                        echo $id;
                                                                    } else {
                                                                        echo "null";
                                                                    }
                                                                    ?>">Historial
                    </a>
                </li>
                <li class="breadcrumb-item ml-auto">
                    <a class="b-home" href="./pac?id=<?php
                                                        if (isset($id)) {
                                                            echo $id;
                                                        } else {
                                                            echo "null";
                                                        }
                                                        ?>">PAC
                    </a>
                </li>
            </ol>
        </nav>
        <div class="row nombreservicio">
            <div id="<?php if (isset($id)) {
                            echo $id;
                        } else {
                            echo "null";
                        } ?>" class="col-12 font-32 servicioId text-center">
                <?php if (isset($servicio[0]["nombre"])) {
                    echo $servicio[0]["nombre"];
                } else {
                    echo "null";
                } ?>
            </div>
        </div>

        <div class='row pacservicio'>
            <table id="table-seguimientopac" class="table table-condensed table-hover table-striped table-11cert">
                <caption>Listado PACs</caption>
                <thead>
                    <th id='id' data-column-id="id" data-type="numeric" data-identifier="true" data-visible='false'>id</th>
                    <th id='activo_id' data-column-id="activo_id" data-type="numeric" data-visible='false'>activo_id</th>
                    <th id='proyecto_id' data-column-id="proyecto_id" data-type="numeric" data-visible='false'>proyecto_id</th>
                    <th id='evaluacion_id' data-column-id="evaluacion_id" data-visible='false'>evaluacion_id</th>
                    <th id='sistema' data-column-id="sistema">Sistema</th>
                    <th id='proyecto' data-column-id="proyecto">Proyecto</th>
                    <th id='prioridad' data-column-id="prioridad">Prioridad</th>
                    <th id='responsable' data-column-id="responsable">Responsable</th>
                    <th id='estado' data-column-id="estado" data-visible='true'>Estado</th>
                    <th id='inicio' data-column-id="inicio" data-visible='true'>Inicio</th>
                    <th id='fin' data-column-id="fin" data-visible='true'>Fin</th>
                    <th id='creado' data-column-id="creado" data-visible='false'>Creado</th>
                    <th id='comentarios' data-column-id="comentarios">Comentarios</th>
                    <th id='adjuntos' data-column-id="adjuntos" data-visible='false'>Adjuntos</th>
                    <th data-column-id="commands" data-formatter="commands" data-sortable="false">Acciones</th>
                </thead>
                <tbody id='table-seguimientopac-data'>
                </tbody>
            </table>
        </div>
    </div>
    <?php getfooter() ?>
</body>

</html>
