<!DOCTYPE html>
<html lang="es">

<head>
    <title>Políticas de Privacidad</title>
    <?php getheader("Políticas de Privacidad", false, false) ?>
</head>

<body class="d-flex flex-column h-100">
    <?php getmenu() ?>
    <div class="container">
        <div class="row">
            <div class="col-sm">
                <p class=MsoNormal>POLÍTICA DE PRIVACIDAD</span></span></p>

                <p class=MsoNormal><br>
                    </span><span class=DestacadoTelefonicaBlancoCar><span lang=ES-TRAD>
                            11 CERT
                        </span></span></p>

                <p class=NombreyfechaportadaTelefnica><span>TELEFÓNICA Digital España, S.L.U.</span></p>


                <p class=MsoNormal><span>CONTENIDO</span></p>

                <p class=MsoToc1><a href="#nuestrosprincipios"><span>NUESTROS PRINCIPIOS</span><span><span>. </span></span><span></a><span>

                    </span></p>

                <p class=MsoToc1><a href="#quees11cert"><span>¿QUÉ ES 11 CERT?</span><span><span>. </span></span></a><span>

                    </span></p>

                <p class=MsoToc1><a href="#quienesresponsable"></span><span>1.<span>            </span></span><span>¿Quién es el responsable
                            de 11 Cert?</span><span><span>. </span></span></a><span>

                    </span></p>

                <p class=MsoToc1><a href="#aplicacion"></span><span>2.<span>            </span></span><span>Aplicación</span><span><span>. </span></span></a><span>

                    </span></p>

                <p class=MsoToc1><a href="#"><span>3.</span><span><span>            </span></span><span>Roles</span><span><span>. </span></span><span></span></a><span>

                    </span></p>

                <p class=MsoToc1><a href="#"><span>4.</span><span><span>            </span></span><span>¿Qué datos se procesan
                            en 11 Cert, con qué propósito y por qué procesamos los datos?</span><span><span>  </span></span></a><span>

                    </span></p>

                <p class=MsoToc2><a href="#"><span>¿Qué datos? – Tipos de
                            datos:</span><span <span> </span></span></a><span>

                    </span></p>

                <p class=MsoToc2><a href="#"><span>¿Para qué? - Finalidades
                            del tratamiento:</span><span><span> </span></span></a><span>

                    </span></p>

                <p class=MsoToc2><a href="#"><span>¿Por qué?</span><span><span>. </span></span></a><span>

                    </span></p>

                <p class=MsoToc2><a href="#"><span>¿De dónde vienen los
                            datos?</span><span><span>. </span></span></a><span>

                    </span></p>

                <p class=MsoToc2><a href="#"><span>¿A quién pertenecen? -
                            Categorías de interesados:</span><span><span> </span></span></a><span>

                    </span></p>

                <p class=MsoToc1><a href="#"><span>5.</span><span><span>            </span></span><span>¿Cuánto tiempo se
                            conservan los datos?</span><span><span>. </span></span></a><span>

                    </span></p>

                <p class=MsoToc1><a href="#"><span>6.</span><span><span>            </span></span><span>Destinarios de los datos
                            y sistemas de terceros</span><span><span>. </span></span></a><span>

                    </span></p>

                <p class=MsoToc1><a href="#"><span>7.</span><span><span>            </span></span><span>Transferencias
                            internacionales de datos</span><span><span>. </span></span></a><span>

                    </span></p>

                <p class=MsoToc1><a href="#"><span>8.</span><span><span>            </span></span><span>¿Qué derechos tienes
                            como interesado?</span><span><span>. </span></span></a><span>

                    </span></p>

                <p class=MsoToc1><a href="#"><span>9.</span><span><span>            </span></span><span>Cambios a esta Política</span><span><span>. </span></span></a><span>

                    </span></p>

                <p class=MsoNormal><span>
                        <o:p>&nbsp;</o:p>
                    </span></p>

                <p class=MsoNormal><span>
                        <o:p>&nbsp;</o:p>
                    </span></p>

                <p class=MsoNormal><span>
                        <o:p>&nbsp;</o:p>
                    </span></p>

                <p class=MsoNormal><span>
                        <o:p>&nbsp;</o:p>
                    </span></p>

                <p class=MsoNormal>

                <table cellpadding=0 cellspacing=0 width="100%">
                    <tr>
                        <td>

                            <div>
                                <h1 align=center><a name="_Toc124335133"><span id="nuestrosprincipios">NUESTROS PRINCIPIOS</span></a><span></span><span class=TituloPortadaBlancoCar><span>

                                        </span></span></h1>
                                <p class=MsoNormal align=center><span class=TituloPortadaBlancoCar><span>En Telefónica tenemos el compromiso de
                                            respetar la privacidad, el secreto y la seguridad de los datos personales de
                                            nuestros empleados, clientes y proveedores.</span></span></p>
                                <p class=MsoNormal align=center><span class=TituloPortadaBlancoCar><span>
                                            <o:p>&nbsp;</o:p>
                                        </span></span></p>
                                <p class=MsoNormal align=center><span class=TituloPortadaBlancoCar><span>Nuestro enfoque para respetar y
                                            proteger la privacidad de los datos personales que tratamos se extiende
                                            más allá de los requisitos legales de cumplimiento. Es nuestra prioridad,
                                            forma parte de nuestro ADN y así lo reflejamos en los principios que rigen
                                            nuestras políticas en materias de privacidad y seguridad.</span></span></p>
                                <p class=MsoNormal align=center><span class=TituloPortadaBlancoCar><span>
                                            <o:p>&nbsp;</o:p>
                                        </span></span></p>
                                <p class=MsoNormal align=center><span class=TituloPortadaBlancoCar><span>Esta Política de Privacidad establece
                                            los principios rectores y la forma en que los Datos Personales de los
                                            usuarios y/o de los terceros interesados son tratados en el uso y gestión de
                                            t11 <span class=SpellE>Cert</span>. </span></span></p>
                                <p class=MsoNormal align=center><span class=TituloPortadaBlancoCar><span>
                                            <o:p>&nbsp;</o:p>
                                        </span></span></p>
                                <p class=MsoNormal align=center><span class=TituloPortadaBlancoCar><span>Para obtener más información sobre los
                                            procedimientos que sustentan esta Política, comuníquese con </span></span><a href="mailto:privacidad.cisocdo@telefonica.com"><b><span>privacidad.cisocdo@telefonica.com</span></b></a><b><span>
                                        </span></b><span class=TituloPortadaBlancoCar><span>

                                        </span></span></p>
                                <p class=MsoNormal align=center><span>
                                        <o:p>&nbsp;</o:p>
                                    </span></p>
                            </div>

                        </td>
                    </tr>
                </table>
                <table cellpadding=0 cellspacing=0 width="100%">
                    <tr>
                        <td>

                            <div>
                                <p class=MsoNormal align=center><span><span> </span>Eres el único que puedes <b>controlar el
                                            uso</b> que se hace de tus datos personales. Ponemos a tu disposición las
                                        herramientas para que puedas ejercitar tus derechos.</span></p>
                            </div>

                        </td>
                    </tr>
                </table>
                <table cellpadding=0 cellspacing=0 width="100%">
                    <tr>
                        <td>

                            <div>
                                <p class=MsoNormal><span>Nos preocupamos por garantizar
                                        la <b>seguridad</b>, el secreto y la confidencialidad de tus datos e
                                        información.</span></p>
                                <p class=MsoNormal><span><span> </span>Adoptamos robustas medidas de
                                        seguridad para evitar su pérdida, alteración, mal uso o acceso sin
                                        autorización.</span></p>
                                <p class=MsoNormal align=center>
                                    <o:p>&nbsp;</o:p>
                                </p>
                            </div>

                        </td>
                    </tr>
                </table>
                <table cellpadding=0 cellspacing=0 width="100%">
                    <tr>
                        <td>

                            <div>
                                <p class=MsoNormal align=center><span>Somos 100% <b>transparentes</b>
                                        respecto a los datos que recogemos y/o tratamos.</span></p>
                                <p class=MsoNormal align=center><span>Aquí te
                                        explicaremos por qué los utilizamos y para qué finalidades. </span></p>
                                <p class=MsoNormal align=center><span>No vamos a
                                        tratar tus datos de una forma inesperada, oscura o abusiva.</span></p>
                            </div>

                        </td>
                    </tr>
                </table>
                <a name="_Toc69754757"></a><span><span><br clear=all>
                    </span></span><span><span>
                        <o:p>&nbsp;</o:p>
                    </span></span>
                </p>

                <span></span>

                <p class=MsoNormal>
                <table cellpadding=0 cellspacing=0 width="100%">
                    <tr>
                        <td>

                            <div>
                                <h1><a name="_Toc124335134"><span id="quees11cert">¿QUÉ ES 11 CERT?</span></a><span>

                                    </span></h1>
                                <p class=MsoNormal><span lang=es>11 <span class=SpellE>Cert</span>
                                        es una solución desarrollada por Telefónica Digital, S.L.U. (en adelante,
                                        “Telefónica”). para realizar una analítica de riesgos y comprobar el
                                        cumplimiento regulatorio de los sistemas informáticos utilizados por Telefónica,
                                        a través de diferentes funcionalidades desarrolladas específicamente para cumplir
                                        estos objetivos.</span></p>
                            </div>

                        </td>
                    </tr>
                </table>
                </span>
                </p>
            </div>
            <div class=WordSection2>

                <h1><a name="_Toc124335135">
                        <span><span>1.<span>&nbsp;&nbsp;
                                </span></span></span>
                        <span id="quienesresponsable">¿Quién
                            es el responsable de 11 </span>
                    </a><span class=SpellE><span><span>Cert</span></span></span><span><span>?</span></span><span>

                    </span></h1>

                <p class=MsoNormal><span lang=es>Telefónica Digital, S.L.U.
                        (&quot;Telefónica&quot;), empresa con número de identificación </span><span class=normaltextrun><span>B83188953</span></span><span lang=es>y domicilio social en Calle Gran
                        Vía, 28, Madrid, es la responsable por el desarrollo, uso y gestión de 11 <span class=SpellE>Cert</span>, y por lo tanto también es la responsable por el
                        tratamiento de los datos personales registrados en 11 <span class=SpellE>Cert</span>.</span></p>

                <h1><a name="_Toc124335136">
                        <span><span>2.<span>&nbsp;&nbsp;
                                </span></span></span>
                        <span id="aplicacion">Aplicación</span>
                    </a><span>

                    </span></h1>

                <p class=MsoNormal><span lang=es>Esta Política de Privacidad se
                        aplica a todos los usuarios de 11 <span class=SpellE>Cert</span> y a todos los
                        terceros que, por mantener una relación jurídica, directa o indirectamente con
                        Telefónica, utilizan 11 <span class=SpellE>Cert</span>.</span></p>

            </div>

            <div class=WordSection4>
                <h1><a name="_Toc69754767">
                        <span><span>3.<span>&nbsp;&nbsp;
                                </span></span></span>
                        <span></span>
                    </a><a name="_Toc124335137"><span><span id="roles">Roles</span></span></a><span><span>

                        </span></span></h1>

                <p class=MsoNormal><span><span lang=es>Telefónica actúa como <b>responsable</b> por los tratamientos de datos
                            personales de los usuarios de 11 <span class=SpellE>Cert</span> que actúen en
                            su representación.</span></span></p>

                <p class=MsoNormal><span><span class=GramE><span lang=es>Telefónica<span>  </span>actuará</span></span></span><span><span lang=es> como <b>encargada</b> del tratamiento en el caso de que 11 <span class=SpellE>Cert</span> se utilice por una filial de Telefónica a la cual se
                            otorgue un derecho de uso del 11 <span class=SpellE>Cert</span>. En este caso
                            la empresa usuaria de 11 <span class=SpellE>Cert</span> será la responsable por
                            los tratamientos de los datos personales de sus usuarios.</span></span></p>


                <h1><span><a name="_Toc124335138">
                            <span><span>4.<span>&nbsp;&nbsp; </span></span></span>
                            <span>¿Qué datos se procesan en 11 </span>
                        </a><span class=SpellE><span><span>Cert</span></span></span></span><span><span><span>, con qué propósito y por qué procesamos los datos?</span></span></span><span><span>

                        </span></span></h1>

                <span></span>

            </div>

            <div class=WordSection5>

                <h2><a name="_Toc124335139"><span>¿Qué datos? –
                            Tipos de datos:</span></a><span>

                    </span></h2>

                <p class=MsoNormal><span lang=es>Los datos personales procesados a
                        través de 11 <span class=SpellE>Cert</span> consisten en datos identificativos de
                        los usuarios de la herramienta, tales como los datos de contacto profesional
                        del usuario (empleado o terceros): nombre, apellidos, número de identificación,
                        dirección profesional, DNI, nacionalidad, estado civil, correo electrónico,
                        sociedad y departamento para la cual trabaja. </span></p>

                <h2><a name="_Toc124335140"><span>¿Para qué? -
                            Finalidades del tratamiento:</span></a><span>

                    </span></h2>

                <p class=MsoNormal><span>Para la analítica de riesgos y la verificación acerca del
                        cumplimiento regulatorio de los sistemas informativos utilizados por Telefónica
                        y por sus filiales en la gestión de sus actividades de negocio y/o de gestión
                        interna</span><span lang=es>, con el objetivo de garantizar la
                        seguridad de estos sistemas y de sus usuarios y verificar el debido
                        cumplimiento normativo</span><span lang=es>.</span></p>

                <h2><a name="_Toc124335141"><span>¿Por qué?</span></a><span>

                    </span></h2>

                <p class=MsoNormal><span lang=es>Las bases legales en las que nos
                        basamos para llevar a cabo ese propósito son:</span></p>

                <p class=MsoListParagraphCxSpFirst>
                    <span lang=es><span>i.<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                            </span></span></span>
                    <span lang=es>el interés legítimo de la compañía
                        en garantizar la seguridad de sus sistemas y la adecuación de éstos al marco
                        regulatorio. </span>
                </p>

                <p class=MsoListParagraphCxSpLast>
                    <span lang=es><span>ii.<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                            </span></span></span>
                    <span lang=es>En el caso del uso de
                        11 <span class=SpellE>Cert</span> por otras filiales, la prestación de un servicio
                        / ejecución de un contrato en el cual la filial es parte.</span>
                </p>

                <h2><span>
                        <o:p>&nbsp;</o:p>
                    </span></h2>

                <h2><a name="_Toc124335142"><span>¿De dónde
                            vienen los datos?</span></a><span> <span> </span>

                    </span></h2>

                <p class=MsoNormal><span lang=es>Los datos de los usuarios se
                        proporcionan por el propio empleado o por el empleador para su registro como
                        usuario de la herramienta.</span><span lang=es>

                    </span></p>

                <h2><a name="_Toc124335143"><span>¿A quién
                            pertenecen? - Categorías de interesados:</span></a><span>

                    </span></h2>

                <p class=MsoNormal><span lang=es>Empleados de Telefónica, empleados
                        de los terceros que presten servicios a Telefónica y/o de los empleados y
                        colaboradores de las filiales de Telefónica, S-A. que utilicen 11 <span class=SpellE>Cert</span>.</span></p>

                <p class=MsoNormal><span lang=es><span> </span>

                    </span></p>

            </div>

            <span lang=es><br clear=all>
            </span>

            <div class=WordSection6>

                <p class=MsoNormal><span lang=es>
                        <o:p>&nbsp;</o:p>
                    </span></p>

                <h1><a name="_Toc124335144">
                        <span><span>5.<span>&nbsp;&nbsp; </span></span></span>
                        <span>¿Cuánto tiempo se conservan los datos?</span>
                    </a><span>

                    </span></h1>

                <p class=MsoNormal><span>Con carácter general, los datos
                        personales tratados a través de 11 <span class=SpellE>Cert</span> se
                        conservarán durante el plazo necesario para cumplir con la finalidad de cada
                        tratamiento y para determinar las posibles responsabilidades que puedan
                        derivarse de dicha finalidad. </span></p>

                <p><span lang=ES-TRAD>
                        <o:p>&nbsp;</o:p>
                    </span></p>

                <h1><a name="_Toc116633290"></a><a name="_Toc124335145"><span>
                            <span><span>6.<span>&nbsp;&nbsp; </span></span></span>
                            <span>Destinarios de los datos y sistemas de
                                terceros</span>
                        </span></a><span><span>

                        </span></span></h1>

                <span></span>

                <p class=MsoNormal><span>Para llevar a cabo los fines de
                        procesamiento descritos anteriormente, Telefónica hace uso de subcontratistas
                        autorizados que actúan en su nombre y que están contractualmente sujetos a sus
                        instrucciones, solo para los fines establecidos y durante el período de tiempo
                        estrictamente necesario para ese propósito. <span> </span>Telefónica. mantiene un contrato y un Acuerdo
                        de Procesamiento de Datos Personales con cada subcontratista que actúe como
                        encargado del tratamiento de los datos personales que se traten a través de 11 <span class=SpellE>Cert</span>.</span></p>

                <p class=MsoNormal><span>11 <span class=SpellE>Cert</span> se
                        desarrolló y/o se integra con sistemas de terceros, con quienes Telefónica
                        mantiene una relación comercial de encargado del tratamiento. Actualmente, 11 <span class=SpellE>Cert</span> se desarrolla y/o se integra con el siguiente sistema
                        de terceros:</span></p>

                <p class=MsoNormal><b><span lang=PT-BR>Sistema:<span>                              </span>Encargado<span>                                                          </span>

                        </span></b></p>

                <p class=MsoNormal><span lang=PT-BR>Microsoft Azure<span>               </span>Microsoft
                        Ireland</span></p>

                <p class=MsoNormal><span>Los subcontratistas de Telefónica
                        pueden mantener relaciones contractuales con terceros para la prestación de los
                        servicios que es fueron contratados. En estos casos, Telefonica les exige que
                        mantengan el mismo nivel de compromiso y obligaciones que mantienen con
                        Telefónica.</span></p>

                <h1><a name="_Toc124335146">
                        <span><span>7.<span>&nbsp;&nbsp; </span></span></span>
                        <span>Transferencias internacionales de datos</span>
                    </a><span>

                    </span></h1>

                <p class=MsoNormal><span>Cuando un subcontratista autorizado
                        se encuentre o procese sus datos fuera del Espacio Económico Europeo, se
                        realiza una transferencia internacional de sus datos de acuerdo con la
                        legislación de protección de datos aplicable. </span></p>

                <p class=MsoNormal><span>En general, Telefónica evitará las
                        transferencias internacionales de datos y los datos personales tratados a
                        través de 11 <span class=SpellE>Cert</span> serán procesados dentro del Espacio
                        Económico Europeo. Sin embargo, en el caso de que dichas transferencias
                        internacionales sean necesarias, Telefónica y/o sus encargados tomarán las
                        medidas organizativas, técnicas y contractuales necesarias para garantizar la
                        protección y seguridad de sus datos.</span></p>

                <p class=MsoNormal><span>
                        <o:p>&nbsp;</o:p>
                    </span></p>

                <h1><a name="_Toc124335147">
                        <span><span>8.<span>&nbsp;&nbsp; </span></span></span>
                        <span>¿Qué derechos tienes como interesado?</span>
                    </a><span>

                    </span></h1>

            </div>

            <span><br clear=all>
            </span>

            <div class=WordSection7>

                <p><span>Los interesados podrán
                        ejercer ante Telefónica los derechos que les otorga la normativa de protección
                        de datos aplicable, descritos a continuación:</span></p>

                <p><b><u><span>Derecho
                                de acceso</span></u></b><span>: corresponde al derecho del interesado en solicitar
                        detalles de los datos que el responsable tiene sobre él y cómo los procesa, y a
                        obtener una copia de estos datos. </span></p>

                <p><b><u><span>Derecho
                                de rectificación</span></u></b><span>: este es el derecho del interesado a
                        obtener la rectificación de sus datos inexactos o erróneos, así como a
                        completar datos incompletos. </span></p>

                <p><b><u><span>Derecho
                                de supresión</span></u></b><span>: corresponde al derecho del interesado a
                        solicitar la eliminación o supresión de sus datos e información en determinadas
                        circunstancias. </span></p>

                <p><span>Sin embargo, hay ciertas
                        ocasiones en las que el responsable tiene el derecho legal a continuar
                        reteniendo y procesando los datos, por ejemplo, para cumplir con una obligación
                        legal de conservar datos. </span></p>

                <p><b><u><span>Derecho
                                a la limitación del tratamiento</span></u></b><span>: este es el derecho del interesado a
                        restringir o limitar el tratamiento de sus datos en determinadas
                        circunstancias. </span></p>

                <p><span>Una vez más, puede haber
                        ocasiones en las que el responsable tenga el derecho legal a rechazar su
                        solicitud de restricción. </span></p>

                <p><b><u><span>Derecho
                                de oposición</span></u></b><span>: corresponde al derecho a oponerse a que
                        el responsable procese sus datos para un propósito específico, en ciertas
                        circunstancias previstas por la ley y relacionadas con su situación personal. </span></p>

                <p><b><u><span>Derecho
                                a la portabilidad de los datos</span></u></b><span>: este es el derecho del interesado a
                        solicitar sus datos personales en un formato estructurado, de uso común,
                        legible por máquina e interoperable y a transferirlos a otro controlador de
                        datos, siempre que el responsable procese sus datos por medios automatizados. </span></p>

                <p><b><u><span>Derecho
                                a no estar sujeto a decisiones individuales automatizadas</span></u></b><span>: corresponde
                        al derecho del interesado a solicitar al responsable, en determinadas
                        circunstancias, que no le someta a una decisión basada únicamente en el
                        procesamiento automatizado de sus datos, incluida la elaboración de perfiles,
                        que le produzca efectos legales o que le afecte significativamente de manera
                        similar.</span></p>

                <p><span>Con carácter general, el
                        interesado podrá ejercer estos derechos en cualquier momento y de forma
                        gratuita poniéndose en contacto con Telefónica a través de </span><span lang=ES-TRAD><a href="mailto:dpo_telefonicasa@telefonica.com"><span lang=ES>dpo_telefonicasa@telefonica.com</span></a></span><span> <span> </span>

                    </span></p>

                <p><span>Es importante tener en
                        cuenta que el interesado deberá especificar claramente qué derecho está
                        ejerciendo y aportar una copia de un documento que acredite su identidad.</span></p>

                <p><span>Cualquier ejercicio de
                        derechos se contestará en el plazo de un mes, prorrogable a dos meses si fuera
                        necesario, teniendo en cuenta la complejidad de la solicitud y el número de
                        solicitudes.</span></p>

                <p><span>Por último, en el caso de
                        que el interesado no esté de acuerdo con la forma en la que Telefónica trata
                        sus datos, tiene derecho a presentar una reclamación ante la autoridad nacional
                        de control dirigiéndose a la Agencia Española de Protección de Datos, cuyos
                        datos de contacto son los siguientes:</span></p>

                <p><span>Agencia
                        Española de Protección de Datos</span></p>

                <p><span>C/
                        Jorge Juan, 6. 28001 – Madrid</span></p>

                <p><span lang=ES-TRAD><a href="https://www.aepd.es/es"><span>Agencia
                                Española de Protección de Datos | AEPD</span></a></span><span lang=ES-TRAD>

                    </span></p>
            </div>

            <span><br clear=all>
            </span>

            <div class=WordSection8>

                <p class=MsoNormal><span>
                        <o:p>&nbsp;</o:p>
                    </span></p>

                <h1><a name="_Toc124335148">
                        <span><span>9.<span>&nbsp;&nbsp;
                                </span></span></span>
                        <span>Cambios
                            a esta Política</span>
                    </a><span>

                    </span></h1>

                <p class=MsoNormal><span>Telefónica se reserva el
                        derecho de actualizar la presente Política de Privacidad en cualquier momento.
                        Dicha actualización será hecha pública por Telefónica, en todo caso, con el
                        aviso legalmente exigido con carácter previo a su entrada en vigor. </span></p>

                <p class=MsoNormal><span>Además, se comunicará
                        directamente al interesado en el caso de que afecte a sus derechos o libertades
                        o cuando, por ejemplo, la inclusión de una nueva actividad de tratamiento
                        requiera el consentimiento del interesado o modifique el alcance del interés
                        legítimo que posibilite el tratamiento.</span><span>

                    </span></p>

                <p class=MsoNormal><span>
                        <o:p>&nbsp;</o:p>
                    </span></p>

                <p class=MsoNormal><b><span>Última
                            actualización: 12/01/2023</span></b></p>

                <table class=TablaTelefonica border=0 cellspacing=0 cellpadding=0>
                    <tr>
                        <td width=567>
                            <p class=MsoNormal align=center><span>
                                    <o:p>&nbsp;</o:p>
                                </span></p>
                        </td>
                    </tr>
                    <tr>
                        <td width=567>
                            <p class=EstiloCabecera><span class=URL><b><span><span>  </span>www.telefonica.c</span></b></span><span class=URL><b><span>om</span></b></span><b><span>

                                    </span></b></p>
                        </td>
                    </tr>
                </table>

                <p class=MsoNormal><span>
                        <o:p>&nbsp;</o:p>
                    </span></p>
            </div>
        </div>
    </div>
    <?php getfooter() ?>
</body>

</html>
