<!DOCTYPE html>
<html lang="es">

<head>
    <title>Perfil de Usuario</title>
    <?php getheader("Perfil de Usuario", false) ?>
    <script src="./js/modules/profileModule.js" type="module" integrity="<?php echo "sha384-" . base64_encode(hash_file('sha384', "./js/modules/profileModule.js", true)) ?>" crossorigin="anonymous"></script>
</head>

<body class="d-flex flex-column h-100">
    <?php getmenu() ?>
    <div class="container">
        <div class="row mb-4">
            <div class="col-12">
                <div class="p-3 border rounded mb-3">
                    <h4>Información de Usuario</h4>
                    <div id="info-user" class="row">
                        <div class="col-md-6">
                            <p>ID: <span id="userId"></span></p>
                            <p>Correo: <span id="userEmail"></span></p>
                        </div>
                        <div class="col-md-6">
                            <p>Roles: <span id="userRoles"></span></p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-12">
                <div class="p-3 border rounded mb-3">
                    <h5>Gestión de Tokens</h5>
                    <p>Administre aquí los tokens de acceso.</p>
                    <div id="table-tokens-container">
                        <table class="table" id="table-tokens">
                            <thead>
                                <tr>
                                    <th>Nombre del Token</th>
                                    <th>Fecha de Creación</th>
                                    <th>Fecha de Expiración</th>
                                    <th>Acciones</th>
                                </tr>
                            </thead>
                            <tbody id="table-tokens-body"></tbody>
                        </table>
                        <button id="new-token" class="btn btn-primary mb-2">Crear Nuevo Token</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php getfooter() ?>
</body>

</html>
