<!DOCTYPE html>
<html lang="es">

<head>
    <title>EAE - Evaluación de la Arquitectura Empresarial</title>
    <?php getheader("EAE - Evaluación de la Arquitectura Empresarial", false) ?>
    <script src="https://www.gstatic.com/charts/loader.js" type="text/javascript"></script>
    <script src="./js/vendor/html2canvas.min.js" type="text/javascript" integrity="<?php echo "sha384-" . base64_encode(hash_file('sha384', "./js/vendor/html2canvas.min.js", true)) ?>" crossorigin="anonymous"></script>
    <script type="module" src="./js/modules/servicios/servicios.js" type="text/javascript" integrity="<?php echo "sha384-" . base64_encode(hash_file('sha384', "./js/modules/servicios/servicios.js", true)) ?>" crossorigin="anonymous"></script>
</head>

<body class="d-flex flex-column h-100">
    <?php getmenu() ?>
    <div class='container'>
        <div class='fixed-bottom alertas'></div>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb breadlist">
                <li class="breadcrumb-item active" aria-current="page"><a class="b-home" href="#">Inicio</a></li>
            </ol>
        </nav>
        <div class='row botones margintop-12'>
            <div class='col-sm'>
                <div class="d-flex align-items-center justify-content-between">
                    <div>
                        <button class="btn btn-primary btn-newactivo">Nuevo Activo</button>
                        <button class="btn btn-primary btn-importar">Importar activos</button>
                        <a href="./downloadExample" class="btn btn-primary">Ejemplo de importación</a>
                        <span class="badge bg-dark pointer show-pro bg-left">Entorno </span>
                        <span class="badge bg-primary pointer show-pro bg-right">PRO</span>
                        <span class="badge bg-primary pointer show-filtros">Filtros</span>
                    </div>
                    <div>
                        <input class="inputExcel excelActivos mshide" type="file" name="excelActivos" />
                        <a class="btn btn-primary btn-arbol">Descargar árbol servicios</a>
                    </div>
                </div>
            </div>
        </div>

        <div class='row visual mshide'>
            <div id="esquemavisual">
            </div>
            <div class='row'>
                <div class='col text-end'>
                    <img class="icono download downloadTree" src="./img/excel.svg" alt="descargar excel" title="Descargar arquitectura en Excel">
                    <img class="icono download downloadEsquema" src="./img/download.svg" alt="descargar modelo" title="Descargar imagen de modelo">
                </div>
            </div>
        </div>
        <div class="info-filtro col-12">
            <div class="d-flex justify-content-end">
                <div class="d-flex flex-column">
                    <small class="tipo-filtrado">Filtrando por: Servicios</small>
                    <small class="tipo-servicio">Mostrando: Todos</small>
                </div>
            </div>
        </div>
        <div class='row activos'>
            <div class='col-12 response'>
            </div>
        </div>
    </div>
    <?php getfooter(); ?>
</body>

</html>
