<!DOCTYPE html>
<html lang="es">

<head>
    <title>Solicitud de pruebas</title>
    <?php getheader("Solicitud de pruebas", false) ?>
    <link rel="stylesheet" href="./css/home.css">
</head>

<body class="d-flex flex-column h-100">
    <?php getmenu() ?>
    <div class="container">
        <div class="row">
            <div class="auto">
                <div class="card d-flex flex-column">
                    <div class="text-center">
                        <img src="./img/focus.svg" class="card-img-top cardImg mt-4 mb-3" alt="icono focus">
                    </div>
                    <div class="card-body d-flex flex-column justify-content-between">
                        <div>
                            <b>
                                <h2 class="card-title">Formulario Pentest</h2>
                            </b>
                            <h3 class="card-text">Formulario para solicitar un pentest a la Unidad de Desarrollo Seguro de TID.</h3>
                        </div>
                        <div class="mt-auto">
                            <a href="./pentestRequest" class="btn btn-secondary my-btn">Entrar</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 mb-5 mshide">
                <div class="card d-flex flex-column">
                    <div class="text-center">
                        <img src="./img/arquitectura.svg" class="card-img-top cardImg mt-4 mb-3" alt="icono arquitectura">
                    </div>
                    <div class="card-body d-flex flex-column justify-content-between">
                        <div>
                            <b>
                                <h2 class="card-title">Formulario Arquitectura</h2>
                            </b>
                            <h3 class="card-text">Próximamente........</h3>
                        </div>
                        <div class="mt-auto">
                            <a href="./pentestRequest" class="btn btn-secondary my-btn">Entrar</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php getfooter() ?>
</body>

</html>
