<!DOCTYPE html>
<html lang="es">

<head>
    <title>Login</title>
    <?php getheader("Login", false) ?>
</head>

<body class="d-flex flex-column h-100">
    <?php getmenu() ?>
    <div class="container">
        <div class="row">
            <div class="col-sm">
                Logueado correctamente con O365 se le redirigirá en breves
                <div class="mshide token-sso"><input class="mshide token-value"></div>
            </div>
        </div>
    </div>
    <?php getfooter() ?>
</body>

</html>
