<!DOCTYPE html>
<html lang="es">

<head>
    <title>Términos legales</title>
    <?php getheader("Términos legales", false, false) ?>
</head>

<body class="d-flex flex-column h-100">
    <?php getmenu() ?>
    <div class="container">
        <div class="row">
            <div class="col-sm">
                <ol>
                    <h4>
                        IMPORTANTE: POR FAVOR LEA CUIDADOSAMENTE ESTOS TÉRMINOS Y CONDICIONES ANTES DE CONTINUAR CON EL USO DE ESTE SERVICIO.
                    </h4>

                    <p>Estos términos y condiciones de uso (en adelante, los “Términos”) constituyen un acuerdo entre Telefonica Digital
                        España S.L.U, con código de identificación fiscal (CIF) B-83.188.953 y con domicilio social en Madrid, calle Gran Vía
                        nº 28 28013 (también denominada "ElevenPaths") y Usted (ya sea como persona física o jurídica) con respecto al uso
                        en su nombre, del servicio, SandaS Portal (en adelante, también, “Servicio” o “SANDAS PORTAL”).</p>

                    <p>SandaS Portal es propiedad de ElevenPaths y, junto con cualquier otro servicio de seguridad gestionada que
                        ElevenPathstenga o pueda lanzar en el futuro, se engloba en los denominados "SERVICIOS DE SEGURIDAD GESTIONADA".</p>

                    <p>SandaS Portal está protegido por leyes y tratados internacionales de derechos de autor, así como por otras leyes y
                        tratados de propiedad intelectual que sean aplicables. SandaS Portal no se licencia ni se vende.</p>

                    SandaS Portal incluye:
                    <ul>
                        <li>Actualizaciones, lanzamientos, mejoras, versiones futuras;</li>
                        <li>Suplementos o componentes de software asociados;</li>
                        <li>Materiales impresos y documentación online o electrónica;</li>
                        <li>Servicios basados en Internet; y</li>
                        <li>Servicios de soporte, a menos que otros términos acompañen dichos servicios. Si es así, se aplicarán dichos
                            términos.</li>
                    </ul>

                    <p>La aceptación sin reservas de los Términos deviene indispensable para la prestación del Servicio por parte de
                        ElevenPaths.</p>

                    <p>Mediante (i) la aceptación electrónica de estos Términos o (ii) el uso de SandaS Portal, Usted acepta completa e
                        inequívocamente haber leído, entendido y aceptado estar sujeto a estos Términos sin modificación. Si no los acepta o
                        no tiene la intención de estar legalmente vinculado a los Términos, no acceda ni utilice de ningún modo SandaS Portal.</p>

                    <li>
                        OBJETO
                        <p>
                            Estos Términos no suponen para ElevenPaths ninguna obligación de actualizar ningún software, ni de emitir
                            ninguna versión, lanzamiento o actualización de SandaS Portal.
                        </p>
                        <p>
                            Estos Términos no suponen para ElevenPaths ninguna obligación de actualizar ningún software, ni de emitir
                            ninguna versión, lanzamiento o actualización de SandaS Portal.
                        </p>
                    </li>
                    <li>
                        DESCRIPCION DEL SERVICIO
                        <p>
                            SandaS es la plataforma mediante la cual Telefónica ofrece los servicios de seguridad gestionada. SandaS
                            incluye un conjunto de herramientas para la automatización y visualización de los servicios de seguridad
                            gestionada ofrecidos desde los SOCs de Telefónica.
                        </p>
                        <p>
                            En concreto, SandaS Portal, es el portal web desde el que Usted puede consultar e interactuar con los
                            servicios de seguridad gestionada que tiene contratados con Telefónica. SandaS Portal incluye:
                        </p>
                        <ul>
                            <li>Cuadros de mando para la consulta del estado de seguridad corporativa.</li>
                            <li>Seguimiento al ciclo de vida de los tickets.</li>
                            <li>Repositorio documental.</li>
                            <li>Módulo de informes.</li>
                            <li>Cuadros de mando del servicio de monitorización de seguridad.</li>
                            <li>Acceso a la lista de alertas y su detalle.</li>
                            <li>Consulta de los dispositivos gestionados y su estado</li>
                            <li>Acceso single-sign-on a otros servicios de seguridad.</li>
                        </ul>

                        <p>
                            SandaS Portal se encuentra accesible mediante la siguiente dirección web:
                            <a href="https://cybersecurity.telefonica.com" target="_blank" rel="noopener noreferrer">https://cybersecurity.telefonica.com</a>
                        </p>
                    </li>

                    <li>
                        PRESTACION DEL SERVICIO
                        <ol>
                            <p>
                                SandaS Portal puede ser utilizado accediendo a
                                <a href="https://cybersecurity.telefonica.com" target="_blank" rel="noopener noreferrer">https://cybersecurity.telefonica.com</a>,
                                requiriendo para ello la utilización de una conexión a Internet en conjunción con un dispositivo electrónico
                                que cuente con un navegador web compatible, elementos que por quedar fuera del objeto de estos Términos
                                deberán ser provistos por Usted.
                            </p>

                            <li>Requisitos Técnicos para la prestación del servicio</li>

                            <p>
                                A continuación, se reseñan las especificaciones técnicas que Usted deberá observar para poder acceder y usar
                                el Servicio. Estas especificaciones tienen carácter de mínimos, pudiendo variar el rendimiento de SandaS
                                Portal por diversas causas técnicas ajenas a ElevenPaths, tales como p.ej., ancho de banda disponible,
                                tipología del dispositivo electrónico utilizado por Usted, versión del sistema operativo o navegador
                                utilizado, etc.
                            </p>
                            <p>
                                De producirse un cambio en los requisitos técnicos mínimos para el acceso al Servicio, ElevenPaths pondrá la
                                información a su disposición mediante correcto electrónico o en la página web
                                <a href="https://cybersecurity.telefonica.com" target="_blank" rel="noopener noreferrer">https://cybersecurity.telefonica.com</a>
                            </p>

                            <li>Conexión a internet</li>

                            <p>
                                El acceso SandaS Portal requiere de la utilización de una conexión a Internet por parte de Usted con un
                                ancho de banda mínimo simétrico dedicado al Servicio de un megabit por segundo (1Mb/s) para el correcto
                                funcionamiento del mismo.
                            </p>
                            <p>
                                Es su responsabilidad que la configuración de la conexión a Internet mencionada sea la necesaria para la
                                provisión del Servicio, en ningún caso ElevenPaths configurará parámetros de la misma.
                            </p>

                            <li>Navegador web compatible</li>

                            <p>
                                Para la correcta prestación del Servicio, Usted deberá utilizar las últimas versiones actualizados de los
                                navegadores web: Microsoft, Internet Explorer o Edge, Mozilla Firefox o Google Chrome, así como cualquier
                                otro que pudiera resultar ser compatible con el Servicio y siguiendo las especificaciones técnicas descritas
                                en estas Condiciones Generales. En caso de duda, Usted deberá consultar a través de
                                <a href="mailto:operations@elevenpaths.com">operations@elevenpaths.com</a>
                            </p>
                            <p>
                                La utilización por su parte de extensiones o complementos del navegador pueden afectar negativamente e
                                incluso impedir la correcta prestación del Servicio, quedando ElevenPaths exenta de la responsabilidad que
                                pudiera derivarse de las mismas.
                            </p>

                            <li>Puesta en marcha del Servicio</li>

                            <p>
                                ElevenPaths hará los esfuerzos razonables para proporcionar los servicios de soporte durante el proceso de
                                registro o acceso a SandaS Portal ("Servicios de Soporte"). Cualquier solicitud de Servicios de Soporte
                                deberá enviarse a ElevenPaths a través de la siguiente dirección de correo electrónico
                                <a href="mailto:operations@elevenpaths.com">operations@elevenpaths.com</a>
                            </p>
                        </ol>
                    </li>
                    <li>
                        OBLIGACIONES DEL CLIENTE
                        <ol>
                            <li>
                                Uso
                            </li>
                            <p>
                                Para respetar el uso de SandaS Portal, Usted además acepta que Usted (y que los Usuarios Finales como
                                vienen explicados más adelante):
                            </p>
                            <p>
                                (a) deberá cumplir con las instrucciones de ElevenPaths relacionadas con el uso de SandaS Portal”:
                            </p>
                            <p>
                                (b) no deberá (i) hacer uso de SandaS Portal de manera que este sea inconsistente con el uso razonable y de
                                buena fe de SandaS Portal, (ii) hacer uso de SandaS Portal en manera que, a juicio de ElevenPaths, afecte
                                (o sea probable que afecte) directamente a SandaS Portal o a otros clientes de ElevenPaths, (iii) hacer uso
                                de SandaS Portal en la manera que pueda perturbar, interferir, distorsionar o dañar los sistemas de
                                ElevenPaths, (iv) hacer uso de SandaS Portal de manera fraudulenta o en relación con un delito, (v) hacer
                                uso de SandaS Portal para enviar, recibir, almacenar o comunicar conscientemente cualquier material que sea
                                ilegal, desprotegido, ofensivo, abusivo, indecente, difamatorio, obsceno o amenazante, suponga una molestia
                                o un engaño o cualquier otro tipo de material susceptible de causar una ofensa, (vi) hacer uso de SandaS
                                Portal para acosar, espiar, molestar, causar angustia o ansiedad innecesaria a cualquier persona, o para
                                hacerse pasar como otra persona o actuar de manera que pueda ser razonablemente considerado como desagradable,
                                o que es de alguna manera perjudicial para terceros, (vii) hacer uso de SandaS Portal de una manera que
                                contravenga cualquier licencia, código de prácticas, instrucciones o directrices emitidas por una autoridad
                                reguladora pertinente, (viii) ) hacer uso de SandaS Portal para enviar spam o enviar material publicitario o
                                promocional no solicitado, (ix) hacer uso de SandaS Portal para enviar o transmitir nada, contenido o
                                material software que consista o contenga virus, (x) hacer uso de SandaS Portal de una manera que pueda dañar
                                la reputación de ElevenPaths o de cualquier entidad dentro del Grupo Telefónica, la reputación de los
                                SERVICIOS DE SEGURIDAD GESTIONADA o de otro modo llevar a ElevenPaths a su descrédito o la reputación de
                                terceros, (xi) hacer uso de SandaS Portal de ninguna manera que viole derechos de autor, marcas registradas,
                                la confidencialidad, privacidad o que se use para infringir los derechos de propiedad intelectual o
                                industrial de terceros, (xii) poseer o seguir manteniendo las licencias, consentimientos y/o notificaciones
                                requeridos bajo cualquier ley, reglamento y/u orden administrativa aplicable para recibir y utilizar SandaS
                                Portal si los hubiere.
                            </p>
                            <p>
                                (c) usará SandaS Portal únicamente (i) para su uso interno con sus operaciones comerciales ordinarias, (ii)
                                de acuerdo con todas las leyes y regulaciones aplicables, y (iii) como se provee en estos Términos y de
                                cualquier documentación que forme parte de SandaS Portal;
                            </p>
                            <p>
                                (d) no utilizará ninguna documentación que forme parte de SandaS Portal excepto para apoyar su uso autorizado;
                            </p>
                            <p>
                                (e) a excepción de lo expresamente establecido en estos Términos, no (i) modificará, adaptará, traducirá,
                                duplicará, desensamblará, descompilará, montará de nuevo, invertir la compilación o realizará ingeniería
                                inversa ni tomará medidas similares con respecto a SandaS Portal para cualquier propósito, o (ii) intentará
                                descubrir el código fuente o los algoritmos subyacentes de SandaS Portal (a menos que la ley vigente lo
                                prohíba y luego, sólo en la medida específicamente permitida por la ley aplicable, y sólo después de
                                proporcionar a ElevenPaths una razonable notificación escrita por anticipado y con la oportunidad de responder);
                            </p>
                            <p>
                                (f) con el fin de diseñar, modificar o desarrollar software o servicios similares en propósito, alcance o
                                función a SandaS Portal, no participará en análisis competitivo, benchmarking, uso, evaluación o
                                visualización de SandaS Portal ni creará ningún derivado basados en SandaS Portal, ya sea para su uso
                                interno, licenciamiento o reventa;
                            </p>
                            <p>
                                (g) deberá cumplir con las leyes vigentes y no permitirá que ninguna de las partes, ya sea directamente o en
                                su nombre, incumpla o viole cualquiera de estas restricciones; y
                            </p>
                            <p>
                                (h) respecto al mantenimiento de avisos de derechos de autor, no quitará o alterará ninguna notificación de
                                derechos de autor en ninguna de las copias de “SandaS Portal”.
                            </p>
                        </ol>
                    </li>


                    <li>
                        OBLIGACIONES DE ELEVENPATHS

                        <ol>
                            <li>
                                Acceso
                                <p>
                                    ElevenPaths le otorga el derecho de acceder y usar SandaS Portal sobre los archivos para los cuales
                                    fue diseñado.
                                </p>
                            </li>
                            <li>
                                Disponibilidad del Servicio

                                <p>
                                    ElevenPaths hará sus mejores esfuerzos por proporcionarle la máxima disponibilidad y acceso continuo
                                    a SandaS Portal.
                                </p>
                            </li>
                            <li>
                                Servicio de atención al cliente y asistencia técnica

                                <p>
                                    ElevenPaths le prestará un servicio adicional de asistencia técnica en relación a SANDAS PORTAL
                                    mediante correo electrónico dirigido a
                                    <a href="mailto:operations@elevenpaths.com">operations@elevenpaths.com</a>.
                                </p>
                            </li>
                        </ol>
                    </li>
                    <li>
                        SERVICIOS DE SOPORTE

                        <p>
                            Las solicitudes de Servicios de Soporte serán atendidas por ElevenPaths tan pronto como sea posible mediante
                            correo electrónico dirigido a <a href="mailto:operations@elevenpaths.com">operations@elevenpaths.com</a>.
                        </p>

                    </li>
                    <li>
                        TARIFAS

                        <p>
                            Debe tomar en consideración que la utilización del servicio " SandaS Portal " está vinculado a la
                            contratación con alguna de las empresas del grupo Telefónica de Servicios de Seguridad Gestionada.
                        </p>

                    </li>
                    <li>
                        DURACIÓN Y TERMINACIÓN

                        <p>
                            La vigencia de estos Términos se mantendrá siempre y cuando exista una relación contractual entre Usted y
                            alguna empresa del grupo Telefónica acerca de Servicios de Seguridad Gestionada.
                        </p>
                        <p>
                            Una vez finalizado, será necesaria una nueva aceptación de estos Términos.
                        </p>
                        <p>
                            Sin perjuicio de lo anterior, ElevenPaths podrá, a su sola discreción y sin necesidad de aviso previo,
                            resolver estos Términos.
                        </p>
                        <p>
                            Además, ElevenPaths puede dar por terminado esta relación inmediatamente en caso de que (i) ElevenPaths
                            determine, a su sola discreción, que la provisión del Servicio ofrecido a Usted quede prohibido por la ley
                            aplicable o se haya vuelto impracticable o inviable por cualquier razón legal o reglamentaria, (ii)
                            ElevenPaths determine, en su sola discreción, que Usted incumple alguno de los términos y condiciones de
                            este documento o que está utilizando SandaS Portal, o está actuando, de tal manera que el uso de SandaS
                            Portal otorgado a otros clientes o sobre cualquier infraestructura relacionada con SandaS Portal puedan
                            verse adversamente afectados o (iii) ElevenPaths determine, a su sola discreción, que el uso que Usted
                            realice de S SandaS Portal (o por parte de sus Usuarios Finales) planteen un riesgo de seguridad o de
                            servicio que pueda implicar la responsabilidad de ElevenPaths o de terceros.
                        </p>
                        <p>
                            Al finalizar o expirar estos Términos, el derecho de uso de SandaS Portal finaliza automática e inmediatamente.
                        </p>
                    </li>
                    <li>
                        PROPIEDAD INTELECTUAL

                        <p>
                            Todos los títulos, incluyendo, pero no limitando, los derechos de autor, nombres, las marcas comerciales,
                            los nombres comerciales, las marcas de servicio o cualquier otra característica de identificación en SandaS
                            Portal y sus copias, tienen propiedad intelectual y son propiedad de ElevenPaths o de sus proveedores.
                        </p>
                        <p>
                            Estos Términos solo le concede el derecho limitado de usar SandaS Portal bajo los términos y restricciones
                            aquí especificados. Usted no tiene y no adquirirá ningún otro derecho, título o interés sobre este Servicio,
                            el cual tendrá en todo momento propiedad exclusiva de ElevenPaths o un tercero proveedor de licencias
                            aplicable a ElevenPaths.
                        </p>
                        <p>
                            Todos los títulos y derechos de propiedad intelectual sobre el contenido al que se puede acceder mediante
                            el uso de SandaS Portal son propiedad del respectivo propietario del contenido y pueden estar protegidos por
                            las leyes y tratados de derechos de autor o de propiedad intelectual aplicables. Estos Términos no le
                            conceden ningún derecho de uso de dicho contenido. Todos los derechos no otorgados expresamente están
                            reservados por ElevenPaths.
                        </p>
                        <p>
                            Usted reconoce y acepta que ElevenPaths será el único propietario de las mejoras, actualizaciones o trabajos
                            derivados de SandaS Portal que son desarrollados por ElevenPaths durante y después del término de estos
                            Términos. Sin limitarse a lo anterior, Usted reconoce y acepta expresamente que ElevenPaths será el único
                            propietario de cualquier propiedad intelectual recién desarrollada, incluyendo pero no limitado a (i) código
                            fuente recién desarrollado, revisado o modificado y (ii) aquellos relacionados de cualquier manera con SandaS
                            Portal o con los negocios generales de ElevenPaths, independientemente de si se desarrollan, revisan o
                            modifican en respuesta a sus solicitudes, sugerencias o ideas, incluso si se realizan siendo pagadas por Usted.
                            Durante la vigencia de estos Términos, y posteriormente, no afirmará la invalidez del derecho de propiedad
                            intelectual de ElevenPaths sobre los SandaS Portal, o impugnará el derecho, título o interés de ElevenPaths
                            en el mismo y al mismo, y no deberá causar, influenciar o ayudar de ninguna manera a ninguna otra parte a
                            realizar tales afirmaciones o disputas.
                        </p>
                    </li>
                    <li>
                        SIN GARANTIAS

                        <p>
                            ElevenPaths renuncia expresamente a otorgar cualquier garantía sobre SandaS Portal. Usted entiende y acepta
                            expresamente que el uso que se dé de SandaS Portal es bajo su propio riesgo. SandaS Portal se suministra tal
                            cual y según disponibilidad. Sin ninguna garantía expresa o implícita de ningún tipo, incluyendo, pero no
                            limitado, a cualquier garantía de comerciabilidad, no infracción o aptitud de un propósito en particular,
                            incluso sin garantía de que SandaS Portal cumplirán sus requisitos o el uso del Servicio pueda ser
                            ininterrumpido, oportuno, seguro o libre de errores o que los resultados que se puedan obtener del uso
                            SandaS Portal sean precisos o confiables o que la calidad de SandaS Portal satisfaga sus expectativas.
                            ElevenPaths no garantiza ni asume la responsabilidad de la exactitud o integridad de cualquier información,
                            documentación, texto, gráficos, enlaces u otros elementos contenidos en SandaS Portal. ElevenPaths no da
                            garantías respecto de cualquier daño que pueda ser causado por la transmisión de un virus informático,
                            gusano, bomba de tiempo, bomba lógica u otro programa informático de este tipo. ElevenPaths se exime además
                            expresamente de cualquier garantía o representación a Usuarios Finales o terceras partes.
                        </p>
                        <p>
                            Usted se compromete a mantener indemne e indemnizar a ElevenPaths y sus filiales (incluyendo cualquier
                            entidad dentro del Grupo Telefónica) oficiales, agentes, empleados, anunciantes o socios de y contra (i)
                            cualquier reclamación de terceros que surja o esté relacionada con su uso (o el uso por parte de usuarios
                            finales) de SandaS Portal con respecto a estos Términos (ii) todo y cualquier daño como resultado de la
                            violación por su parte o de los Usuarios Finales de cualquier regulación o ley aplicable o como resultado de
                            cualquier otra acción relacionada con el uso SandaS Portal, o como resultado de un incumplimiento de
                            cualquiera de estos Términos por sus Usuarios Finales o como resultado del uso de los Usuarios finales de
                            SandaS Portal; (iii) de cualquier reclamación contra ElevenPaths realizada por cualquiera de sus Usuarios
                            Finales o terceros relacionados con cualquier servicio, contenido o de otro servicio suministrado o enviado
                            por Usted (directamente o a través de sus Usuarios Finales) utilizando SandaS Portal o (iv) cualquier daño a
                            cualquier equipo perteneciente a ElevenPaths o sobre cualquier otra compañía del Grupo Telefónica causado
                            por su incumplimiento o incumplimiento por los Usuarios Finales de estos Términos; incluyendo cualquier
                            responsabilidad o gasto derivado de todas las reclamaciones, pérdidas, daños (reales o consecuentes),
                            demandas, juicios, costos de litigios y honorarios de abogados, o de cualquier clase y naturaleza. En tal
                            caso, ElevenPaths le proporcionará una notificación por escrito de tal demanda, pleito o acción.
                        </p>
                    </li>
                    <li>
                        LIMITACIÓN DE RESPONSABILIDAD

                        <p>
                            En ningún caso ElevenPaths será responsable de ningún daño (incluyendo, sin limitación, pérdidas de beneficios,
                            pérdida de negocio, interrupción del negocio o pérdida de información) que surjan de su uso o incapacidad de
                            usar SandaS Portal (incluyendo a sus usuarios finales), el coste de la adquisición o bienes y servicios de
                            sustitutivos, la declaración o la conducta de los servicios o productos de terceros, incluso si ElevenPaths
                            ha sido avisada de la posibilidad de tales daños.
                        </p>
                        <p>
                            En ningún caso ElevenPaths será responsable por la pérdida de datos o por daños indirectos, especiales,
                            incidentales o consecuenciales (incluyendo pérdidas o pérdidas de negocio, ya sean directas o indirectas,
                            pérdida o corrupción de datos), o por cualquier otra pérdida indirecta o consecuente o por daños basados en
                            estos Términos, agravio u otra manera.
                        </p>
                        <p>
                            ElevenPaths no tendrá ninguna responsabilidad con respecto al contenido de SandaS Portal o cualquier parte
                            del Servicio, incluyendo, pero no limitado a errores u omisiones contenidos, calumnias, infracciones de
                            derechos de publicidad, privacidad, derechos de marca, interrupción de negocios, daños personales, pérdida
                            de privacidad, derechos morales o la divulgación de información confidencial.
                        </p>
                        <p>
                            En cualquier caso, la responsabilidad máxima agregada de ElevenPaths por todos los daños que surjan de o
                            relacionados con estos Términos o SandaS Portal se limitará al cincuenta por cierto (50%) de la tarifa
                            abonada por su parte por el derecho de acceso y uso de SandaS Portal y recibida por ElevenPaths
                            posteriormente a los últimos doce (12) meses inmediatamente anteriores al evento que dio lugar a la reclamación.
                        </p>
                        <p>
                            Nada en este acuerdo excluirá o restringirá la responsabilidad de cualquiera de las partes por: (i) muerte
                            o lesión personal resultante de la negligencia de esa parte; o (ii) fraude o declaración falsa o tergiversada.
                        </p>
                        <p>
                            Nada en este acuerdo excluirá o restringirá la responsabilidad de cualquiera de las partes con respecto a
                            cualquier responsabilidad que no pueda ser excluida o restringida por la ley.
                        </p>
                    </li>
                    <li>
                        CONFIDENCIALIDAD

                        <p>
                            Usted se compromete a tratar de forma estrictamente privada y confidencial y no revelar a terceros ninguna
                            información, datos, noticias o documentos en cualquier medio relacionado con SandaS Portal que obtenga o
                            reciba como resultado de la celebración o ejecución de estos Términos (La "Información confidencial").
                        </p>

                        <p>
                            No se considerará incumplido el compromiso establecido en el párrafo anterior si la información, las
                            noticias, los datos y / o los documentos ya son de dominio público cuando se revelan o la divulgación de
                            dicha información es requerida por la ley o una autoridad competente ordena la total o parcial divulgación
                            de la Información Confidencial.
                        </p>

                        <p>
                            Para los propósitos de esta sección, la Información Confidencial también incluye estos Términos, incluyendo
                            la consideración relevante, el sistema de ElevenPaths, cualquier documento, oferta de negocio, información o
                            presentación que le haya sido dada por ElevenPaths relacionada con la tecnología de los socios comerciales
                            de ElevenPaths, actividades promocionales y de marketing, finanzas y otros asuntos comerciales.
                        </p>

                        <p>
                            Las obligaciones de confidencialidad establecidas en este documento perdurarán a la terminación de estos
                            Términos y continuarán hasta que se aplique cualquiera de las excepciones incluidas en este artículo.
                        </p>

                        <p>
                            Si Usted es requerido por estatuto, ley o regulación aplicable o por una autoridad legal o reguladora, para
                            proceder a revelar cualquier Información Confidencial, deberá notificar adecuadamente a ElevenPaths (si la
                            ley, la autoridad reguladora o la autoridad pertinente lo permite) tal necesidad para que la parte afectada
                            pueda solicitar oportunamente una orden de protección u otro remedio apropiado o renunciar al cumplimiento
                            de los términos de esta sección. Usted también acepta cooperar con ElevenPaths en sus esfuerzos para obtener
                            tal orden de protección u otro recurso. En caso de que no se obtenga tal orden de protección u otro recurso,
                            Usted deberá permitir que en el presente documento solo se proporcione la porción de la Información
                            Confidencial que sea aconsejada por la opinión de un abogado que legalmente deberá revelar y que hará los
                            esfuerzos razonables para obtener garantías de que el tratamiento confidencial será aplicado a tal
                            Información Confidencial.
                        </p>

                    </li>
                    <li>
                        LEY Y JURISDICCIÓN

                        <p>
                            Estos Términos se regirán por la Ley Española.
                        </p>

                        <p>
                            Las partes acuerdan someter cualquier desacuerdo en la interpretación y ejecución de estos Términos a los
                            Juzgados y tribunales de la ciudad de Madrid.
                        </p>

                    </li>
                    <li>
                        ASIGNACION Y SUBCONTRATACIÓN

                        <p>
                            Usted no puede asignar estos Términos ni transferir de ninguna manera sus derechos u obligaciones, incluyendo
                            credenciales o cualquier otro derecho, sin el previo consentimiento por escrito de ElevenPaths.
                        </p>

                        <p>
                            ElevenPaths, previa notificación escrita (incluyendo el correo electrónico) y sin su consentimiento, podrá
                            ceder o transferir estos Términos a terceros, ya sea un miembro del Grupo Telefónica o no.
                        </p>

                        <p>
                            ElevenPaths podrá en cualquier momento subcontratar parte o la totalidad de sus obligaciones bajo este contrato.
                        </p>

                    </li>
                    <li>
                        PUBLICIDAD

                        <p>
                            ElevenPaths puede usar su nombre y /o logotipo en una lista de clientes utilizados en materiales de mercado
                            siempre que Usted dé su consentimiento a ElevenPaths por correo electrónico en la solicitud pertinente
                            enviada por ElevenPaths.
                        </p>
                        <p>
                            Dentro de los cuarenta y cinco (45) días de la firma de estos Términos, ElevenPaths puede publicar un
                            comunicado de prensa anunciando su relación con Usted como cliente, siempre que tenga la oportunidad de
                            revisar y aprobar el comunicado de prensa.
                        </p>

                    </li>
                    <li>
                        PRIVACIDAD
                        <ul>
                            <li>
                                Datos objeto de tratamiento y finalidad
                            </li>
                            <p>
                                Para poder ofrecer SandaS Portal, ElevenPaths deberá tratar la siguiente información:
                            </p>
                            <p>
                                - Dirección de e-mail del usuario que accede al portal.
                            </p>
                            <p>
                                - Nombre y apellidos del usuario que accede al portal.
                            </p>
                            <p>
                                - Dirección IP del usuario que accede al portal.
                            </p>
                            <p>
                                La recogida y tratamiento de dicha información se realizará con la finalidad de:
                            </p>
                            <p>
                                - El registro del usuario que accede.
                            </p>
                            <p>
                                - Verificar la cuenta de acceso.
                            </p>
                            <p>
                                - Control de privilegios para el acceso a la información de seguridad corporativa.
                            </p>
                            <p></p>
                            <p>
                                - Informar al usuario del último acceso efectuado con su identidad.
                            </p>
                            <li>
                                Protección de datos personales
                            </li>
                            <p>
                                Todos los datos personales que sean facilitados por el usuario como consecuencia de la utilización del
                                Servicio serán recogidos y tratados de conformidad con la legislación vigente en materia de protección
                                de datos perso
                            </p>
                            <p>
                                ElevenPaths, como responsable del tratamiento de dichos datos, se compromete a:
                            </p>
                            <p>
                                - No utilizar, en ningún caso, la información que se le facilita para prestar otro servicio.
                            </p>
                            <p>
                                - No destinar los datos de carácter personal a finalidades distintas de las que figuran en este documento.
                            </p>
                            <p>
                                - Adoptar las medidas necesarias para asegurar que los datos sean manejados únicamente por aquellas
                                personas cuya intervención sea precisa para la prestación del Servicio.
                            </p>
                            <p>
                                - Tratar los datos de carácter personal con la máxima cautela con el fin de garantizar su
                                confidencialidad e integridad, adoptando las medidas de seguridad técnicas y organizativas necesarias en
                                lo que respecta a la custodia, almacenamiento y conservación de los datos con el fin de evitar su
                                alteración, pérdida, tratamiento o acceso no autorizado.
                            </p>
                            <p>
                                - Destruir los datos de carácter personal, una vez cumplida la prestación del Servicio o cuando el
                                usuario seleccione su borrado, mediante un procedimiento dotado de las máximas garantías, sin conservar
                                copia alguna de los mismos y sin que ninguna persona externa, física o jurídica, tenga conocimiento
                                de los datos.
                            </p>
                            <p>
                                - No comunicar los datos personales, ni siquiera para su conservación, a terceras personas excepto
                                cuando sea necesario:
                            </p>
                            <p>
                                o Cumplir con la ley aplicable, procedimientos regulatorios o legales o a las exigencias
                                gubernamentales vigentes.
                            </p>
                            <p>
                                o Hacer cumplir los términos del Servicio aplicables incluyendo la investigación de potenciales
                                violaciones de los presentes Términos.
                            </p>
                            <p>
                                o Detectar, prevenir y tratar problemas técnicos, de seguridad y relacionados con el fraude, que
                                puedan surgir del uso del Servicio.
                            </p>
                            <p>
                                o Proteger los derechos, la propiedad y seguridad tanto de ElevenPaths como de los usuarios ante
                                posibles daños de acuerdo a lo requerido por la norma.
                            </p>
                            <p>
                                - En caso de que el usuario quiera acceder, corregir, eliminar o tratar cualquiera de los datos, así
                                como solicitar información sobre ellos, podrá ponerse en contacto con ElevenPaths en la dirección de
                                correo señalada a continuación: <a href="mailto:operations@elevenpaths.com">operations@elevenpaths.com</a>.
                            </p>
                        </ul>
                    </li>
                    <li>
                        MODIFICACIÓN CONTRACTUAL

                        <p>
                            ElevenPaths podrá modificar estos Términos por (i) cambios tecnológicos, (ii) cambios normativos que afecten
                            al Servicio, o (iii) por la propia evolución del Servicio, publicándolo en la dirección web
                            <a href="https://cybersecurity.telefonica.com" target="_blank" rel="noopener noreferrer">https://cybersecurity.telefonica.com</a>,
                            para su información.
                        </p>
                    </li>
                    <li>
                        CONSERVACIÓN E INTEGRIDAD DE ESTOS TÉRMINOS Y NO RENUNCIA

                        <p>
                            La declaración de nulidad o invalidez de cualquier cláusula de estos Términos, salvo que tengan carácter
                            esencial, no afectará a la validez y eficacia de las demás cláusulas.
                        </p>
                        <p>
                            El fracaso o el retraso de cualquiera de las partes implicadas en estos Términos para ejercer o hacer cumplir
                            cualquier derecho, poder o recurso bajo estos Términos no será considerado que se trata de una renuncia de
                            tal derecho, poder o recurso.
                        </p>
                    </li>
                    <li>
                        NOTIFICACIONES

                        <p>
                            A Usted: Salvo que se establezca lo contrario en este documento, los avisos hechos por ElevenPaths bajo estos
                            Términos le serán proporcionados a través de la dirección de correo electrónico que Usted haya proporcionado
                            a ElevenPaths en el proceso de registro seguido para adquirir el derecho de acceso y uso de SandaS Portal o
                            en cualquier dirección de correo electrónico actualizado que Usted haya proporcionado a ElevenPaths y/o
                            filiales. Es responsabilidad suya mantener su dirección de correo electrónico actualizada y se considerará
                            que ha recibido cualquier correo electrónico enviado a dicha dirección, si es enviado desde ElevenPaths y/o
                            filiales, independientemente de si realmente recibió el correo electrónico.
                        </p>
                        <p>
                            A ElevenPaths: Para las notificaciones que Usted envíe a ElevenPaths bajo estos Términos y para preguntas
                            con respecto a estos Términos o SandaS Portal, puede contactarnos a través de la dirección
                            <a href="mailto:elevenpaths@elevenpaths.com.">elevenpaths@elevenpaths.com.</a>
                        </p>
                        <p>
                            Cualquier pregunta de soporte o consulta relacionada con SandaS Portal deberá hacerla al contacto descrito
                            anteriormente.
                        </p>
                    </li>
                </ol>
            </div>
        </div>
    </div>
    <?php getfooter() ?>
</body>

</html>
