<!DOCTYPE html>
<html lang="es">

<head>
        <title>Términos de uso</title>
        <?php getheader("Términos de uso", false, false) ?>
</head>

<body class="d-flex flex-column h-100">
        <?php getmenu() ?>
        <div class="container">
                <div class="row">
                        <div class="col-sm">
                                <div class=WordSection1>

                                        <p class=paragraph><span class=normaltextrun><b><span>TÉRMINOS DE USO DE 11 CERT</span></b></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>&nbsp;</span></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>&nbsp;</span></span></p>

                                        <p class=paragraph><b><span>1.<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></b><span class=normaltextrun><b><span>OBJETO</span></b></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>&nbsp;</span></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>El
                                                                objeto de estos Términos y Condiciones es regular el uso de 11 Cert </span></span><span class=eop><span>por
                                                                parte de sus usuarios.</span></span></p>

                                        <p class=paragraph><span>&nbsp;</span></p>

                                        <p class=paragraph><span class=normaltextrun><b><span>2.<span>&nbsp;&nbsp;&nbsp;&nbsp;</span></span></b></span><span class=normaltextrun><b><span>¿QUÉ
                                                                        ES 11 CERT?</span></b></span></p>

                                        <p class=paragraph><span class=normaltextrun><b><span>&nbsp;</span></b></span></p>

                                        <p class=paragraph><span class=normaltextrun><b><span>2.1.<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                                                        </span></span></b></span><span class=normaltextrun><b><span>Descripción</span></b></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>11
                                                                Cert es una solución <i>cloud</i> desarrollada por Telefónica Digital España,
                                                                S.L.U, con CIF. B83188953y domicilio social en Gran Vía 28, 28013 Madrid,
                                                                España (en adelante, “<b>Telefónica</b>”), que permite realizar la analítica de
                                                                riesgos y de cumplimiento regulatorio de los sistemas informáticos utilizados
                                                                por Telefónica. </span></span></p>

                                        <p class=paragraph><span class=normaltextrun><b><span>2.2.<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                                                        </span></span></b></span><span class=normaltextrun><b><span>Funcionalidades&nbsp;</span></b></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>Actualmente
                                                                11 Cert dispone de los módulos identificados a continuación. Otras
                                                                funcionalidades podrán desarrollarse conforme a las necesidades de Telefónica. </span></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>Módulo
                                                                de Gestión de Indicadores Clave de Desempeño (KPMS, por sus siglas en inglés):
                                                                es un módulo destinado para evaluar y revisar los indicadores clave de
                                                                rendimiento y las métricas de madurez de los servicios. Este módulo permite
                                                                medir el nivel de madurez de los servicios y evaluar su desempeño en relación
                                                                con objetivos predefinidos. Además, permite identificar áreas de mejora y
                                                                establecer planes de acción para alcanzar un mayor grado de eficiencia y
                                                                efectividad en la prestación de los servicios.</span></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>Módulo
                                                                de Análisis de Impacto en el Negocio (BIA, por sus siglas en inglés): es
                                                                utilizado para determinar el impacto que la interrupción o el cambio en los
                                                                servicios dados de alta en la herramienta pueden tener en el negocio. Este
                                                                módulo permite evaluar el impacto potencial de dichos eventos y establecer
                                                                medidas de mitigación adecuadas para minimizar su impacto en el negocio. De
                                                                esta manera, se pueden tomar decisiones informadas y proteger la continuidad
                                                                del negocio en caso de interrupciones o cambios inesperados en los servicios.</span></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>Módulo
                                                                de Servicios: es el que almacena y proporciona acceso a información detallada
                                                                sobre los servicios creados y sus dependencias con los tipos de activos que los
                                                                conforman. Este módulo permite tener una visión general de todos los servicios
                                                                existentes y obtener información relevante sobre ellos, como sus componentes y
                                                                dependencias. Además, los tipos de activos incluidos en este módulo son tenidos
                                                                en cuenta en otros módulos para calcular parámetros específicos.</span></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>Módulo
                                                                de Evaluación: es un procedimiento mediante el cual se determina el grado de
                                                                cumplimiento de la normativa aplicable al servicio objeto de evaluación. Dicho
                                                                módulo se basa en la realización de un cuestionario dinámico, confeccionado de
                                                                manera específica para el servicio en cuestión, cuyo propósito es obtener
                                                                información necesaria para realizar la evaluación correspondiente.</span></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>Módulo
                                                                de Seguimiento de Planes de Acciones Correctivas (PAC): es un procedimiento
                                                                mediante el cual se lleva un registro del estado de los PAC y se permite hacer
                                                                un seguimiento de su evolución. Dicho módulo incluye información relevante como
                                                                la fecha de inicio, la fecha de finalización prevista, comentarios y el
                                                                responsable de cada PAC. Con este módulo, se puede obtener una visión general
                                                                del progreso de las acciones correctivas en curso y asegurar que se están
                                                                llevando a cabo de manera oportuna y efectiva.</span></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>Módulo
                                                                de Historial de Servicio: es una herramienta que permite visualizar el
                                                                resultado de la introducción de datos en los módulos anteriores, como el módulo
                                                                de Evaluación o el módulo de Análisis de Impacto en el Negocio (BIA). Este
                                                                módulo proporciona información relevante sobre el estado de los servicios
                                                                frente a las normativas evaluadas y no evaluadas, incluyendo listados de
                                                                amenazas y estado de controles. Además, este módulo permite obtener una visión
                                                                general del progreso de los servicios en términos de cumplimiento normativo y
                                                                protección frente a riesgos.       </span></span></p>

                                        <p class=paragraph><span class=eop><span>&nbsp;</span></span></p>

                                        <p class=paragraph><span class=normaltextrun><b><span>2.3.<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                                                        </span></span></b></span><span class=normaltextrun><b><span>Requisitos para la utilización de 11
                                                                        Cert&nbsp;</span></b></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>&nbsp;</span></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>Para
                                                                acceder a 11 Cert es necesario ser empleado o colaborador de Telefónica y que
                                                                ésta te conceda un permiso de acceso y uso a la herramienta (en adelante los “<b>Usuarios</b>”).</span></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>&nbsp;</span></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>Para
                                                                la utilización de 11 Cert es necesario que el Usuario disponga de:</span></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>&nbsp;</span></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>                2.3.1
                                                                Conexión a Internet:</span></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>Para
                                                                utilizar 11 Cert es necesario contar con una conexión a Internet estable y
                                                                acceder a través de las redes privadas virtuales (VPNs) de TID/TECH o a través
                                                                de las redes seguras de Distrito Telefónica. Es importante tener en cuenta que
                                                                el rendimiento y la disponibilidad de 11 Cert pueden verse afectados por la
                                                                calidad y estabilidad de la conexión a Internet utilizada.</span></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>&nbsp;</span></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>                2.3.2
                                                                Navegador web compatible:</span></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>Para
                                                                garantizar el correcto funcionamiento de 11 Cert, se recomienda utilizar las
                                                                últimas versiones de los navegadores web compatibles, como Internet Explorer o
                                                                Edge, Firefox y Chrome. Es posible que otros navegadores también sean
                                                                compatibles con el servicio, pero no se garantiza su correcto funcionamiento.
                                                                Es importante tener en cuenta que el uso de versiones obsoletas de los navegadores
                                                                o de navegadores no compatibles puede afectar la prestación del servicio y
                                                                generar problemas de funcionamiento.                             </span></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>&nbsp;</span></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>&nbsp;</span></span></p>

                                        <p class=paragraph><span class=normaltextrun><b><span>3.<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></b></span><span class=normaltextrun><b><span>ACEPTACIÓN
                                                                        DE ESTOS TÉRMINOS Y CONDICIONES </span></b></span></p>

                                        <p class=MsoNormal><span>&nbsp;</span></p>

                                        <p class=MsoNormal><span lang=es>El acceso y uso de 11 Cert está sujeto y se rige por estos
                                                        Términos y Condiciones, así como por los avisos legales, la Política de
                                                        Privacidad y demás documentación disponible a través de 11 Cert. </span></p>

                                        <p class=MsoNormal><span lang=es>&nbsp;</span></p>

                                        <p class=MsoNormal><span lang=es>Estos Términos y Condiciones constituyen un acuerdo legalmente
                                                        vinculante entre los Usuarios y las correspondientes Empresas Usuarias de 11
                                                        Cert y Telefónica. Al hacer uso de 11 Cert estos aceptan y aceptan cumplir con estos
                                                        Términos y Condiciones. El Usuario y/o la Empresa Usuaria de 11 Cert que no esté
                                                        de acuerdo con estos Términos y Condiciones, no debe hacer uso de 11 Cert.</span></p>

                                        <p class=MsoNormal><span>&nbsp;</span></p>

                                        <p class=MsoNormal><span lang=es>Telefónica podrá modificar estos Términos y Condiciones para
                                                        reflejar la ley aplicable o por otras razones que considere necesarias. Si los
                                                        Términos y Condiciones cambian, Telefónica proporcionará un aviso en la
                                                        herramienta. El Usuario que no esté de acuerdo con los cambios realizados en los
                                                        Términos y Condiciones, debe interrumpir el uso de 11 Cert y de cualquier
                                                        material disponible a través de la herramienta.</span></p>

                                        <p class=MsoNormal><span lang=es>&nbsp;</span></p>

                                        <p class=paragraph><span class=normaltextrun><b><span>4.<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></b></span><span class=normaltextrun><b><span>VALIDEZ</span></b></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>&nbsp;</span></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>Estas
                                                                Condiciones Generales estarán vigentes de forma indefinida.</span></span></p>

                                        <p class=paragraph><span>&nbsp;</span></p>

                                        <p class=paragraph><span class=normaltextrun><b><span>5.<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></b></span><span class=normaltextrun><b><span>COMPROMISOS
                                                                        Y OBLIGACIONES</span></b></span><span class=normaltextrun><b><span>&nbsp;</span></b></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>&nbsp;</span></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>En
                                                                este apartado te explicamos los compromisos que los Usuarios adquieren en el
                                                                uso de 11 Cert y los que adquirimos en Telefónica como desarrolladores de esta
                                                                herramienta.</span></span><span class=eop><span>&nbsp;</span></span></p>

                                        <p class=paragraph><span>&nbsp;</span></p>

                                        <p class=paragraph><span>5.1.<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                                        </span></span><span class=normaltextrun><b><span>Obligaciones de los Usuarios</span></b></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>&nbsp;</span></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>Los
                                                                Usuarios se comprometen a hacer un uso responsable de 11 Cert, siempre en
                                                                consonancia con las normativas aplicables y conforme a lo establecido en estos Términos
                                                                y Condiciones. En especial, pero no limitado a esto, se comprometen a:</span></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>&nbsp;</span></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>i.<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                                                </span></span></span><span class=normaltextrun><span>Respectar la confidencialidad de la
                                                                información.</span></span><span lang=es> En 11 </span><span class=normaltextrun><span>Cert se
                                                                registra información confidencial de Telefónica, por lo cual los Usuarios deberán
                                                                en todo momento respectar la confidencialidad de la información y no divulgarla
                                                                a terceros, conforme se establece en el apartado 6 de Confidencialidad. </span></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>ii.<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                                                </span></span></span><span class=normaltextrun><span>Respectar la propiedad intelectual
                                                                de Telefónica y de terceros. Los Usuarios no pueden copiar, modificar,
                                                                distribuir, transmitir, exponer, ejecutar, publicar, licenciar, crear trabajos
                                                                derivados, transferir, alquilar, ceder o comercializar 11 Cert o su contenido.</span></span></p>

                                        <p class=paragraph><span>iii.<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                                        </span></span><span lang=es>No utilizar 11 Cert para:</span></p>

                                        <p class=paragraph><span>a.<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span lang=es>publicar,
                                                        cargar, publicar, transmitir o poner a disposición cualquier contenido que (a)
                                                        no tengas derecho a revelarlo (b) sea ilegal, perjudicial o censurable; (c)
                                                        infrinja cualquier derecho de propiedad intelectual de Telefónica o de
                                                        terceros, (d) contenga un virus de software, caballo de Troya, archivo dañado o
                                                        cualquier otro archivo o software diseñado para destruir, dañar, interrumpir o
                                                        afectar de cualquier otra forma la herramienta o funcionalidad de los equipos
                                                        informáticos de Telefónica y/o de sus proveedores;</span></p>

                                        <p class=paragraph><span>b.<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span lang=es>hacerse
                                                        pasar por otra persona o entidad, incluido, entre otros, un Usuario de 11 Cert;</span></p>

                                        <p class=paragraph><span>c.<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span lang=es>descargar
                                                        cualquier archivo o contenido de 11 Cert que sepas, o razonablemente deberías
                                                        saber, que no debe reproducirse, mostrarse, ejecutarse y / o distribuirse
                                                        legalmente;</span></p>

                                        <p class=paragraph><span>d.<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><span lang=es>interferir
                                                        o interrumpir los servidores o redes que soportan 11 Cert;</span></p>

                                        <p class=paragraph><span lang=es>iv.<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                                        </span></span><span lang=es>No intentar obtener acceso no autorizado a 11 Cert o sistemas
                                                        informáticos o redes conectadas a través de piratería, extracción de
                                                        contraseñas o cualquier otro medio;</span></p>

                                        <p class=paragraph><span lang=es>v.<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                                        </span></span><span lang=es>No violar los derechos de terceros, como los derechos de
                                                        privacidad, confidencialidad, entre otros;</span></p>

                                        <p class=paragraph><span lang=es>vi.<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                                        </span></span><span lang=es>No recolectar, recopilar, almacenar o tratar información de
                                                        carácter personal o datos de otros usuarios.</span></p>

                                        <p class=paragraph><span lang=es>vii.<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                                        </span></span><span lang=es>No violar cualquier ley o regulación, nacional o internacional;</span></p>

                                        <p class=paragraph><span>&nbsp;</span></p>

                                        <p class=paragraph><span>El incumplimiento a lo anterior
                                                        podrá derivar en la baja del Usuario y/o en la terminación del contrato con las
                                                        Empresas Usuarias de 11 Cert, según corresponda, sin perjuicio de la apuración
                                                        de los daños y perjuicios ocasionados a Telefónica y/o a terceros que resulten
                                                        afectados.</span></p>

                                        <p class=paragraph><span>&nbsp;</span></p>

                                        <p class=paragraph><span class=normaltextrun><b><span>5.2.<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                                                        </span></span></b></span><span class=normaltextrun><b><span> Obligaciones de TELEFÓNICA</span></b></span><span class=normaltextrun><b><span>&nbsp;</span></b></span></p>

                                        <p class=paragraph><span class=normaltextrun><b><span>&nbsp;</span></b></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>Telefónica
                                                                se compromete a ofrecer a los Usuarios y Empresas Usuarias de 11 Cert el servicio
                                                                en las condiciones y conforme a las garantías establecidas en estos Términos y
                                                                Condiciones.</span></span></p>

                                        <p class=paragraph><span>&nbsp;</span></p>

                                        <p class=paragraph><span class=normaltextrun><b><span>6.<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></b></span><span class=normaltextrun><b><span>CONFIDENCIALIDAD</span></b></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>&nbsp;</span></span></p>

                                        <p class=MsoNormal><span>Tendrá
                                                        carácter de información confidencial, respecto a Telefónica, el software y la
                                                        documentación asociada, así como cualquier copia total o parcial de los mismos,
                                                        los conceptos de programa, las bases de datos y software de terceros
                                                        licenciados con o como parte de 11 Cert; y la información de Telefónica y de
                                                        sus filiales registrada en los módulos de 11 Cert. La información confidencial
                                                        de Telefónica no podrá divulgarse a terceros por parte de los Usuarios.</span></p>

                                        <p class=paragraph><span class=normaltextrun><span>&nbsp;</span></span></p>

                                        <p class=paragraph><span class=normaltextrun><b><span>7.<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></b></span><span class=normaltextrun><b><span>PROTECCIÓN
                                                                        DE DATOS DE CARACTÉR PERSONAL</span></b></span><span class=normaltextrun><b><span>&nbsp;</span></b></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>&nbsp;</span></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>La
                                                                regulación del tratamiento de tus datos como Usuario del 11 Cert se encuentra
                                                                en la Política de Privacidad, accesible a través de este enlace <a href="https://11certools.d-consumer.com/politicadeprivacidad">https://11certools.d-consumer.com/politicadeprivacidad</a></span></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>&nbsp;</span></span></p>

                                        <p class=paragraph><span>&nbsp;</span></p>

                                        <p class=paragraph><span class=normaltextrun><b><span>8.<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></b></span><span class=normaltextrun><b><span>PROPIEDAD
                                                                        INDUSTRIAL E INTELECTUAL</span></b></span><span class=normaltextrun><b><span>&nbsp;</span></b></span></p>

                                        <p class=paragraph><span>&nbsp;</span></p>

                                        <p class=MsoNormal><span lang=es>&nbsp;</span></p>

                                        <p class=MsoNormal><span lang=es>En el marco de estos Términos y Condiciones, los &quot;<b>Derechos
                                                                de propiedad</b> <b>intelectual</b></span><span lang=es>&quot;  incluyen todos los derechos de propiedad
                                                        intelectual e industrial, registrados y no registrados, incluyendo, sin
                                                        limitación: patentes, derechos de </span><span lang=es>diseño, modelos de utilidad u otros derechos de invención
                                                        similares, derechos de autor, marcas, signos distintivos, secretos comerciales,
                                                        derechos de confidencialidad y cualquier otro derecho de propiedad intangible.
                                                        Estos derechos incluyen, sin limitación, todas las solicitudes, renovaciones,
                                                        etc; de  cualquiera de los derechos anteriores, en cualquier país.</span></p>

                                        <p class=MsoNormal><span>&nbsp;</span></p>

                                        <p class=MsoNormal><span lang=es>Todos los Derechos de Propiedad Intelectual de 11 Cert pertenecen
                                                        en exclusiva a Telefónica Ninguna previsión de estos Términos y Condiciones se
                                                        considerará que otorgue a cualquier tercero (Usuarios de 11 Cert o cualquier
                                                        tercero) el derecho de modificar, copiar, distribuir, transmitir, mostrar,
                                                        ejecutar, reproducir, publicar, licenciar, hacer ingeniería inversa, crear
                                                        obras derivadas, transferir o vender 11 Cert. </span></p>

                                        <p class=MsoNormal><span lang=es>&nbsp;</span></p>

                                        <p class=MsoNormal><span lang=es>Cualquier modificación o trabajo derivado de 11 Cert que se
                                                        realice en contravención de los estipulado en esta cláusula, será propiedad
                                                        exclusiva de Telefónica y se cederá de forma inmediata a ésta,sin que
                                                        corresponda ningún tipo de remuneración a favor de quien la ejecute y sin
                                                        perjuicio de cualesquiera acciones legales que Telefónica pudiera emprender, en
                                                        defensa de sus derechos.</span></p>

                                        <p class=paragraph><span>&nbsp;</span></p>

                                        <p class=paragraph><span class=normaltextrun><b><span>9.<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></b></span><span class=normaltextrun><b><span>RENUNCIAS
                                                                        A GARANTÍAS Y LIMITACIÓN DE RESPONSABILIDAD</span></b></span><span class=normaltextrun><b><span>&nbsp;</span></b></span></p>

                                        <p class=paragraph><span>&nbsp;</span></p>

                                        <p class=paragraph><span>9.1.<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                                        </span></span><span class=normaltextrun><b><span> Descargo</span></b></span><span class=eop><span>&nbsp;</span></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>Telefónica
                                                                se compromete a utilizar las medidas de seguridad adecuadas y conforme a los
                                                                estándares de mercado para garantizar la seguridad e integridad de 11 Cert a
                                                                sus Usuarios.</span></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>&nbsp;</span></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>Sin
                                                                embargo, no se garantiza que el servicio no pueda verse afectado por algún tipo
                                                                de virus u otros componentes dañinos. Tampoco se garantiza la seguridad de los
                                                                contenidos que los usuarios registren en 11 Cert. </span></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>&nbsp;</span></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>Sin
                                                                embargo, Telefónica se compromete a adoptar las medidas necesarias para
                                                                solucionar cualquier incidente de seguridad, conforme a los estándares de
                                                                mercado, de forma ágil y eficaz.</span></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>&nbsp;</span></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>Telefónica
                                                                no se hace responsable de las pérdidas o daños, eventos de fuerza mayor y
                                                                cualquier otra reclamación relacionada con o derivada por el incumplimiento de
                                                                estos Términos y Condiciones por los Usuarios de 11 Cert.</span></span><span class=eop><span>&nbsp;</span></span></p>

                                        <p class=paragraph><span class=eop><span>&nbsp;</span></span></p>

                                        <p class=paragraph><span class=normaltextrun><b><span>9.2.<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                                                        </span></span></b></span><span class=normaltextrun><b><span>Indemnidad</span></b></span><span class=normaltextrun><b><span>&nbsp;</span></b></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>Los
                                                                Usuarios de 11 Cert, de forma individual, a discreción de Telefónica,
                                                                mantendrán a Telefonica indemnes y exenta de toda responsabilidad frente a
                                                                cualquier tipo de reclamación surgida o relacionada con un mal uso de 11 Cert y
                                                                de su contenido; por la violación de estos Términos y Condiciones o de la
                                                                normativa aplicable; la violación de los derechos u obligaciones de un tercero;
                                                                o por negligencia o dolo.</span></span></p>

                                        <p class=paragraph><span class=eop><span>&nbsp;</span></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>Telefónica
                                                                declara que 11 Cert no infringe derechos de terceros y que  mantendrá indemnes
                                                                y exentos de responsabilidad  a los Usuarios respecto de cualquier reclamación
                                                                o responsabilidad derivada de acciones de violación de derechos de propiedad
                                                                intelectual en relación con el 11 Cert, siempre que  la reclamación o demanda
                                                                no sea derivada de un uso inadecuado de 11 Cert y/o de cualquier infracción a
                                                                los derechos de terceros por parte de los Usuarios y/o de un incumplimiento de
                                                                las restricciones establecidas en la cláusula 8. El usuario deberá notificar a
                                                                Telefónica de forma inmediata acerca de una reclamación o demanda de tercero,
                                                                proporcionándole toda la información y documentación correspondiente, y deberá
                                                                permitir que Telefónica asuma el control de la defensa.</span></span></p>

                                        <p class=paragraph><span class=eop><span>&nbsp;</span></span></p>

                                        <p class=paragraph><span class=normaltextrun><b><span>10.<span>&nbsp;&nbsp; </span></span></b></span><span class=normaltextrun><b><span>INTERRUPCIÓN
                                                                        DEL SERVICIO&nbsp;</span></b></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>&nbsp;</span></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>Telefónica
                                                                podrá interrumpir el servicio en caso de un incumplimiento de estos Términos y
                                                                Condiciones.</span></span></p>

                                        <p class=paragraph><span class=eop><span>&nbsp;</span></span></p>

                                        <p class=paragraph><span>Adicionalmente,
                                                        Telefónica podrá interrumpir el servicio para la actualización y mantenimiento
                                                        de la plataforma. </span></p>

                                        <p class=paragraph><span>&nbsp;</span></p>

                                        <p class=paragraph><span class=normaltextrun><b><span>11.<span>&nbsp;&nbsp; </span></span></b></span><span class=normaltextrun><b><span>MISCELÁNEA</span></b></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>&nbsp;</span></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>Si
                                                                alguna cláusula de estos Términos y Condiciones fuera invalidada, no se verán
                                                                afectadas el resto de las cláusulas. Estos Términos y Condiciones y sus
                                                                referencias constituyen el acuerdo entre el Usuario de 11 Cert y Telefónica en
                                                                relación con las condiciones de uso de la herramienta y, en caso de terminación,
                                                                sobrevivirán las siguientes cláusulas: 8 “propiedad intelectual”, 9.2
                                                                “Indemnidad”, 6 “confidencialidad”, 7 “protección de datos de carácter
                                                                personal”, 11. Miscelánea, 13. “Ley Aplicable y Resolución de Conflictos”.</span></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>&nbsp;</span></span></p>

                                        <p class=paragraph><span class=normaltextrun><b><span>12.<span>&nbsp;&nbsp; </span></span></b></span><span class=normaltextrun><b><span>LEY
                                                                        APLICABLE Y RESOLUCIÓN DE CONFLICTOS&nbsp;</span></b></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>&nbsp;</span></span></p>

                                        <p class=paragraph><span class=normaltextrun><span>Estas
                                                                Condiciones se rigen por la legislación española y cualquier controversia que
                                                                pueda surgir en relación con las mismas se somete a la jurisdicción de los
                                                                Juzgados y Tribunales de Madrid, España.</span></span></p>

                                        <p class=paragraph><span class=eop><span>&nbsp;</span></span></p>

                                        <p class=paragraph><span class=eop><span>Telefónica
                                                                Digital España, S.L.U.</span></span></p>

                                        <p class=paragraph><span class=eop><span>&nbsp;</span></span></p>

                                        <p class=paragraph><span class=eop><span>Fecha de
                                                                actualización: 12/01/2023</span></span></p>

                                        <p class=MsoNormal><span>&nbsp;</span></p>

                                </div>
                        </div>
                </div>
        </div>
        <?php getfooter() ?>
</body>

</html>
