name: Crear Release

on:
  push:
    tags:
      - '[0-9]*'
  workflow_dispatch:

jobs:
  release:
    name: Publicar release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Crear release con notas automáticas
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
